TheOdinProject/theodinproject

getting_involved.md

#105 
Video is legit, but let me know if it is not what you are looking for or looking for something different.

adds a video to the [watch this] call in the getting started guide.

---

app/controllers/contacts_controller.rb

Hi guys,
I am keen to contribute to the project. And have tried starting by improving some code in the contacts controller.
Please review my work.
Thx :)

Improve contacts controller

---

app/views/static_pages/_sg_js.html.erb

the link to Sunday's hangout will be: https://plus.google.com/events/cden432o17689bafkrv9tsfulgk

corrected the link to google community

---

db/seeds.rb

Putting front-end frameworks before server-side programming
First time committing here, let me know if I made any mistakes.
In reference to https://github.com/TheOdinProject/curriculum/issues/2878

Reorder Javascript section

---

app/views/shared/_social.html.erb

Adds 25px of width to Facebook button on front page.

Fix Facebook like button display issue

---

script/rails

- These folders were a version of the old `rails`

Remove the folders `script` and `plugins`.

---

db/seeds.rb

- Remove espace and blank line.
- Change hash format ruby 1.8 to ruby 1.9.
e.g: `:key => 'value'` to `key: 'value'`
- Add some comments as documentation. Use [tomdoc](http://tomdoc.org) format.

Improve the `seed.rb`

---

db/seeds.rb

This updates the seeds for the name change of `how your computer works` to `command line basics`

updated seeds for command line basics name change

---

Gemfile
Gemfile.lock
doc/linux_setup.md
spec/features/courses_lessons_spec.rb
spec/features/search_spec.rb
spec/features/static_pages_spec.rb
spec/spec_helper.rb
spec/support/javascript.rb

Tests now run in 20-30% less time for me, and I haven't seen any sporadic failures either in this branch.
@KevinMulhern Can you review?

Move JS tests from Selenium/Firefox to PhantomJS

---

db/seeds.rb

This adds a new linked lists project to the ruby course

Added linked lists project to seeds

---

db/seeds.rb

updated seed files

---

doc/mac_setup.md

I added a link to a resource that helped my get past issues I ran into following the normal guide.

Add info to MacOSX Setup

---

app/views/shared/_navbar.html.erb

Remove forum link

---

db/seeds.rb

This adds the new standalone dev tools lesson to web dev 101.

Added developer tools lesson to seeds

---

db/seeds.rb

Fixes minor typo

---

app/models/lesson.rb
lib/tasks/curriculum.rake
spec/models/lesson_spec.rb

Just moved some things around so this method is easier to understand.

Made the import content method easier to understand

---

app/assets/stylesheets/lessons.scss
db/seeds.rb

2 new git lessons and one new project for web dev 101

Added new git lessons to the seed files

---

app/models/lesson.rb
db/seeds.rb
spec/models/lesson_spec.rb

This adds the new joining chat lesson to web dev 101

added new joining community lesson

---

features/lesson_completion.feature
features/step_definitions/lesson_steps.rb

Tasks done:
- Add a scenario to emulate the user experience when competing all lessons in a course
- Replace double quotes with single quotes wherever possible to stay consistent

Add cuke steps for completion of all lessons in a course

---

.travis.yml
app/controllers/static_pages_controller.rb
spec/controllers/static_pages_controller_spec.rb

This makes the static pages controller more maintainable and adds unit tests for this controller. There are also some improvements to Travis included.
Fixes:
https://github.com/TheOdinProject/theodinproject/issues/201
https://github.com/TheOdinProject/theodinproject/issues/200

refactored and added unit test for static pages controller

---

features/lesson_navigation.feature
features/step_definitions/navigation_steps.rb

Add cuke scenarios for lesson navigation feature

---

app/helpers/users_helper.rb
app/services/gravatar_url_builder.rb
app/services/social_media_link.rb
spec/helpers/users_helper_spec.rb
spec/services/gravatar_url_builder_spec.rb
spec/services/social_media_link_spec.rb

This is a refactor of the users helper, it also adds unit tests for this helper.
Fixes:
https://github.com/TheOdinProject/theodinproject/issues/222

Refactored users helper and added unit tests

---

app/helpers/application_helper.rb
app/helpers/lessons_helper.rb
app/views/shared/_navbar.html.erb
spec/helpers/lessons_helper_spec.rb

This is a refactor of the lessons helper, it also cleans up the unit tests.
fixes https://github.com/TheOdinProject/theodinproject/issues/221

refactored lesson helper and added unit tests

---

.rspec
spec/controllers/courses_controller_spec.rb
spec/controllers/lesson_completions_controller_spec.rb
spec/controllers/omniauth_callbacks_controller_spec.rb
spec/controllers/sitemap_controller_spec.rb
spec/controllers/static_pages_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/features/auth_spec.rb
spec/features/courses_lessons_spec.rb
spec/features/email_spec.rb
spec/features/search_spec.rb
spec/features/signup_spec.rb
spec/features/smart_redirect.rb
spec/features/users_spec.rb
spec/helpers/admin_flash_helper_spec.rb
spec/helpers/lessons_helper_spec.rb
spec/helpers/users_helper_spec.rb
spec/mailers/user_mailer_spec.rb
spec/models/ad_spec.rb
spec/models/admin_flash_spec.rb
spec/models/lesson_completion_spec.rb
spec/models/section_spec.rb
spec/models/user_spec.rb
spec/rails_helper.rb
spec/services/social_media_link_spec.rb
spec/spec_helper.rb
spec/tasks/curriculum_spec.rb

This cleans up the duplication between the spec_helper and rails_helper file that was left over from the last rails upgrade.
Fixes: https://github.com/TheOdinProject/theodinproject/issues/228

cleaned up spec_helper and rails_helper

---

app/helpers/application_helper.rb
app/views/courses/index.html.erb
app/views/lessons/index.html.erb
app/views/lessons/show.html.erb
app/views/shared/_head.html.erb
spec/helpers/application_helper_spec.rb

Refactor application helper

---

app/views/lesson_completions/create.js.erb

Update progress tracking bar on lesson completion

---

db/migrate/20161017232509_remove_title_and_title_url_index_from_courses.rb
db/schema.rb

Remove title and title_url indices from courses table.

---

app/assets/javascripts/forums.js.coffee
app/assets/javascripts/splash_emails.js.coffee

Remove splash_email.js and forum.js from assets

---

features/lesson_completion.feature
features/step_definitions/lesson_steps.rb

Add cuke scenarios for lesson completions from lesson page

---

app/controllers/courses_controller.rb
app/models/course.rb
app/views/courses/show.html.erb
app/views/shared/_pt_bar.html.erb
spec/controllers/courses_controller_spec.rb
spec/models/course_spec.rb

I went through the site with [Bullet](https://github.com/flyerhzm/bullet) and fixed any n+1 queries it found 😄

Removed a few n+1 queries

---

app/views/courses/show.html.erb
app/views/shared/_pt_bar.html.erb

This removes includes from a couple of the views as they had a negative impact on performance.

removed includes from the view

---

db/migrate/20161019203200_drop_unused_tables.rb
db/schema.rb

* content_activation table
* content_bucket table
* user_prefs table

Dropped unused database tables

---

spec/models/section_spec.rb

Refactor sections model spec

---

app/controllers/lesson_completions_controller.rb
app/views/courses/show.html.erb
app/views/lesson_completions/create.js.erb
app/views/shared/_completion_percent.html.erb
spec/controllers/lesson_completions_controller_spec.rb

Fixes #259 
Tasks done:
- Refactored lesson completions controller and rspec tests
- Cleaned up `create.js.erb`

Refactor lesson completions controller and rspec tests

---

app/controllers/lessons_controller.rb
app/models/ad.rb
spec/controllers/lessons_controller_spec.rb
spec/models/ad_spec.rb

Add tests for ad model

---

app/models/admin_flash.rb
spec/models/admin_flash_spec.rb
spec/models/lesson_completion_spec.rb

fixes https://github.com/TheOdinProject/theodinproject/issues/261

Refactored admin flash spec

---

Gemfile
Gemfile.lock
features/step_definitions/user_steps.rb
features/support/capybara_email.rb
features/user_management/user_email_signup.feature

Add cuke tests for user signing up via email

---

features/step_definitions/users_steps.rb
features/support/env.rb
features/users/sign_up.feature

Fixes https://github.com/TheOdinProject/theodinproject/issues/278

added cuke for signing up with github

---

app/views/static_pages/faq.html.erb
app/views/user_mailer/welcome_email.html.erb
app/views/user_mailer/welcome_email.text.erb
config/routes.rb

Fix studygroup routing issue

---

features/step_definitions/sign_in_steps.rb
features/users/sign_in.feature

fixes https://github.com/TheOdinProject/theodinproject/issues/280

Added cuke for signing in with Github

---

app/views/user_mailer/welcome_email.html.erb
app/views/user_mailer/welcome_email.text.erb
spec/features/email_spec.rb
spec/features/signup_spec.rb

- Fixes lesson url in the email
- And fixes malformed urls in the email.

Fix broken urls in the plaintext version of the welcome email

---

features/step_definitions/sign_out.rb
features/users/sign_out.feature

Fixes https://github.com/TheOdinProject/theodinproject/issues/296

Added cuke for signing out

---

features/step_definitions/cancel_account_steps.rb
features/users/deleting_account.feature

Fixes https://github.com/TheOdinProject/theodinproject/issues/299

Added cuke for deleteing user account

---

features/step_definitions/link_omniauth.rb
features/users/adding_omniauth.feature

fixes https://github.com/TheOdinProject/theodinproject/issues/295

Added cuke for linking github account to existing user

---

app/controllers/omniauth_callbacks_controller.rb
app/services/link_omniauth.rb
app/services/new_or_existing_omniauth_user.rb
spec/controllers/omniauth_callbacks_controller_spec.rb
spec/features/email_spec.rb
spec/features/signup_spec.rb
spec/rails_helper.rb
spec/services/link_omniauth_spec.rb
spec/services/new_or_existing_omniauth_user_spec.rb

Fixes https://github.com/TheOdinProject/theodinproject/issues/301

Refactored ominauth callbacks controller

---

app/controllers/application_controller.rb
app/services/smart_redirect.rb
features/step_definitions/sign_out.rb
features/users/sign_out.feature
spec/controllers/application_controller_spec.rb
spec/rails_helper.rb
spec/services/smart_redirect_spec.rb

Fixes https://github.com/TheOdinProject/theodinproject/issues/310

Refactored application controller

---

features/step_definitions/confirmation_steps.rb
features/step_definitions/lesson_steps.rb
features/step_definitions/link_omniauth.rb
features/support/auth_helpers.rb
features/users/confirmation.feature

fixes https://github.com/TheOdinProject/theodinproject/issues/308

Added cuke to ensure the user cannot login after 2 days if they have not confirmed

---

features/step_definitions/confirmation_steps.rb
features/step_definitions/reset_password_steps.rb
features/support/auth_helpers.rb
features/users/confirmation.feature
features/users/reset_password.feature

Add cuke scenarios for password reset feature

---

app/controllers/application_controller.rb
app/controllers/registrations_controller.rb
spec/controllers/registrations_controller_spec.rb

Fixes: https://github.com/TheOdinProject/theodinproject/issues/316

Refactored registrations controller

---

app/models/user.rb

added in null check

---

app/controllers/registrations_controller.rb
features/step_definitions/edit_account_steps.rb
features/users/edit_account.feature

fixes https://github.com/TheOdinProject/theodinproject/issues/304

fixed bug with omniauth users needing a password when editing their account

---

lib/tasks/curriculum.rake
spec/tasks/curriculum_spec.rb

Refactor curriculum update rake task and spec

---

app/assets/javascripts/analytics.js.erb

Track previous lesson and next lesson link clicks for analytics

---

app/assets/javascripts/analytics.js.erb
app/views/shared/_navbar.html.erb

Track click events on the gitter chat link

---

db/seeds.rb

In preparation for removing twitter spambot project from Ruby on the Web less.

remove references to twitter spambot

---

.rubocop.yml
app/controllers/application_controller.rb
app/controllers/courses_controller.rb
app/controllers/lesson_completions_controller.rb
app/controllers/lessons_controller.rb
app/controllers/registrations_controller.rb
app/controllers/sitemap_controller.rb
app/controllers/static_pages_controller.rb
app/controllers/users_controller.rb

Fix rubocop issues

---

features/step_definitions/edit_account_steps.rb
features/step_definitions/edit_profile_steps.rb
features/users/edit_account.feature
features/users/edit_profile.feature

Fixes: https://github.com/TheOdinProject/theodinproject/issues/281

Added cukes for edit user profile and edit user account

---

app/models/ability.rb
app/models/ad.rb
app/models/admin_flash.rb
app/models/course.rb
app/models/lesson.rb
app/models/lesson_completion.rb
app/models/section.rb
app/models/user.rb

Still, we get 3 issues from rubocop's analysis. Not sure how to resolve them.
Fixes #354

Fix rubocop issues in models

---

app/models/lesson.rb
app/models/project.rb
app/models/user.rb
db/migrate/20161127171855_create_projects.rb
db/schema.rb
spec/factories/factories.rb
spec/models/project_spec.rb

Add a project model and set up relationships

---

app/controllers/projects_controller.rb
config/routes.rb
spec/controllers/projects_controller_spec.rb
spec/support/shared_examples.rb

Complete create, update and destroy actions for projects

---

app/controllers/projects_controller.rb
app/models/project.rb
config/routes.rb
spec/controllers/projects_controller_spec.rb

Add all_submissions and recent_submissions for projects

---

app/controllers/projects_controller.rb
app/controllers/users_controller.rb
app/models/ability.rb
db/migrate/20161224052711_add_admin_field_to_users.rb
db/schema.rb
spec/controllers/projects_controller_spec.rb
spec/factories/factories.rb
spec/models/ability_spec.rb

Allow admin to update and destroy project submissions

---

app/assets/javascripts/analytics.js.erb
app/assets/stylesheets/site.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_sidecar.html.erb

Embed gitter chat

---

app/assets/javascripts/faq.js
app/assets/stylesheets/components/faq.scss
app/assets/stylesheets/global.scss
app/assets/stylesheets/mixins.scss
app/assets/stylesheets/settings.scss
app/views/static_pages/faq.html.erb

Redesign FAQ page

---

app/assets/stylesheets/components/success_stories.scss
app/controllers/static_pages_controller.rb
app/views/layouts/application.html.erb
app/views/static_pages/success_stories.html.erb
config/routes.rb
spec/controllers/static_pages_controller_spec.rb

Add success_stories page based on the layout on issue #403 
The style was made on the existing success_stories.scss

Add success_stories page

---

app/controllers/application_controller.rb
app/views/lessons/show.html.erb
app/views/user_mailer/welcome_email.html.erb
app/views/user_mailer/welcome_email.text.erb
features/create_project_submission.feature
spec/controllers/lessons_controller_spec.rb
spec/controllers/projects_controller_spec.rb
spec/factories/factories.rb
spec/mailers/user_mailer_spec.rb

Thanks to @KevinMulhern for actually fixing it :)

Fix failing cuke tests

---

app/assets/stylesheets/components/faq.scss
app/assets/stylesheets/settings.scss
app/views/static_pages/faq.html.erb

Addresses @adachiu 's [feedback comments](https://github.com/TheOdinProject/theodinproject/issues/400#issuecomment-294338021)

Tweak the FAQ page

---

app/assets/javascripts/courses.js
app/assets/javascripts/courses.js.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/courses.scss
app/assets/stylesheets/components/faq.scss
app/assets/stylesheets/components/logo.scss
app/assets/stylesheets/global.scss
app/assets/stylesheets/settings.scss
app/decorators/course_decorator.rb
app/models/course.rb
app/views/courses/_course_card.html.erb
app/views/courses/_course_completion_indicator.html.erb
app/views/courses/_course_description.html.erb
app/views/courses/_course_overview.html.erb
app/views/courses/index.html.erb

Course card:
- **Incomplete state**
- **Completed state**

Redesign the curriculum page

---

app/assets/stylesheets/global.scss

Redesign fix #416 
global.scss updated to handle new global designs for H1, H2, and H3.

Update global font styles for H1, H2, H3

---

app/assets/stylesheets/components/about.scss

I didn't fix every problem.. but I fixed the overflow on widths < 350px

convert fixed-widths

---

app/assets/stylesheets/components/footer.scss
app/helpers/application_helper.rb
app/views/shared/_footer.html.erb

Added blog link to application_helper, use in footer

Footer links change

---

app/assets/stylesheets/components/contributing.scss
app/helpers/application_helper.rb
app/views/static_pages/_contributors.html.erb
app/views/static_pages/contributing.html.erb
db/schema.rb

Redesign contributing page

---

app/assets/stylesheets/components/how_it_works.scss
app/views/static_pages/home/_how_it_works.html.erb

added a new class with height of 165px which is the height of the first image.

issue #414 Alignment for How It Works

---

app/assets/stylesheets/components/footer.scss
app/assets/stylesheets/responsive.scss

fix alignment issues on the footer

fix footer links

---

app/assets/stylesheets/components/logo.scss
app/views/shared/_navbar.html.erb

navbar fix

---

app/views/static_pages/contributing.html.erb

make background gradient full page width
change link text to prevent overflow on small screens

small tweaks

---

app/assets/images/odin-logo.svg

switched logo

---

app/assets/stylesheets/components/logo.scss
app/assets/stylesheets/components/navbar.scss
app/assets/stylesheets/responsive.scss
app/views/shared/_navbar.html.erb
app/views/static_pages/home.html.erb

mobile navbar

---

app/assets/stylesheets/components/home_page_header.scss
app/assets/stylesheets/components/how_it_works.scss
app/assets/stylesheets/responsive.scss
app/views/static_pages/home/_how_it_works.html.erb

homepage header/how-it-works tweaks

---

app/assets/javascripts/navbar.js
app/assets/stylesheets/components/logo.scss
app/assets/stylesheets/components/navbar.scss
app/views/shared/_navbar.html.erb

Cody navbar

---

app/assets/javascripts/navbar.js
app/assets/stylesheets/components/logo.scss
app/assets/stylesheets/components/navbar.scss

Navbar tweaks

---

app/assets/stylesheets/components/hero.scss
app/views/static_pages/home.html.erb

tweak linear gradient

---

app/views/shared/_footer.html.erb

make blog link open in new tab

---

app/assets/stylesheets/components/about.scss
app/assets/stylesheets/components/navbar.scss
app/assets/stylesheets/components/success_stories.scss
app/views/static_pages/about.html.erb
app/views/static_pages/about/_contact.html.erb
app/views/static_pages/home/_success_stories.html.erb

About page gif

---

app/assets/stylesheets/components/about.scss
app/assets/stylesheets/components/contributing.scss
app/assets/stylesheets/components/home_page_header.scss
app/assets/stylesheets/components/success_stories.scss
app/assets/stylesheets/global.scss
app/views/static_pages/contributing.html.erb
app/views/static_pages/success_stories.html.erb

Make h1 styles globally consistent

---

app/assets/stylesheets/components/navbar.scss

make navbar 100% height

---

app/assets/javascripts/navbar.js

Setup event listener on turbolinks:load

---

app/assets/stylesheets/components/card.scss
app/assets/stylesheets/components/contributing.scss
app/assets/stylesheets/components/courses.scss
app/assets/stylesheets/components/success_stories.scss
app/assets/stylesheets/global.scss
app/assets/stylesheets/mixins.scss
app/views/courses/_course_card.html.erb
app/views/courses/_course_overview.html.erb
app/views/static_pages/contributing.html.erb
app/views/static_pages/success_stories.html.erb

create card base

---

app/helpers/application_helper.rb

I sure hope this works :crossed_fingers:

Update FAQ Links

---

README.md

fix README - issue #533

---

app/assets/stylesheets/components/footer.scss
app/views/shared/_footer.html.erb

changed to font awesome icons

---

app/assets/stylesheets/components/about.scss
app/assets/stylesheets/components/bottom_cta.scss
app/assets/stylesheets/components/courses.scss
app/assets/stylesheets/components/faq.scss
app/assets/stylesheets/components/user_settings.scss
app/assets/stylesheets/typography.scss
app/views/courses/_course_overview.html.erb
app/views/devise/registrations/edit.html.erb
app/views/static_pages/about.html.erb
app/views/static_pages/about/_intro.html.erb

made a bunch of small tweaks as suggested in the review document

Review edits

---

CONTRIBUTORS.md
app/views/static_pages/_contributors.html.erb

and link it to the contribution page.

Create 'CONTRIBUTORS.md' file

---

app/assets/stylesheets/components/home_page_header.scss

this media query was messing with stuff... and we don't need it anyway.

fix horizontal scrolling on homepage

---

app/assets/stylesheets/components/curriculum_details.scss
app/views/static_pages/home/_curriculum_details_title.html.erb

Removes homepage path text

---

app/views/courses/course/_section.html.erb

Fixes https://github.com/TheOdinProject/theodinproject/issues/547

added card class to sections

---

app/assets/stylesheets/components/curriculum_details.scss

Vertically align course badge content on xs size and below

---

app/views/shared/_footer.html.erb

#574 Fixed link address to Gitter room on footer.

Fix Gitter link

---

app/assets/stylesheets/components/faq.scss

I hope I did it correctly this time 😁

Fixed the faq-accordian

---

app/assets/stylesheets/components/success_stories.scss
app/views/static_pages/success_stories.html.erb
config/database.yml

* Remove completed course text from success stories card
* Bold student_name in success stories card
* Include job title beside name, not bold
* Change margin-bottom for name section to 10px
* Stack and center avatar and text on success stories card

Tweak success stories

---

app/assets/stylesheets/components/login_page.scss
app/assets/stylesheets/global.scss
app/assets/stylesheets/mixins.scss
app/controllers/application_controller.rb
app/controllers/registrations_controller.rb
app/controllers/static_pages_controller.rb
app/views/courses/course/_sections.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/_confirm_email.html.erb
spec/controllers/static_pages_controller_spec.rb

#555 Fixed h1 and input styles on sign in and sign up pages.

Fix styling on sign in and sign up pages

---

app/models/user.rb
spec/controllers/omniauth_callbacks_controller_spec.rb

The omniauth login was not working because it was trying to get details from the wrong hash

Fix Omniauth bug

---

app/controllers/static_pages_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_flash_helper.html.erb
app/views/shared/_flashes.html.erb
app/views/shared/_navbar_and_flashes.html.erb
app/views/static_pages/home.html.erb
spec/controllers/static_pages_controller_spec.rb

Tasks done:
- Display bootstrap flash messages by removing `in` class with `show` class
- Navbar is displayed in all the pages, hence `@navbar` is useless, removed it
- Fixed failing specs
- Did some cosmetic changes

Cleanup application layout

---

app/controllers/courses_controller.rb
app/decorators/course_decorator.rb
app/models/course.rb
app/views/courses/_course_overview.html.erb
app/views/courses/index.html.erb
app/views/courses/show.html.erb
spec/controllers/courses_controller_spec.rb
spec/decorators/course_decorator_spec.rb
spec/models/course_spec.rb

Just some refactoring around the course controller and some tests for the course decorator.

Refactored the course controller

---

app/assets/stylesheets/components/login_page.scss
app/views/devise/registrations/new.html.erb

#596 Tasks performed:
* Added link to terms of use above sign up buttons.

Link to terms of use on sign up page

---

app/assets/stylesheets/components/lessons.scss
app/views/lessons/show.html.erb

* Narrowed the lesson content to make it easier to read
* Added basic img styles

Lesson Page Tweaks

---

app/views/static_pages/about/_contact.html.erb

Completes https://github.com/TheOdinProject/theodinproject/issues/594

added a contact email to the contact section of about page

---

app/assets/stylesheets/components/login_page.scss
app/views/courses/index.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

Tweaks to the auth pages raised from last review.

tweaked the auth page

---

app/assets/stylesheets/components/dashboard.scss
app/assets/stylesheets/components/logo.scss
app/assets/stylesheets/components/navbar.scss
app/assets/stylesheets/components/user_settings.scss
app/helpers/users_helper.rb
app/models/user.rb
app/views/users/_profile_card.html.erb
app/views/users/_skill_progress.html.erb
spec/helpers/users_helper_spec.rb

redesign dashboard (Issue #617 )

Dashboard tweaks

---

app/assets/stylesheets/components/navbar.scss
app/views/shared/_user_dropdown.html.erb

Fixed the shadows in this pull request as opposed to my screenshot in the issue#615 issue.

#615  Fix style around dropdown and follow style guide

---

app/assets/stylesheets/components/login_page.scss
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_user_dropdown.html.erb

going through the app looking for various accessibility issues... then fixing them.
fixes #629

a11y fixes

---

app/assets/javascripts/navbar.js
app/assets/stylesheets/components/logo.scss
app/assets/stylesheets/components/navbar.scss
app/views/shared/_footer.html.erb
app/views/shared/_logo.html.erb
app/views/shared/_logo_text.html.erb
app/views/shared/_navbar.html.erb
app/views/users/_profile_card.html.erb

- Modified logo to use BEM conventions
- Removed un-needed wrapper div around the logo
- Reduced nesting in the logo style sheet
- Renamed the logo-text partial to "logo"

Cleaned up the logo partial and stylesheet

---

app/assets/stylesheets/components/buttons.scss
app/assets/stylesheets/components/contributing/benefits.scss
app/assets/stylesheets/components/contributing/contributing_options.scss
app/assets/stylesheets/components/contributing/hall_of_fame.scss
app/views/static_pages/contributing.html.erb
app/views/static_pages/contributing/_hall_of_fame.erb

Fixes https://github.com/TheOdinProject/theodinproject/issues/643

Contributing Page Tweaks

---

app/decorators/lesson_decorator.rb
app/decorators/user_decorator.rb
spec/decorators/course_decorator_spec.rb
spec/decorators/lesson_decorator_spec.rb
spec/decorators/user_decorator_spec.rb

This cleans up all of the decorators by removing methods that are no longer used.

Clean up Decorators

---

app/assets/stylesheets/components/success_stories.scss
app/views/static_pages/success_stories.html.erb
config/database.yml
db/seeds/dummy_projects.rb

* Divide contents into two rows
* Mobile: Add margin-top to success stories content
* Mobile: Add centering and display:block to student-name elements
* Mobile: Add centering to photo
* Flush stories content to photo
* Vertically align name/title to photo

Fix issue #645

---

app/assets/stylesheets/components/about/overview.scss
app/views/static_pages/about/_overview.html.erb

Fix overview section in medium and small screen viewports

---

app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/projects/index.html.erb
app/views/static_pages/faq.html.erb
app/views/static_pages/style_guide.html.erb
app/views/static_pages/success_stories.html.erb
app/views/static_pages/terms_of_use.html.erb
app/views/users/show.html.erb

Currently there are quite a few pages that don't have a title. This sets the title on those pages.

Add Titles to all Pages

---

app/assets/javascripts/form_validations.js

Blocks form submission while the form validations fail.
I removed the requirement the presence requirement for the input fields because they all have other validations. This means when a field is empty it won't show "can't be blank" validation.

stop form submit when input invalid

---

app/assets/stylesheets/components/form/form.scss
app/assets/stylesheets/components/settings/settings-card.scss
app/assets/stylesheets/components/settings/settings-section.scss
app/views/devise/registrations/_learning_goal.html.erb
app/views/devise/registrations/_password.html.erb
app/views/devise/registrations/_profile.html.erb

This includes various tweaks to the settings page layout.

Various Improvements to the Settings Page

---

app/assets/stylesheets/components/buttons.scss
app/assets/stylesheets/components/courses/course-section.scss
app/assets/stylesheets/components/courses/section_lessons.scss
app/assets/stylesheets/components/form/form.scss
app/assets/stylesheets/components/settings/settings-card.scss
app/assets/stylesheets/mixins.scss
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/_profile.html.erb
app/views/lessons/show.html.erb
app/views/projects/index.html.erb
app/views/static_pages/contributing/_hall_of_fame.erb
app/views/static_pages/faq.html.erb
app/views/users/show.html.erb

This includes various small tweaks that @adachiu suggested.

tweaks for various pages

---

app/assets/javascripts/form_validations.js

Reverts TheOdinProject/theodinproject#695

Revert "stop form submit when input invalid"

---

app/assets/javascripts/form_validations.js

Reverts TheOdinProject/theodinproject#698

Revert "Revert "stop form submit when input invalid""

---

app/assets/javascripts/prism.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/prism.css

This styles any multiline code blocks on lesson pages, this is shown below:

Style Multiline Code Blocks

---

app/models/course.rb
app/views/sitemap/index.xml.builder
db/migrate/20170827201913_remove_unused_columns_from_course.rb
db/schema.rb
db/seeds.rb

This removes columns we no longer use anywhere on the site.

Remove Unused Columns from Course Table

---

app/assets/javascripts/analytics.js.erb
app/views/courses/show.html.erb
app/views/shared/_lc_index.html.erb

yo homies.. here's somethin a little different.
the great Satin Mulan thought it would be a good idea to track which lessons are completed most often..... so I have added that info to our analytics code.

add lesson data to analytics

---

app/assets/stylesheets/utilities.scss

This removes the red border on form validations, this was raised at last design review.

Remove Border on Form Validations

---

app/assets/stylesheets/components/navbar.scss

Per @adachiu's request at the last review

Make Navbar links bold by default and remove underline hover style

---

app/assets/stylesheets/components/about/about.scss
app/assets/stylesheets/components/dashboard.scss
app/assets/stylesheets/components/settings/settings-card.scss
app/views/static_pages/about/_contact.html.erb
app/views/users/_skills_progress.html.erb

This includes various tweaks to fix issues raised at the last design review
* Changed color of headings on the settings page
* Changed the color of the contact us heading on the about page
* Add instructions for what order courses should be taken in on the dashboard

Various Small Tweaks

---

app/assets/stylesheets/components/navbar.scss
app/assets/stylesheets/components/navbar_modal.scss
app/helpers/application_helper.rb
app/views/shared/_head.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_navbar_modal.html.erb
app/views/shared/_user_dropdown.html.erb
spec/helpers/application_helper_spec.rb

Fixes #712 
Tasks done: 
- Style active links with black color
- Extract navbar modal into a partial
- Make cosmetic changes to `head` partial

Style active links

---

app/assets/stylesheets/components/course-badge.scss
app/assets/stylesheets/components/courses.scss
app/assets/stylesheets/components/courses/banner.scss
app/assets/stylesheets/components/courses/course_card/course_card_header.scss
app/assets/stylesheets/components/progress_circle.scss
app/helpers/application_helper.rb
app/helpers/course_helper.rb
app/services/course_progress.rb
app/views/courses/_course_overview.html.erb
app/views/courses/course/_banner.html.erb
app/views/courses/show.html.erb
app/views/lesson_completions/create.js.erb
app/views/lessons/show.html.erb
app/views/projects/index.html.erb
app/views/shared/_completion_percent.html.erb
app/views/shared/_course_badge.html.erb
app/views/users/_skill_progress.html.erb
app/views/users/show.html.erb
spec/helpers/application_helper_spec.rb
spec/helpers/course_helper_spec.rb
spec/services/course_progress_spec.rb

Completes step two of https://github.com/TheOdinProject/theodinproject/issues/707
This includes the course progress badge that will appear on the curriculum, course, lesson and dashboard pages.

Course Progress Badge

---

app/assets/images/badge-webdev101.svg
app/assets/stylesheets/components/progress_circle.scss
app/views/shared/_course_badge.html.erb

This resolves the third and final step for https://github.com/TheOdinProject/theodinproject/issues/707

Hover Effect for Course Badge

---

app/controllers/courses_controller.rb
app/controllers/lesson_completions_controller.rb
app/controllers/lessons_controller.rb
app/controllers/users_controller.rb
app/decorators/lesson_decorator.rb
app/helpers/application_helper.rb
app/helpers/course_helper.rb
app/models/lesson.rb
app/services/course_progress.rb
app/services/find_lesson.rb
app/views/courses/_course_card.html.erb
app/views/courses/_course_overview.html.erb
app/views/courses/course/_banner.html.erb
app/views/courses/course/_lessons.html.erb
app/views/lesson_completions/create.js.erb
app/views/lessons/_lesson_buttons.html.erb
app/views/lessons/_lesson_completion_button.html.erb
app/views/lessons/_lesson_completion_state.html.erb
app/views/lessons/show.html.erb
app/views/shared/_course_badge.html.erb
app/views/users/_skill_progress.html.erb
app/views/users/_skills_progress.html.erb
spec/controllers/lesson_completions_controller_spec.rb
spec/controllers/lessons_controller_spec.rb
spec/decorators/lesson_decorator_spec.rb
spec/helpers/course_helper_spec.rb
spec/models/lesson_spec.rb
spec/services/find_lesson_spec.rb

With the addition of course progress indicators to the dashboard and
course pages. There was a noticeable slow down in the speed of the pages
This optimizes as many queries as I can find. There is a noticeable performance
improvement with how quickly pages are loading now.

Optimize Queries

---

app/decorators/user_decorator.rb
app/views/users/show.html.erb

Turns off displaying projects in the student dashboard.

Disable projects display in dashboard

---

app/assets/stylesheets/components/courses/banner.scss
app/assets/stylesheets/components/courses/section_lessons.scss
app/assets/stylesheets/components/navbar.scss

* Reduce size of nav links to 1em
* Add margin to lesson/course title in banner
* Change color of completion checkmarks to success green color

Tweaks from Last Review

---

app/assets/stylesheets/components/progress_circle.scss
app/views/shared/_course_badge.html.erb

* Make the badge appear in the inner badge circle when a course is completed
* Change the hover state to reveal the percentage when a course is fully completed

Course Completion Badge Style

---

app/assets/stylesheets/components/courses/banner.scss
app/assets/stylesheets/components/lesson/lesson_header.scss
app/views/lessons/show.html.erb

This is to resolve and close https://github.com/TheOdinProject/theodinproject/issues/720

reduce lesson title bottom margin and change sub title size to h3

---

app/mailers/user_mailer.rb
app/models/user.rb
app/views/layouts/_confirm_email.html.erb
app/views/user_mailer/welcome_email.html.erb
app/views/user_mailer/welcome_email.text.erb
spec/mailers/user_mailer_spec.rb

This ensures the welcome email is sent to the user after they sign up.

Fix Welcome Email

---

app/assets/stylesheets/components/about/overview/overview.scss
app/assets/stylesheets/components/buttons.scss
app/assets/stylesheets/components/progress_circle.scss
app/assets/stylesheets/components/viking_advert.scss
app/views/shared/_course_badge.html.erb
app/views/static_pages/about/_overview.html.erb

Fixes https://github.com/TheOdinProject/theodinproject/issues/761

Fix Issues From Last Review

---

app/assets/stylesheets/components/gitter_floating.scss

Makes the following changes as requested by Ada
.gitter-chat-embed
-removes border-left
-changes opacity of box-shadow to 0.1
..chat-floating-btn
-changes opacity to 0.2

adjustments to gitter button and sidecar css

---

app/models/lesson.rb

Make the site pull from the master branch again now the redesign has been deployed,

change lesson github path back to master branch

---

app/views/devise/sessions/_form.html.erb

fixed form wording for login page

---

app/models/user.rb
db/migrate/20171027030143_remove_unique_user_index.rb
spec/models/user_spec.rb

Removed the unique validation for username on the user model and removed
the unique constraint in the username index on the database.

Remove unique user validation

---

app/views/shared/_head.html.erb

ASCII header with link to our contributing Gitter room.

Add ASCII header

---

db/seeds.rb

in reference to https://github.com/TheOdinProject/curriculum/pull/7439

modified seeds file for lesson addition

---

db/seeds.rb

This updates the repo and curriculum links in the seeds file for the rails course

update seeds for separate rails course

---

db/seeds.rb

added the new JS101 content to our main WD101 page 🎉 
I put it in it's own section:

add new JS content to WD101

---

db/seeds.rb

pulls out the major "projects" from the js101 stuff
looks like this:

pull out js101 projects

---

db/seeds.rb

this links the last two lessons properly.....

Move js final

---

app/views/lessons/show.html.erb

Add a link back to the course overview page on the course badge and course heading on the lesson pages.

add link the lesson badge and course title on lesson pages

---

app/views/devise/registrations/_learning_goal.html.erb
app/views/devise/registrations/_password.html.erb
app/views/devise/registrations/_profile.html.erb
app/views/devise/registrations/edit.html.erb

Fixes #845 
- Set ids for profile, learning goal update and password update forms
- Use local variables inside partials
- Make cosmetic changes

Use different ids for forms in settings page

---

app/assets/javascripts/navbar.js
app/views/shared/_navbar.html.erb

Community Hover Action #856 [here](https://github.com/TheOdinProject/theodinproject/issues/856)

allow for & implement - multiple dropdowns on hover

---

Gemfile
Gemfile.lock

Required to update the gem to enable support for openssl 1.1

update puma gem

---

app/assets/javascripts/analytics.js.erb
app/controllers/lesson_completions_controller.rb
app/views/layouts/application.html.erb
app/views/lessons/_lesson_buttons.html.erb
app/views/lessons/_lesson_completion_state.html.erb

Reverts TheOdinProject/theodinproject#874

Revert "Fix Unique Validation Errors for Lesson Completions"

---

app/views/static_pages/success_stories.html.erb

Fixing issue #879 
My first ever pull request in GitHub.

fixed signup buttom showing when logged

---

db/seeds/06_javascript_course_seeds.rb

Adds new js frameworks lessons to the seeds file.

add js frameworks to seeds file

---

app/assets/javascripts/application.js

This fixes a known security vulnerability in JQuery.

Upgrade from JQuery 1.12 to JQuery3.~

---

app/decorators/course_decorator.rb
db/migrate/20180712020424_change_html_lesson_titles.rb
db/seeds/05_html_css_course_seeds.rb

Because Cody didn't like it, I changed it.

Change html and css course title

---

app/assets/stylesheets/components/card.scss

Add padding to the card body to match the heading

---

app/assets/stylesheets/components/navbar.scss

fixes #939 by adjusting the breakpoint to match the bootstrap navbar
I was having a hard time actually getting the site running locally so someone should actually test this

adjust breakpoint

---

Gemfile
Gemfile.lock
spec/controllers/omniauth_callbacks_controller_spec.rb
spec/controllers/registrations_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/factories/factories.rb
spec/mailers/user_mailer_spec.rb
spec/models/ability_spec.rb
spec/tasks/curriculum_spec.rb

Because FactoryGirl was sexist, thoughtbot changed the name. This updates the gem and specs for the new FactoryBot gem.

update factory girl gem

---

app/models/lesson.rb
config/initializers/timeout.rb
db/seeds.rb
db/seeds/02_ruby_course_seeds.rb
spec/models/lesson_spec.rb

This adds Leos new RSpec lessons to the seeds file.
Also includes:
* Increase timeout as it wasn't long long enough for compiling assets on the fly locally
* Remove un-needed content validation on lesson model
* Ensure that if a lesson cannot be updated during seeding that it will not fail silently.

Add New RSpec Lessons to Seeds File

---

app/views/static_pages/home.html.erb

You could probably remove the word "Full" altogether and not lose anything important to the message.

Fix Inconsistent Capitalization in CTA

---

app/helpers/application_helper.rb

https://forum.theodinproject.com/t/www-theodinproject-com-faq-fix-link/10820

Fixed broken link from FAQ :)

---

app/assets/javascripts/lessons.js

Might not be the best solution but this PR goes along with this: https://github.com/TheOdinProject/curriculum/pull/9632

Add to LESSON_HEADINGS

---

db/seeds/01_web_dev_101_seeds.rb

This update goes with this curriculum change:
https://github.com/TheOdinProject/curriculum/pull/10540

Update command-line-basics location.

---

db/seeds/tracks/front_end.rb
db/seeds/tracks/full_stack_javascript.rb
db/seeds/tracks/full_stack_rails.rb

[Issue](https://github.com/TheOdinProject/theodinproject/issues/1035)

Fix duplicate trackcourse creation in seed

---

config/routes.rb

Solves #1015 where /courses should point to /tracks

redirect /courses to /tracks

---

Gemfile.lock

Release notes can be found at
https://github.com/rack/rack/blob/master/CHANGELOG.md

Update Rack gem to 2.0.8

---

app/assets/javascripts/prism.js
app/assets/stylesheets/prism.css
app/views/layouts/application.html.erb

Adds [Line numbers](https://prismjs.com/plugins/line-numbers/) plugin to Prism.
Fixes #1054

Add line numbers to code blocks

---

app/views/users/_profile_card.html.erb

I believe I've fixed this issue I was having (in chrome):
https://github.com/TheOdinProject/theodinproject/issues/1021

added a div to the user profile card to ensure it stops stretching

---

app/models/user.rb
spec/models/user_spec.rb

This will make the js validations the same for client and server-side
https://github.com/TheOdinProject/theodinproject/issues/1056

update username validation

---

app/helpers/application_helper.rb

changes FAQ to include extra information

---

db/seeds/05_html_css_course_seeds.rb

This is the corresponding pull request to [curriculum issue #11867](https://github.com/TheOdinProject/curriculum/issues/11867) with the [pull request #11868](https://github.com/TheOdinProject/curriculum/pull/11868) . You can find an explanation to these changes and the reason for them over there.

Delete the CSS Grids Lesson

---

db/seeds/02_ruby_course_seeds.rb

Because:
* We want these lessons to be seperate from the new Ruby basics lessons.

Chore: Extract Introductory Ruby Lessons

---

db/seeds/02_ruby_course_seeds.rb
lib/tasks/data_migrations/remove_ruby_basic_lessons.rake

Because:
* New and improved lessons are good for students.
This Commit:
* Replaces the old Ruby Basic lessons with the new ones.
* Introduces a new section for basic projects.
* Adds a data migration to remove the old lessons from the db.

Feature: New Ruby Basic Lessons

---

app/assets/stylesheets/components/gitter_floating.scss
app/javascript/src/js/analytics.js
app/views/shared/_navbar_modal.html.erb

Removes
- Gitter references in analytics code
- Gitter sidebar related CSS

Remove Gitter references

---

app/views/users/_skill.html.erb

Because:
* This was requested by a student and provides a better user experience.

Feature: Course Badges on Dashboard Now Link to Their Course Page

---

.travis.yml
Gemfile
Gemfile.lock
lib/tasks/bundler_audit.rake

Fixes https://github.com/TheOdinProject/theodinproject/issues/1112
Ref: https://docs.travis-ci.com/user/deployment-v2/providers/heroku/
Whenever a build on `master` completes successfully, the code will be deployed to Production.
Note that this means once a PR is merged to `master`, it will be deployed. If we want to have control over the Production deployment, we could add a new branch `develop` and have all PRs submitted against `develop`. Once we want to deploy the changes to Production, we can cherry-pick the commits from `develop` to `master` and push to trigger a build.
This PR also fixes the [broken bundle audit check](https://travis-ci.org/github/TheOdinProject/theodinproject/builds/678347822#L802) on Travis.

Setup Continuous deployment to Production

---

db/seeds/01_web_dev_101_seeds.rb

Update some of the section descriptions for the Overview of the Web Development 101 course.
Changes include:
- Removing a reference to Ruby and Rails from the Installation section, as they are not actually covered there
- Moving a reference to installing software to the Installation section
- Capitalizing GitHub and JavaScript appropriately

Update Web Dev 101 overview section descriptions

---

config/environments/production.rb

Because:
* This was turned off in dev mode and made it through code review

Fix: Forcing SSL

---

db/seeds/04_rails_course_seeds.rb
db/seeds/08_node_js_course_seeds.rb

In reference to:
https://github.com/TheOdinProject/curriculum/issues/16292

Seeds Added for "Preparing for Deployment"

---

.dependabot/config.yml

Adds Dependabot to automate dependency updates.
/cc @KevinMulhern

Setup Dependabot

---

app/controllers/lessons_controller.rb
app/features/project_submission_feature.rb
app/javascript/components/project-submissions/components/submission.js
app/views/lessons/show.html.erb
db/seeds.rb
db/seeds/test_projects.rb
spec/controllers/lessons_controller_spec.rb

Because:
* Displaying the 10 most recent is more performant than displaying all projects.
This Commit:
* Displays the 10 most recent projects in the submissions component on lesson pages.
* Adds some fake projects and users to make this feature easier to test/work with while in development.

Feature: Display 10 most Recent Projects on Lesson Page.

---

app/assets/stylesheets/components/submissions.scss
app/controllers/projects_controller.rb
app/javascript/components/project-submissions/components/edit-submission-form.js
app/javascript/components/project-submissions/components/submission.js
app/javascript/components/project-submissions/components/submissions-list.js
app/javascript/components/project-submissions/containers/project-submissions-container.js
app/javascript/components/project-submissions/index.jsx
app/serializers/project_serializer.rb
app/views/lessons/show.html.erb
spec/serializers/project_serializer_spec.rb

Because:
* Mistakes happen.
This Commit:
* Adds an edit button and modal form.

Feature: Allow Users to Edit Their Submissions

---

app/assets/stylesheets/components/buttons.scss
app/controllers/projects_controller.rb
app/javascript/components/project-submissions/components/edit-submission-form.js
app/javascript/components/project-submissions/containers/project-submissions-container.js

Because:
* Users will want this as an option.

Feature: Allow Users to Delete Their Submission

---

legal_terms_of_use.md

Updated Thinkful's privacy policay and terms of use

---

app/assets/stylesheets/components/form/form.scss
app/assets/stylesheets/components/toggle.scss
app/assets/stylesheets/utilities.scss
app/javascript/components/project-submissions/components/create-submission-form.js
app/javascript/components/project-submissions/components/edit-submission-form.js

Because:
* The styling of this component was messed up after refactoring the custom checkbox in the report form story.

Chore: Fix Create and Edit Form Public Checkbox Styling

---

app/assets/stylesheets/global.scss
app/controllers/project_submissions_controller.rb
app/javascript/components/project-submissions/components/create-form.js
app/javascript/components/project-submissions/components/edit-form.js
app/javascript/components/project-submissions/containers/project-submissions-container.js
app/javascript/components/project-submissions/schemas/project-submission-schema.js
app/models/project_submission.rb
app/validators/url_validator.rb
package.json
spec/models/project_submission_spec.rb
yarn.lock

Because:
* We should ensure users can only enter valid urls.
This Commit:
* Adds a customer server side url validator.
* Returns a error json response from the project submission create and update endpoints.
* Adds a schema validator to ensure url fields are valid client side.
* Triggers validations when a form input has been touched on the project submission forms.
* Disables the submit button if there are any errors on the project submission forms.

Feature: Url Validations for Project Submission Form

---

app/assets/stylesheets/components/project_submissions/submissions.scss
app/javascript/components/project-submissions/components/create-form.js
app/javascript/components/project-submissions/components/submission.js

This Commit:
* Displays an eye icon in place of the flag icon in the users submission to signify if the submission is public or not.
* Sets public to true by default.

Feature: Tweaks to Making a Submission Public

---

app/views/static_pages/contributing.html.erb
app/views/static_pages/contributing/_contributing_options.html.erb

In the file app/views/static_pages/contributing.html.erb,
The sentence ".....and are always looking for people who want join our growing team of maintainers." was missing a "to" between "want" and "join".
In the file app/views/static_pages/contributing/_contributing_options.html.erb,
1. In the sentence "....and ensure it meets our students needs in the ever changing world...", the word "students" was missing an apostrophe.
2. In the sentence "We are always working on new features that improves the platform and helps students in their learning journey.", verbs "improves" and "helps" should be "improve" and "help" respectively.
3. In the sentence "...there is also constant backlog of outstanding issues...", word "constant" was missing an article "a".
4. The sentence "...bugs that need …

Fixed some grammatical mistakes in the Contribute page of the website.

---

app/assets/stylesheets/components/react_modal.scss
app/javascript/components/project-submissions/components/create-form.js
app/javascript/components/project-submissions/components/edit-form.js
app/javascript/components/project-submissions/components/flag-form.js

Because:
* They needed some polish
This Commit:
* Adds a fixed width of 45% for extra large screens and responsive sizing to the react modals.
* Errors are now triggered on submit with the submission create and edit forms.
* Removes some un-needed reset logic in the create and edit forms.

Feature: Tweak Modal Styles

---

app/assets/stylesheets/components/project_submissions/submissions.scss
app/javascript/components/project-submissions/components/submission.js
app/services/notifications/flag_submission.rb
spec/services/notifications/flag_submission_spec.rb

This Commit:
* Bold the submission title.
* Use dynamic routes for the admin flag url that is sent to discord.

Chore: Polish Submissions Feature

---

app/assets/stylesheets/global.scss
app/javascript/components/project-submissions/components/create-form.js
app/javascript/components/project-submissions/components/edit-form.js
app/javascript/components/project-submissions/components/flag-form.js
app/javascript/components/project-submissions/components/modal.js
app/javascript/components/project-submissions/containers/project-submissions-container.js
app/javascript/components/project-submissions/index.jsx
app/views/lessons/show.html.erb
package.json
yarn.lock

This Commit:
* Autofocus on the first input in each modal.
* Do not allow the body to scroll when a modal is opened.
* Display the submissions list to signed out users.
* Display a prompt to sign in when signed out users try to flag a submission.

Chore: Project Submission Tweaks

---

app/javascript/components/project-submissions/components/submission.js
app/javascript/packs/application.js
package.json
yarn.lock

Because:
* It's unclear what this button is for.
This Commit:
* Adds hint.css to the project for tool tips.
* Adds a "Report Submission" tooltip to flag button.

Feature: Add Tool Tip to Flag Button

---

db/seeds/01_web_dev_101_seeds.rb

Because:
* This completes the roll out of the submissions feature :tada:

Feature: Roll Submissions Feature out to Web Dev 101

---

db/seeds/01_web_dev_101_seeds.rb

Feature: roll out to etch a sketch project

---

Procfile

Because:
* It can improve our memory usuage on production.

Chore: Try Jemalloc

---

db/seeds/01_web_dev_101_seeds.rb

Changed name of Project HTML/CSS to Google Homepage.

Changed name of Project HTML/CSS to Google Homepage.

---

app/controllers/paths_controller.rb

Alright, cleaned up that mess with the commits @KevinMulhern :)
I also leveraged your suggestion because I liked it better as well.

Filtering out Front End Only from paths index.

---

app.json

Because:
* It will allow us to test new PR's easier.
This commit:
* Adds the needed config it app.json

Chore: Set Up Heroku Review Apps

---

app/models/user.rb
db/seeds.rb
db/seeds/paths/front_end.rb
db/seeds/paths/full_stack_javascript.rb
db/seeds/paths/full_stack_rails.rb
db/seeds/paths/web_development_101.rb
spec/models/user_spec.rb

Because:
* This is the foundational path we expect all users to have completed before choosing a vocational path.
This commit:
* Adds a Web Development 101 Path.
* Sets the new users paths to the Web Development 101 path after they create an account.

Feature: Auto Enroll New Users in the Web Development 101 Path

---

app/assets/stylesheets/components/react_modal.scss

Added rounded corners to modal

---

db/seeds/01_foundations_seeds.rb
db/seeds/06_javascript_course_seeds.rb
db/seeds/paths/front_end.rb
db/seeds/paths/full_stack_javascript.rb
db/seeds/paths/full_stack_rails.rb

This commit:
* Changes the folder name to import foundation lessons from web development 101 to foundations.
* Fixes prerequisite creation failure due to unique validation, it will only create the prerequisite if it isn't already there now.
* Adds live preview to js restaurant project.

Chore: Various Seed Fixes

---

app/assets/stylesheets/components/form/form.scss

Reverts TheOdinProject/theodinproject#1450

Revert "Update form.scss"

---

app/views/shared/_navbar.html.erb
app/views/shared/_navbar_modal.html.erb
app/views/shared/_sidecar.html.erb

Might want to change the Community drop down to just a Discord link now that it's the only link in the drop down

Remove links to the Odin Project forum

---

app/models/user.rb

Now that web dev 101 has been renamed to foundations
This commit renames the after create callback and method in user to
enrol them into the foundations course

Rename enroll_in_web_dev_101 method to foundations

---

app/assets/stylesheets/utilities.scss
app/views/paths/show.html.erb
app/views/static_pages/contributing/_contributing_options.html.erb

Added an additional `push-down-2x` utility class and updated text sections referenced in issue below with said class.
Issue: #1441

added margin utility and updated views

---

Dockerfile
config/database.yml
config/webpacker.yml
docker-compose.yaml
entrypoint.sh

A follow-up pull request to https://github.com/TheOdinProject/theodinproject/pull/1250

Add docker compose

---

app/queries/lesson_project_submissions_query.rb
config/database.yml

This code:
- Adds an additional sort to the ProjectSubmission, enabling it to sort by most likes and then by most recent date.

Added additional sort to project submissions.

---

app/assets/stylesheets/components/form/form.scss
app/javascript/components/project-submissions/components/create-form.js
app/javascript/components/project-submissions/components/edit-form.js
app/javascript/components/project-submissions/components/flag-form.js

submissal modal responsive fix

submissal modal responsive fix

---

Gemfile.lock

Reverts TheOdinProject/theodinproject#1521

Revert "Chore(deps): Bump newrelic_rpm from 6.13.1 to 6.14.0"

---

app/javascript/components/project-submissions/components/__tests__/visible-toggle.test.js
package.json
setupTests.js
yarn.lock

Resolves #1511 
Not a fan of the third test since it didn't seem to be proper RTL, but I couldn't think of another way to test the actual toggle action.

Setup Jest/RTL and add test for visible-toggle

---

README.md

my very first Open Source Contribution

add Node and React to the list

---

db/seeds/paths/full_stack_rails.rb

Wording no longer made sense with the new curriculum structure.

Updated Ruby path description

---

app/javascript/components/project-submissions/components/__tests__/like.test.js
app/javascript/components/project-submissions/components/like.js

https://github.com/TheOdinProject/theodinproject/issues/1506
This commit:
- Adds unit tests for the like.js component
- Adds aria label to icon in component for accessibility purposes.

Add unit tests for like.js

---

package.json
yarn.lock

Reverts TheOdinProject/theodinproject#1545

Revert "Chore(deps): Bump @hookform/resolvers from 0.1.1 to 1.1.0"

---

app/assets/stylesheets/components/project_submissions/submissions.scss

Add max width to submission left container to prevent overflowing

---

config/initializers/rack_attack.rb
env.sample

Because
* We've been seeing a lot of spam requests lately.

Chore: Block Spam

---

app/assets/stylesheets/components/card.scss
app/assets/stylesheets/components/paths.scss
app/views/paths/index.html.erb
db/seeds/paths/foundations.rb

Alters the /paths layout as requested to emphasize the fact that FOUNDATIONS is the beginning, where everyone should start.
looks like this:

Edit all paths layout

---

app/javascript/components/project-submissions/components/__tests__/modal.test.js
app/javascript/components/project-submissions/components/modal.js

#1507 
This commit:
- Adds unit tests for the modal.js component
- Adds aria labels in component for accessibility purposes.

Add unit tests for modal.js

---

db/seeds/01_foundations_seeds.rb

Updated the names according to [this issue](https://github.com/TheOdinProject/theodinproject/issues/1560)

Fixed names of two introductory lessons

---

app/assets/stylesheets/components/project_submissions/submissions.scss

fix https://github.com/TheOdinProject/theodinproject/issues/1557

Fix position inconsistency issue with like button

---

app/javascript/components/project-submissions/components/submissions-list.jsx

There were some missing spaces, so for example, the text read:
Showing10 most recent submissions - View full list of solutions orView old submissions
If I'm not mistaken, my changes should address this.

Added missing spaces

---

app/assets/stylesheets/components/lesson/lesson_content.scss

rounded assignments box because it looks nicer.

rounded assignments box

---

app/assets/stylesheets/components/lesson/lesson_content.scss

rounded code blocks corners

---

app/helpers/lessons_helper.rb
app/javascript/components/project-submissions/components/submissions-list.jsx
app/javascript/components/project-submissions/index.jsx
app/views/lessons/show.html.erb
spec/helpers/lessons_helper_spec.rb

Because:
* Enough Submissions have been submitted with the new system now.

Feature: Remove Legacy Submissions Link

---

app/helpers/application_helper.rb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/static_pages/about.html.erb
app/views/user_mailer/welcome_email.html.erb
app/views/user_mailer/welcome_email.text.erb
doc/code_of_conduct.md
legal_terms_of_use.md

Because:
* The old address is defunct.

Feature: Update Contact Email Address

---

.circleci/config.yml
app/controllers/registrations_controller.rb
app/jobs/welcome_email_job.rb
app/models/user.rb
spec/jobs/welcome_email_job_spec.rb
spec/models/user_spec.rb

Because:
* Performance
This Commit:
* Adds a welcome email job
* Triggers the job on the registrations controller when the user finishes signing up.

Chore: Send Welcome Email in Background Job

---

.circleci/config.yml
Gemfile.lock
spec/factories/lessons.rb
spec/jobs/update_lesson_content_job_spec.rb
spec/vcr/update_lesson_content.yml

Because:
* This job was untested.
This commit:
* Adds a unit test to cover the update lesson content job.

Chore: Add Unit Tests for Update Lesson Content Job

---

app/assets/stylesheets/components/project_submissions/submissions.scss

before: ![chrome-capture (28)](https://user-images.githubusercontent.com/36450233/105661003-029fbc80-5ed5-11eb-9330-a5e8367459fe.jpg)
after:

Fix: submissions alignment on medium to large screens

---

app/javascript/components/project-submissions/components/__tests__/flag-form.test.jsx
app/javascript/components/project-submissions/components/flag-form.jsx

Resolves #1505 
This commit:
- Adds unit tests for the flag-form.js component

Tests: Add unit-tests for flag-form.js

---

app/views/shared/_logo.html.erb
app/views/static_pages/home/_success_stories.html.erb
app/views/static_pages/success_stories.html.erb
app/views/users/_profile_card.html.erb

Relates to: https://github.com/TheOdinProject/theodinproject/issues/1682

Alt text for images

---

README.md

Removed Sinatra from README

---

app/jobs/application_job.rb
app/notifications/flag_notification.rb
spec/notifications/flag_notification_spec.rb

Reverts TheOdinProject/theodinproject#1768

Revert "Revert "Create a FlagNotification class""

---

app/javascript/components/project-submissions/components/__tests__/edit-form.test.jsx

Add tests for edit-form component
https://github.com/TheOdinProject/theodinproject/issues/1504

Add tests for edit-form

---

Gemfile.lock

Reverts TheOdinProject/theodinproject#1807

Revert "Chore(deps-dev): Bump rubocop from 1.11.0 to 1.12.0"

---

README.md
app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb
spec/helpers/button_helper_spec.rb

Link to the issue: https://github.com/TheOdinProject/theodinproject/issues/1815
I believe it's all good now :)

Update Discord Link

---

app/javascript/components/project-submissions/components/__tests__/create-form.test.jsx
app/javascript/components/project-submissions/components/create-form.jsx

Resolves: https://github.com/TheOdinProject/theodinproject/issues/1503

Chore: Unit Tests for Project Submission Create Form

---

app/views/courses/show.html.erb

Because:
* This slipped through.

Chore: Remove Debugging

---

db/fixtures/lessons/ruby_lessons.rb
db/fixtures/paths/full_stack_rails/courses/1_ruby.rb

Adding the Nested Collection lessons to Ruby Basic lesson fixtures.

Add Ruby nested collections lesson to Basics

---

app/assets/stylesheets/components/navbar.scss
app/views/shared/_navbar.html.erb

Changes:
* Align Navbar's divider to the center 
* Refactor Navbar's position code
Before:
After:

Fix: Navbar alignment and position

---

config/routes/old_route_redirects.rb
spec/requests/old_course_route_redirects_spec.rb

Closes Issue #1820  
**What this code accomplishes:**
* Changes casing in the old redirects to find the desired target appropriately.
* Adds an additional redirect to catch an additional case.

Fixes old nodeJS redirects.

---

app/assets/stylesheets/components/form/form.scss
app/assets/stylesheets/components/project_submissions/submissions.scss

Fix: Support for *Safari
Replaces all `flexbox-gap` instances with `margin`.

Fix: support for ios

---

Gemfile
Gemfile.lock
app/models/user.rb
app/views/devise/registrations/_form.html.erb
app/views/lessons/_lesson_completion_state.html.erb
app/views/shared/_navbar.html.erb
app/views/static_pages/home.html.erb
app/views/users/show.html.erb
config/environments/test.rb
spec/rails_helper.rb
spec/support/better_rails_system_tests.rb
spec/support/capybara_setup.rb
spec/support/cuprite_setup.rb
spec/support/devise.rb
spec/system/lesson_completion.rb
spec/system/sign_up_spec.rb

Because:
* We should have end to end test coverage.
This commit:
* Sets up Rails systems tests using cuprite as the js driver.
* Adds a couple of tests for completing a lesson and signing up to verify the setup works as expected.

Chore: Setup System Tests

---

app/views/paths/index.html.erb
app/views/paths/show.html.erb
app/views/shared/_flash_helper.html.erb
spec/system/switching_path_spec.rb

Because
- Switching paths needs end to end test coverage.
This commit:
- Tests switching paths from the paths index page.
- Tests switching paths from the path show page.
- Resolves #1863

Add system tests for switching paths

---

app/models/lesson.rb
app/models/lesson_completion.rb
app/models/user.rb
db/migrate/20210505042630_rename_lesson_completions_student_id_to_user_id.rb
db/schema.rb
spec/controllers/lesson_completions_controller_spec.rb
spec/factories/lesson_completions.rb
spec/helpers/lessons_helper_spec.rb
spec/models/lesson_completion_spec.rb
spec/models/user_spec.rb

This addresses issue https://github.com/TheOdinProject/theodinproject/issues/1883. Not quite sure on the proper etiquette regarding assignment of the issue. I acknowledge this was already assigned, but I had the night free and I thought it might be okay since this is a "chore" and it had been a week since it was assigned. 
Summary:
I generated the migration to rename the column and then ran the specs and addressed each failure by section, renaming where necessary. I also updated the file `spec/factories/lesson_completion.rb` to be associated with a user instead of a student.

Rename student_id to user_id. Update relevant models, specs, etc.

---

app/assets/stylesheets/settings.scss
app/helpers/projects_helper.rb

Because:
* It is not being used anywhere.

Chore: Remove Project Helpers File

---

app/controllers/project_submissions/flags_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/models/lesson.rb
app/models/omniauth_providers/finder.rb
config/initializers/omniauth.rb
config/initializers/rack_attack.rb
spec/support/oauth.rb

Because:
* Analysing the simplecov code coverage report revealed some unused code in the app.
This commit:
* Remove unused type method on lesson model.
* Remove unused forum_link method from the application helper.
* Stop sending failed sign in/up events with oauth to NewRelic as we use Sentry for error tracking now.
* Remove unused project_submission method from flags controller.
* Remove unused courses method from the users controller.
* Prevent oauth failed events from logging to stdout.
* Remove unused Rack Attack rule.

Chore: Remove Unused Code

---

app/views/paths/index.html.erb

Changed the title on the Paths index to "All Paths"  issue #1918

changed title on paths index to 'All Paths'

---

app/views/admin/flags/_flag_actions.html.erb
app/views/devise/sessions/_form.html.erb
config/initializers/rack_attack.rb
spec/system/admin/flags_spec.rb

Because:
* This feature should have end to end test coverage.
This commit:
* System test for dismissing flags
* System test for removing flags
* System test for banning user
* Only rate limit when posting flags
Resolves: https://github.com/TheOdinProject/theodinproject/issues/1914

Chore: System Tests for Admin Flows

---

db/fixtures/paths/foundations/seed.rb

fix typo in conclusion lesson description

---

app/views/devise/registrations/_learning_goal.html.erb
app/views/devise/registrations/_profile.html.erb
app/views/devise/registrations/edit.html.erb
spec/system/user_account_spec.rb

Because:
- User account changes should have end to end test flow
This commit:
- tests for updating user personal details
- tests for updating user learning goals
- tests for deleting user accounts
Resolves: #1893

Chore: Add system tests for editing and deleting user accounts

---

app/views/users/_skill.html.erb
spec/system/user_dashboard/open_course_spec.rb
spec/system/user_dashboard/resume_course_spec.rb
spec/system/user_dashboard/start_course_spec.rb

Because:
* The user dashboard should have end to end test coverage.
This Commit:
* System test for dashboard starting new course
* System test for dashboard resuming course
* System test for dashboard opening completed course
Resolves #1900

Chore: System Tests for User Dashboard

---

db/fixtures/lessons/ruby_lessons.rb
db/fixtures/paths/full_stack_rails/courses/1_ruby.rb

* This project needed to be added to the database.
* Adds this project to the end of the Advanced Ruby section.

Lesson: Add Custom Enumerable Project to Ruby

---

app/javascript/layouts/application.css
app/javascript/packs/application.js
package.json
postcss.config.js
tailwind.config.js
yarn.lock

* We have decided to go with Tailwind for our CSS instead of continuing to use BEM.
* Adds the Tailwind package.
* Adds some config for Tailwind.
* Comments out the Tailwind base style sheet (basically a normalize file) for now as it changes our heading sizes.
* Don't use Tailwinds container plugin as it changes the container sizes we use - we can use it after getting rid of bootstrap.

Chore: Add Tailwind to the App

---

Gemfile
Gemfile.lock
app/admin/flags.rb
app/services/admin/flags/ban_user.rb
app/services/admin/flags/dismiss.rb
app/services/admin/flags/remove_submission.rb
spec/services/admin/flags/ban_user_spec.rb
spec/services/admin/flags/dismiss_spec.rb
spec/services/admin/flags/remove_submission_spec.rb

Because
* It was incomplete
This commit:
* Change ruby version in Gemfile so we can deploy.
* Fix depreciation warnings with kwargs.

Chore: Complete Ruby 2.7.1 Upgrade

---

package.json
yarn.lock

Reverts TheOdinProject/theodinproject#2011

Revert "Upgrade: Bump postcss from 7.0.35 to 8.3.0"

---

db/fixtures/paths/full_stack_javascript/courses/2_html_and_css.rb
db/fixtures/paths/full_stack_rails/courses/4_html_and_css.rb

A significant amount of students ask if they should take HTML/CSS prior to the actual programming courses
- updates description to clarify that the programming courses should be done first

Updates HTML/CSS course description 

---

app/javascript/components/project-submissions/components/__tests__/submissions-list.test.jsx

`submissions-list.jsx` did not have unit tests written.
Close #1510 
* provides unit tests for `submissions-list.jsx`

Add unit testing for submissions-list.jsx

---

app/javascript/src/js/analytics.js
app/views/lessons/_advert.html.erb

Because:
* We were not tracking some ga events.

Chore: Fix GA Tracking

---

Gemfile
Gemfile.lock

Because:
* Bundler will not work with the previous bump, it says the version has been removed.

Chore: Bump Active Admin Addons

---

app/controllers/application_controller.rb

https://github.com/TheOdinProject/theodinproject/issues/1954
Made browser redirect to lesson or specific page the user was on in case they go to sign in from that specific page.

Feature: Redirect Back to Lesson Page After Logging In

---

.ruby-gemset

Because:
* It is not being used.

Chore: Remove Gemset File

---

db/fixtures/lessons/foundation_lessons.rb
db/fixtures/paths/foundations/seed.rb

A lesson needed to be added.
- adds the Asking For Help lesson to Foundations

Add asking for help lesson

---

db/fixtures/lessons/foundation_lessons.rb
db/fixtures/paths/foundations/seed.rb

**NOTE** this PR should only be merged along with https://github.com/TheOdinProject/curriculum/pull/22439
The practicing git basics project has been moved into the git basics lesson
Removes the practicing git basics project.

Remove project: practicing git basics

---

db/seeds/maintainer_users.rb

Because:
* This list will automatically create an account for the review app.

Chore: Add rachel to Maintainer Users Seeds List

---

db/seeds/maintainer_users.rb

Kevin told me to
adds my name to the maintainers seeds file

Add name to maintainer seeds

---

db/seeds/maintainer_users.rb

My name wasn't in the maintainer user seeds.
Adds my name to the maintainer user seeds.

Add "sully" to maintainer user seeds

---

app/controllers/lessons/project_submissions_controller.rb
app/views/lessons/show.html.erb
spec/system/all_lesson_project_submissions_spec.rb
spec/system/lesson_project_submissions/add_submission_spec.rb
spec/system/user_project_submissions/edit_submission_spec.rb

Because:
* Some submissions have been targeted with spam.
This commit:
* If a user is not signed in they will not be able to view any submissions.

Feature: Hide Submissions for Guest Users

---

doc/code_of_conduct.md

- [N/A] You have verified the tests and linters all pass against your changes?
- [N/A] You have included automated tests for your changes where applicable?

Fix punctuation error in Code of Conduct

---

db/fixtures/lessons/foundation_lessons.rb

Chore: Allow Submissions on New HTML & CSS Projects

---

db/fixtures/paths/full_stack_rails/courses/5_javascript.rb

The Ruby version of the JS course was out of order.
Closes #2247
Reorders the course.

Fix order of testing and React sections

---

db/fixtures/paths/full_stack_rails/courses/5_javascript.rb

This reverts commit 28ecad59aaf264e7cd8e9e5e9620218031db2224.
tests failed on main.

Revert "Fix order of testing and React sections"

---

.circleci/config.yml

Chore: Bump Ruby Version on Circle

---

app/javascript/components/project-submissions/components/__tests__/submission.test.jsx
app/javascript/components/project-submissions/components/edit-form.jsx

Hey,
I finally finished writing the tests and would like your feedback.
There is only one problem is with the test on line up 76 which doesn't work and I don't quite know why. 
Any help would there would be appreciated.
Related to: #1509

Testing Submission Component

---

db/fixtures/lessons/node_js_lessons.rb

fixes path, it's case sensitive. 
updates path name

Fix mongodb course path

---

db/fixtures/paths/full_stack_javascript/courses/3_node_js.rb

Adds debugging node lesson to section.

Add node debugging lesson to section

---

package.json
yarn.lock

Reverts TheOdinProject/theodinproject#2280

Revert "Upgrade: Bump hint.css from 2.6.0 to 2.7.0"

---

yarn.lock

Chore: Add Uncommitted Yarn.lock Changes

---

db/fixtures/paths/full_stack_rails/courses/5_javascript.rb

- Same section desc was updated in NodeJs path recently
- Current desc is not descriptive enough
- Will update section desc to match the one in NodeJs path

Update 'Asynchronous JavaScript and APIs' section desc in Ruby path

---

db/fixtures/lessons/javascript_lessons.rb

Because:
* There is no live preview to show for this project.

Chore: Remove Live Preview From JS Testing Lesson

---

app/assets/stylesheets/components/lesson/lesson_content.scss

closes #2360
- This commit updates the knowledge check link CSS by basing it on [href]:not([class]) from the global class.

updated knowledge check css

---

app/views/errors/not_found.erb

It might be nice to help students learn what 404 actually means (and 500, etc.)
adds a link to a wikipedia page about http status codes

Update not_found.erb to include a link to learn about http status codes

---

app/helpers/application_helper.rb

FAQ Question: "What is the goal of ~**the**~ The Odin Project"
Remove extra the

Remove additional "the" from FAQ question

---

db/seeds/success_stories.rb

Chore: Remove Success Story Link

---

app/assets/stylesheets/components/lesson/lesson_preview.scss
app/views/lessons/previews/show.html.erb

This pull request will update the [lesson preview](https://www.theodinproject.com/lessons/preview) page of the website
- Add webpage title
- Add heading and one line detail
After changes:

Update lesson preview page

---

Gemfile.lock
db/fixtures/lessons/foundation_lessons.rb
db/fixtures/paths/foundations/seed.rb

This commit is the second task of [#23248](https://github.com/TheOdinProject/curriculum/issues/23248) on the curriculum repo. The 'Installing Node.js' lesson has been added to the curriculum repo and this PR adds the lesson to the TOP site.
- Adds the Installing Node.js lesson to db/fixtures/lessons/foundation_lessons.rb
- Adds the Installing Node.js lesson to db/fixtures/paths/foundations/seed.rb
If this PR is approved I will then update the JavaScript Exercises [README](https://github.com/TheOdinProject/javascript-exercises/blob/main/README.md) to reflect the change.

Foundations - JavaScript Basics - Add 'Installing Node.js' lesson 

---

app/assets/stylesheets/components/lesson/lesson_content.scss

- Ordered lists are currently displayed as unordered lists
- Set ordered list items type to `decimal`

Fix: Ordered list style for lesson content

---

db/fixtures/paths/full_stack_javascript/courses/intermediate_html_css.rb
db/fixtures/paths/full_stack_rails/courses/intermediate_html_css.rb

Update section descriptions in Intermediate HTML/CSS course

---

db/fixtures/lessons/javascript_lessons.rb
db/fixtures/paths/full_stack_javascript/courses/javascript.rb
db/fixtures/paths/full_stack_rails/courses/javascript.rb

Relevant PR: https://github.com/TheOdinProject/curriculum/pull/23387
- Improve the lesson title of the [form lesson in the JavaScript course](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/forms) to align with the content of the lesson

Rename forms lesson in the JavaScript course

---

app/views/shared/_footer.html.erb

- typo
- eduction => education

Fix typo in footer

---

db/fixtures/lessons/foundation_lessons.rb
db/fixtures/lessons/ruby_lessons.rb
db/fixtures/lessons/ruby_on_rails_lessons.rb

closes #2581
- Sets the installation_lesson property of the installation lessons to true.

Set the installation_lesson property of installation lessons to true

---

app/views/lessons/installation_lessons/index.html.erb

This Solves issue [#2582](https://github.com/TheOdinProject/theodinproject/issues/2582)
1.  Added styles to various tags.
2. Made it look as identical as the result picture given in the issue.
This is my first time contibuting here so i do not know where to add tests. If i have to include one please let me know

Upgrade patch which solves issue #2582

---

app/views/shared/_footer.html.erb

closes #2583
Add a link to appendix in the _footer.html.erb

Add appendix link to footer partial

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

Related to https://github.com/TheOdinProject/curriculum/pull/23587
I updated the PR and Issue templates to be more consistent across our repos.
I also updated the README file to make it more focused on this repo's focus, while still linking to the curriculum repo.

README and Templates: Update files based on new guides/templates

---

CONTRIBUTING.md

Fix: three simple spelling mistakes

---

CONTRIBUTING.md

Chore: Add instructions for Odinbot repo to Contributing Guide

---

app/javascript/src/js/lessons.js

Feature: Add Practice to lesson headings

---

db/fixtures/lessons/javascript_lessons.rb
db/fixtures/lessons/ruby_lessons.rb
db/fixtures/paths/full_stack_javascript/courses/javascript.rb
db/fixtures/paths/full_stack_rails/courses/ruby.rb

Move A Deeper Look at Git lesson in Ruby and Javascript courses

---

app/controllers/static_pages_controller.rb
app/helpers/application_helper.rb
app/views/static_pages/home/_success_stories.html.erb
spec/helpers/application_helper_spec.rb

Chore: Move Home Page Success Stories Query into Controller

---

app/views/shared/_off_canvas_menu.html.erb

Feature: Add Notifications to Mobile Nav Menu

---

Gemfile
Gemfile.lock

Chore: Add Rack Mini Profiler Gem

---

db/fixtures/lessons/ruby_on_rails_lessons.rb
db/fixtures/paths/full_stack_rails/courses/rails.rb

We want to update our Rails lessons to be on the latest version (7)
This commit:
- Add Rails 7 lesson fixtures
- Add Rails 7 lessons to seed file
-   [ ] I have verified …

Add Rails 7 seed files

---

app/assets/stylesheets/dark-mode.css
app/javascript/components/project-submissions/components/create-form.jsx
app/javascript/components/project-submissions/components/edit-form.jsx
app/javascript/components/project-submissions/components/flag-form.jsx
app/javascript/components/project-submissions/components/modal.jsx

Fix: Dark Mode on Project Submission Forms

---

Gemfile

Moved dotenv file to development and test.

---

app/helpers/application_helper.rb
app/views/shared/_footer.html.erb
config/initializers/odin_configuration.rb

<hr>
Because:
* Our blog posts are now …

Feature: Change Blog Link to Dev.to

---

app/helpers/application_helper.rb
app/helpers/button_helper.rb
app/javascript/src/js/analytics.js
app/views/shared/_footer_cta.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_off_canvas_menu.html.erb
app/views/shared/_sidecar.html.erb
app/views/static_pages/about.html.erb
config/initializers/odin_configuration.rb
spec/helpers/application_helper_spec.rb

<hr>
Because:
* We are now storing side …

Chore: Move Odin Chat URL to Configuration

---

db/fixtures/lessons/html_and_css_lessons.rb

Fix broken improve on github urls - Grid

---

app/javascript/src/js/lessons.js

Fix: Heading rendering in Chromium

---

db/fixtures/lessons/html_and_css_lessons.rb
db/fixtures/paths/full_stack_javascript/courses/intermediate_html_css.rb
db/fixtures/paths/full_stack_rails/courses/intermediate_html_css.rb

Fix - Update Grid Conclusion lesson title

---

app/assets/stylesheets/dark-mode.css

Feature: Make the text a bit lighter

---

app/assets/stylesheets/_bootstrap-custom.scss
app/assets/stylesheets/application_stylesheet.scss

<hr>
Because:
* They are interfering with …

Chore: Disable Bootstrap Utility Classes

---

db/fixtures/lessons/foundation_lessons.rb
db/fixtures/lessons/git_lessons.rb
db/fixtures/lessons/javascript_lessons.rb
db/fixtures/lessons/ruby_lessons.rb
db/fixtures/paths/foundations/seed.rb
db/fixtures/paths/full_stack_javascript/courses/javascript.rb
db/fixtures/paths/full_stack_rails/courses/ruby.rb
db/seeds.rb

Add Using Git in the Real World to the JS course

---

app/javascript/src/js/lessons.js

Feature: add "Lesson Overview" to lesson headings

---

app/assets/stylesheets/components/lesson/lesson_content.scss

Fix: set lesson h3 headings width to fit-content

---

app/views/static_pages/about.html.erb

Fix: typos on About page

---

app/views/notifications/index.html.erb

<hr>
Because:
* To ensure it's consistent …

Feature: Add Page Heading and Title to Notifications

---

app/assets/stylesheets/components/internal_link.scss

fixed hover effect visual on site

---

app/javascript/layouts/application.css
app/javascript/layouts/layout.css
app/views/courses/show.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/lessons/project_submissions/index.html.erb
app/views/lessons/show.html.erb
app/views/notifications/index.html.erb
app/views/paths/index.html.erb
app/views/paths/show.html.erb
app/views/shared/_navbar.html.erb
app/views/static_pages/about.html.erb
app/views/static_pages/contributing.html.erb
app/views/static_pages/faq.html.erb
app/views/static_pages/home.html.erb
app/views/static_pages/style_guide.html.erb
app/views/static_pages/success_stories.html.erb
app/views/static_pages/terms_of_use.html.erb
app/views/users/show.html.erb

<hr>
Because:
* We previously included a …

Fix: Nav Bar Margin in Darkmode

---

app/views/static_pages/dashboard_steps/community_rules.md

-   [X] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable
<hr>
**1. Because:** this page lists …

Fix - Community Rules - Update crosspost wording

---

app/assets/stylesheets/dark-mode.css

<hr>
Because:
* The progress badge text …

Fix: Progress Badge Text in Darkmode

---

app/javascript/layouts/typography.css
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/lessons/previews/show.html.erb
app/views/notifications/index.html.erb
app/views/paths/index.html.erb
app/views/paths/show.html.erb
app/views/static_pages/about.html.erb
app/views/static_pages/contributing.html.erb
app/views/static_pages/faq.html.erb
app/views/static_pages/style_guide.html.erb
app/views/static_pages/success_stories.html.erb
app/views/users/show.html.erb

Because:
* Ada's new page designs include this style of heading
-   [x] I have verified all tests and linters pass against my changes, and/or I have included automated …

Feature: New Page Heading Styling

---

app/views/lessons/installation_lessons/index.html.erb

<hr>
Because:
* The title did not have …

Fix: Appendix Page Title Spacing

---

app/views/static_pages/terms_of_use.html.erb
legal_terms_of_use.md

<hr>
Because:
* It was hard to read.
This …

Fix: Terms of use page styling

---

CONTRIBUTING.md

Chore: Add test commands for website instructions

---

app/assets/stylesheets/dark-mode.css

Feature: Use the same color for the box shadow in dark mode as is used in light mode

---

app/views/shared/_footer_cta.html.erb

<hr>
Because:
* The new design does not have …

Feature: Remove Footer CTA Border

---

app/views/shared/_navbar.html.erb

<hr>
Because:
* The logo was touching the …

Chore: Add Bottom Padding To Nav Container

---

.rubocop_todo.yml
spec/helpers/application_helper_spec.rb
spec/jobs/discard_project_submission_job_spec.rb
spec/models/lesson_spec.rb
spec/system/lesson_navigation_spec.rb
spec/system/lesson_project_submissions/add_submission_spec.rb
spec/system/select_path_spec.rb
spec/system/user_account_spec.rb
spec/system/user_login_spec.rb

<hr>
Because:
* It removes these linting …

Chore: Resolve RSpec/ContextWording Linting Offences

---

.rubocop_todo.yml
spec/controllers/api/lesson_completions_controller_spec.rb
spec/helpers/application_helper_spec.rb
spec/mailers/user_mailer_spec.rb
spec/models/lesson_spec.rb
spec/queries/lesson_project_submissions_query_spec.rb
spec/services/discord_notifier_spec.rb
spec/services/find_lesson_spec.rb
spec/services/next_lesson_spec.rb

<hr>
Because:
* It removes these linting …

Chore: Resolve RSpec/BeEql and RSpec/BeEq RSpec Rubocop Offences

---

.rubocop_todo.yml
spec/helpers/application_helper_spec.rb
spec/models/user_spec.rb
spec/system/all_lesson_project_submissions_spec.rb
spec/tasks/curriculum_spec.rb
spec/tasks/project_submissions_spec.rb

<hr>
Because:
* It removes these linting …

Chore: Resolve BeNil, BeforeAfterAll and VisibilityMatcher RSpec Rubocop Offences

---

.rubocop_todo.yml
spec/.rubocop.yml
spec/decorators/course_decorator_spec.rb
spec/decorators/lesson_decorator_spec.rb
spec/decorators/section_decorator_spec.rb
spec/factories_spec.rb
spec/mailers/user_mailer_spec.rb
spec/models/admin_flash_spec.rb
spec/models/lesson_completion_spec.rb
spec/models/omniauth_providers/builder_spec.rb
spec/models/omniauth_providers/finder_spec.rb
spec/models/path_spec.rb
spec/models/point_spec.rb
spec/models/project_submission_spec.rb
spec/models/user_provider_spec.rb
spec/services/course_progress_spec.rb
spec/services/find_lesson_spec.rb
spec/services/lesson_content_importer_spec.rb
spec/services/mailchimp_subscription_spec.rb
spec/services/markdown_converter_spec.rb
spec/services/next_lesson_spec.rb

<hr>
Because:
* It removes these linting …

Chore: Fix RSpec Describe Offences

---

.rubocop_todo.yml
spec/models/flag_spec.rb
spec/notifications/flag_notification_spec.rb
spec/services/users/reset_progress_spec.rb

<hr>
Because:
* It removes these offences …

Chore: Fix Empty Line Offences

---

app/components/card_component.html.erb
app/components/card_component.rb
spec/components/card_component_spec.rb

Because:
A Card Component may sometimes need data attributes set
This commit:
* Add a data attributes hash argument to the CardComponent initiazer
* Add a data_attributes reader method that parses the data_attributes hash
be html5 valid syntax
* Add test coverage
Complete the following checkbox ONLY …

Add data attributes options to CardComponent

---

app/components/progress_badge_component.html.erb

<hr>
This commit:
* The progress badge was …

Fix: Progress Badge Background in Darkmode

---

db/fixtures/lessons/html_and_css_lessons.rb

Chore: update lesson URLs for Advanced HTML/CSS course

---

.rubocop_todo.yml
spec/models/flag_spec.rb
spec/models/project_submission_spec.rb
spec/requests/static_pages_spec.rb
spec/system/lesson_project_submissions/edit_submission_spec.rb
spec/system/user_project_submissions/edit_submission_spec.rb

<hr>
Because:
* It removes these offences …

Chore: Fix More RSpec Rubocop Offences

---

app/assets/stylesheets/components/home/curriculum_details.scss
app/views/static_pages/home/_curriculum.html.erb

Because:
* The badges were not aligned centre and longer titles were overflowing on mobile.
This commit:
* Align the course badges centre.
* Remove the explicit height from the course badge tile container.
Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later …

Fix: Homepage Course Badges on Mobile

---

app/views/users/show.html.erb

<hr>
Because:
* It looks cleaner and reads …

Feature: Change Dashboard Page Title to Just "Dashboard"

---

.rubocop_todo.yml
spec/.rubocop.yml
spec/controllers/registrations_controller_spec.rb
spec/helpers/application_helper_spec.rb
spec/helpers/paths_helper_spec.rb
spec/jobs/mailing_list_job_spec.rb
spec/jobs/update_lesson_content_job_spec.rb
spec/models/lesson_completion_spec.rb
spec/models/path_spec.rb
spec/models/project_submission_spec.rb
spec/models/user_spec.rb
spec/services/users/reset_progress_spec.rb
spec/system/lesson_project_submissions/voting_spec.rb
spec/system/user_dashboard/start_course_spec.rb
spec/system/user_reset_progress_spec.rb

<hr>
Because:
* It removes this offence from …

Chore: Fix RSpec/LetSetup Offences

---

app/views/static_pages/success_stories.html.erb

<hr>
Because:
* It was not centered on …

Fix: Success Stories Image on Mobile

---

.rubocop_todo.yml
spec/controllers/registrations_controller_spec.rb
spec/models/lesson_spec.rb
spec/services/lesson_content_importer_spec.rb
spec/services/mailchimp_subscription_spec.rb

<hr>
Because:
* It removes these offences …

Chore: Resolve More Rubocop RSpec Offences

---

app/components/faq_item_component.html.erb

<hr>
Because:
* It needed an svg extension.

Fix: Chevron SVG Cannot be Found

---

app/assets/stylesheets/components/lesson/lesson_content.scss

<hr>
Because:
* There was too much spacing …

Fix: Nested Unordered List Spacing in Assignment Panel

---

app/mailers/user_mailer.rb
config/initializers/devise.rb
spec/mailers/user_mailer_spec.rb

<hr>
Because:
* Send grid now requires a …

Fix: Emails being Sent Via Sendgrid

---

app/mailers/user_mailer.rb
config/initializers/devise.rb

<hr>
Because:
* It allows users to know …

Chore: Add Friendly From Name to Emails

---

app/assets/stylesheets/dark-mode.css
app/views/static_pages/home.html.erb
app/views/static_pages/home/_success_stories.html.erb

<hr>
Because:
* We have a couple of links on …

Fix: Hard to See Links on Dark Mode

---

.circleci/config.yml

Because:
* The staging deploy test succeeded.
-   [x] I have verified all tests and linters pass against my changes, and/or I have included automated tests where …

Chore: Switch CI Deploy to Production

---

app/views/static_pages/dashboard_steps/community_rules.md

Feature: Add details to crossposting rule

---

app/controllers/lessons/installation_lessons_controller.rb

-   [X] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable
<hr>
Closes #2903
**2. This …

Feature: Add sort function to installation lessons appendix

---

app/views/static_pages/dashboard_steps/community_rules.md

Fix: Update mini-modding in community rules

---

app/views/static_pages/faq.html.erb

Fixed grammar

---

db/fixtures/paths/full_stack_rails/courses/ruby.rb

-   [X] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable
<hr>
Makes the description …

Fix: Typo in ruby testing section's description

---

app/assets/stylesheets/global.scss
app/assets/stylesheets/typography.scss
app/components/faq_item_component.html.erb
app/components/faq_item_component.rb
app/javascript/layouts/typography.css
app/views/static_pages/faq.html.erb
config/locales/en.yml

Because:
* It gives reduces the duplication on the faq view.
This commit:
* Move all faq questions and answers to the en locale file.
* Allow faq item component to accept an item hash.
* Change global p tag styling to bring it in line with our newer Tailwind styles.
Complete the following checkbox …

Chore: Move Faq Items to Locale

---

.circleci/config.yml

Because:
* Heroku's Github integration is working again.
-   [x] I have verified all tests and linters pass against my changes, and/or I have included automated tests …

Chore: Stop Deploying with Circle CI

---

.rubocop_todo.yml
app/services/markdown_converter.rb
spec/helpers/application_helper_spec.rb
spec/models/omniauth_providers/builder_spec.rb
spec/models/omniauth_providers/finder_spec.rb
spec/models/user_provider_spec.rb
spec/serializers/course_serializer_spec.rb
spec/serializers/lesson_serializer_spec.rb
spec/serializers/section_serializer_spec.rb
spec/services/course_progress_spec.rb
spec/services/discord_notifier_spec.rb
spec/services/markdown_converter_spec.rb

Because:
* They were in the rubocop todo file.
This commit:
* Fixes all RSpec/VerifiedDoubles cop violations.
-   [x] I have verified all tests and linters pass against my …

Chore: Fix RSpec/VerifiedDoubles Cops

---

.rubocop_todo.yml
spec/helpers/application_helper_spec.rb
spec/models/omniauth_providers/finder_spec.rb
spec/models/project_submission_spec.rb
spec/models/user_provider_spec.rb
spec/models/user_spec.rb
spec/services/course_progress_spec.rb
spec/services/lesson_content_importer_spec.rb

Because:
* It removes them from the rubocop_todo file.
This commit:
* Fix RSpec/NotToNot violations
* Fix RSpec/NestedGroups violations
* Fix RSpec/NamedSubject violations
* Remove Layout/LineLength from todo file - there was nothing to fix for this one.
Complete the following checkbox ONLY IF it is …

Chore: Fix More Rubocop RSpec Violations

---

bin/test

**Because:**
* It's a nice QOL improvement
This script was a recent addition as a convenience for running all tests / linters in a single command. This addition is a small QOL change to give a summary at the end. Partly intended to improve experience for beginner / newer contributors
**Example Output**

Chore: Add test summary to end of bin/script

---

.rubocop.yml
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

Because:
* Of an ongoing effort to update Rails config files to match what comes in the more recent versions of Rails
This commit:
* Update development environment file to match latest Rails config.
* Update production environment file to match latest Rails config.
* Update test environment file to match latest Rails config.
- `Chore` - changes that have no user-facing value, refactors, dependency …

Chore: Update Environment Files

---

db/fixtures/lessons/foundation_lessons.rb
db/fixtures/paths/foundations/seed.rb

Feature: add computer basics lesson and other changes

---

app/assets/stylesheets/components/lesson/lesson_content.scss

Feature: Add lesson-note class in lesson content

---

app/assets/stylesheets/dark-mode.css

Feature: updated color values for text color and background color in dark-mode

---

app/assets/stylesheets/global.scss

Fix: now adds dark mode bg color to input if in dark mode

---

app/assets/stylesheets/dark-mode.css
app/components/paths/select_button_component.html.erb
app/components/paths/select_button_component.rb
app/components/paths/view_button_component.html.erb
app/components/paths/view_button_component.rb
app/controllers/paths_controller.rb
app/models/path.rb
app/models/user.rb
app/views/paths/index.html.erb
db/fixtures/paths/foundations/seed.rb
db/fixtures/paths/full_stack_javascript/seed.rb
db/fixtures/paths/full_stack_rails/seed.rb
db/migrate/20220702170539_add_badge_uri_to_paths.rb
db/schema.rb
lib/seeds/path_seeder.rb
spec/components/paths/select_button_component_spec.rb
spec/components/paths/view_button_component_spec.rb
spec/factories/paths.rb
spec/models/path_spec.rb
spec/models/user_spec.rb
spec/system/lesson_navigation_spec.rb
spec/system/select_path_spec.rb

Because:
* Ada has redesigned the All Paths page.
This commit:
* Refactor path index view to follow the new design
* Separate default and full-stack paths at the controller level to avoid too much logic in views
* Add Explore button to path cards which learners can use to view paths without selecting
* Add path select button component for containing select path logic
* Add badge_uri to paths table
- …

Feature: Redesign All Paths Page

---

app/components/progress_badge_component.html.erb
app/javascript/components/project-submissions/components/__tests__/like.test.jsx
app/javascript/components/project-submissions/components/like.jsx
app/javascript/components/project-submissions/components/modal.jsx
app/javascript/components/project-submissions/components/toggle.jsx
app/javascript/layouts/buttons.css
app/views/courses/_course.html.erb
app/views/paths/show.html.erb
tailwind.config.js

Because:
* We primarly use this color for call to action buttons and the contast was not great.
This commit:
* Increase the darkness of the the base shade for our teal color.
Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently …

Feature: Increase Darkness of Base Teal Shade

---

app/views/shared/_footer.html.erb

Because:
* If someone wants to know who designed the site, they can find out in the footer.
* Recognition for all the work Ada has done. …

Feature: Add Footer Link to Ada's Site

---

app/javascript/controllers/clickable_images_controller.js
app/javascript/src/js/lessons.js
app/views/lessons/show.html.erb

Because:
* We should extract and modularize the different behaviours we apply to lesson content in the lessons.js script.
* Refactoring as part of our ongoing effort to move all our styles to Tailwind.
Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if …

Chore: Extract Lesson Content Clickable Images JS to Stimulus Controller

---

db/fixtures/paths/full_stack_rails/courses/ruby.rb

Fix: correct typo in Conclusion description

---

app/views/shared/_footer.html.erb

Remove Ada's Website Link from Footer

---

app/assets/stylesheets/dark-mode.css
app/javascript/stylesheets/forms.css

-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
<hr>
Closes #3138 
**2. …

updated forms css file, changed text color to dark gray

---

app/views/static_pages/dashboard_steps/how_to_ask.md

Fix: Update odin-bot prefix

---

app/views/static_pages/how_to_ask.html.erb

 Fix: Content Styling on How to Ask

---

app/javascript/controllers/lesson_toc_controller.js

Because:
* Only the id should be lowercased before it is converted to kebab case. The displayed heading should maintain any capital letters.
-   [x] I have verified all …

Fix: TOC Items Displaying in Lowercase

---

db/fixtures/lessons/html_and_css_lessons.rb

Chore: Update Intermediate HTML/CSS course lesson seeds

---

app/views/static_pages/home.html.erb
app/views/static_pages/home/_curriculum.html.erb
app/views/static_pages/home/_how_it_works.html.erb
app/views/static_pages/home/_success_stories.html.erb
tailwind.config.js

<hr>
Closes https://github.com/TheOdinProject/top-meta/issues/212
**2. This PR:**
Refactor css of the home / landing page to use tailwind classes.
There are a few classes I could not remove entirely …

Chore: Tailwind homepage refactor

---

.gitignore
app/views/static_pages/success_stories.html.erb

<hr>
Closes https://github.com/TheOdinProject/top-meta/issues/187
**2. …

Chore: refactor success stories page tailwind

---

app/views/user_mailer/welcome_email.html.erb
app/views/user_mailer/welcome_email.text.erb

Because:
* This is from a time when profiles could be shared and visited.
-   [x] I have verified all tests and linters pass against my changes, and/or I have included …

Feature: Remove profile link from welcome email

---

app/helpers/application_helper.rb
app/views/static_pages/home/_how_it_works.html.erb
config/locales/en.yml

Because:
* A locale file is a better home for this content.
This commit:
* Moves how it works hash from application controller, converts to yaml, and moves it to the en locale file.

Chore: Move Home Page How it Works Items to Locale File

---

app/views/static_pages/terms_of_use.html.erb

Fix: Replacing "Contact Us" with an email

---

app/views/static_pages/dashboard_steps/_github_link.html.erb

-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x ] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
<hr>
Closes #XXXXX
**2. …

Fix - Resolves #3171 Changed /blob/ to /edit/

---

package.json
yarn.lock

Chore: Remove Validate.js

---

app/views/users/show.html.erb

Because:
* It was aligned left

Fix: Dashboard Alignment

---

app/views/static_pages/home/_curriculum.html.erb

**Because:**
* It's very bright and it burns my eyes
* Replaces colour class with appropriate dark mode utility
**Notes:**
* Won't matter soon with proper native darkmode on the way, but an easy fix in the meantime
Before: 
After:

Fix: White background in dark mode on homepage

---

.babelrc

feat: add diff to PrismJS

---

db/fixtures/lessons/ruby_on_rails_lessons.rb
db/fixtures/paths/full_stack_rails/courses/rails.rb

feat: add installing psql lesson to Rails course

---

app/controllers/paths_controller.rb

Dependabot bumped a new `rubocop-rails` version but it is failing due [this error](https://app.circleci.com/pipelines/github/TheOdinProject/theodinproject/4565/workflows/914d8d1a-5fa3-4a32-8f01-995607689311/jobs/12687)
```
app/controllers/paths_controller.rb:10:3:
C: [Correctable] Rails/ActionOrder: Action index should appear before show.
```
Related https://github.com/TheOdinProject/theodinproject/pull/3459
- `Chore` - changes that have no …

Fix: Rubocop Rails/ActionOrder

---

config/locales/en.yml

Hyperlink in FAQ wasn't updated with removal of code of conduct from this repo.
Updated the FAQ link to the correct code of conduct link.
-   [x] I have verified all tests and linters pass after …

Fix: fixing code of conduct link

---

app/views/static_pages/community_rules.html.erb

These rules need to be aligned with current moderation.
- Expands on the mental health rule to include other topics
- Moves politics and religion to 0 zap level
- Moves mild unprofessionalism to mild toxicity
Related to https://github.com/TheOdinProject/moderator/issues/2
-   [x] …

Rule Update: Reword and reorganize rules

---

app/views/static_pages/community_rules.html.erb

These two rules need to be moved to align with current moderation.
- Moves asking for help on outside projects to 0 zaps
- Moves unsolicited pings to 0 zaps
Related to https://github.com/TheOdinProject/moderator/issues/10 …

Rule Update: Move 2 rules to 0 Zaps

---

app/views/static_pages/community_rules.html.erb

This rule needed more examples to fully encompass everything
* treating others disrespectfully was left off previous changes
* add trolling to list of specific examples
* add other unprofessional behavior as a general bucket
Closes https://github.com/TheOdinProject/moderator/issues/4
-   [x] The `Because` section summarizes the reason for this …

Rules: Update mild toxicity Rules

---

db/fixtures/paths/full_stack_javascript/courses/javascript.rb

gonna move the 'eslint and prettier' section to the front of the main JS content.. think of it as a mini 'installations' section.

move linting lesson

---

app/javascript/components/lesson-preview/components/lesson-content-preview.jsx

[Lesson preview tool](https://www.theodinproject.com/lessons/preview) currently renders parts of the page incorrectly due to missing classes.
- Manually updates the classes in the React component to be in line with the ViewComponent used for the lesson styling.
Closes #3555
As discussed in the issue, this is a temporary fix and any changes in the lesson styling will need to be done in the React component as well to keep the preview in parity with what is the case on live pages.
- `Feature` - adds new or …

Fix: Update styling for lesson preview to be in line with the current one

---

babel.config.js
package.json
yarn.lock

Because:
* This package is EOL and we have migrated to Shakapacker

Chore: Remove rails/webpacker package

---

db/fixtures/paths/full_stack_rails/courses/javascript.rb

[PR #3539](https://github.com/TheOdinProject/theodinproject/pull/3539) moved the Linting lesson in the JavaScript path's JavaScript Course from the "JavaScript in the Real World" section to the "Introduction" section. This change is not reflected in the Rails path JavaScript course.
For comparison:
[Rails path JavaScript course](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/javascript)
[JavaScript path JavaScript course](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript)
- Updates the location of the JavaScript linting lesson in the Rails path to mimic the change in the JavaScript path.
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTIN …

Fix: Update Rails path JavaScript linting lesson location

---

app/views/static_pages/community_rules.html.erb

We've decided to blanket ban fundraising/donation initiatives on the server.
- Adds a rule covering fundraising and donation links.
Closes https://github.com/TheOdinProject/moderator/issues/54
The rule has to be added to the `#rules` channel itself as well.
-   [x] The `This PR` …

Rules: add fundraising/donation rule

---

app/views/static_pages/community_expectations.html.erb

The purpose of this PR is fixing a minor grammar mistake, this might even give a more professional look.
* Switched place of "even"
Closes #XXXXX
-   [x] I have verified all tests and linters …

Fix: minor grammar mistake

---

app/views/static_pages/community_rules.html.erb

The email mentioned `theodinproject@gmail.com` is not in use. 
- changes the contact email to `theodinprojectcontact@gmail.com`
Closes #XXXXX
[Discord discussion where KM mentions the email in use](https://discord.com/channels/505093832157691914/991035463949254767/1080066268947816448)
-   [x] The `Because` section summarizes the reason for this …

Fix: change incorrect TOP email into the one in use 

---

db/fixtures/lessons/ruby_on_rails_lessons.rb

i have removed unnecessary from ruby on rails lesson tittle 
Closes #3654 
-   [x] If this PR addresses an open …

fix: remove unnecessary comma from title

---

app/views/lessons/installation_lessons/index.html.erb

If it broke, fix it
Use display title instead of phantom helper
Closes #3657

Fix: Broken lessons appendix page

---

app/models/lesson.rb
spec/models/lesson_spec.rb

Because:
* None of this is used anymore.

Chore: Remove Dead Code From Lesson Model 💀

---

app/javascript/stylesheets/prism-theme.css

It fixes Inconsistent code block styles
- Removed margin property which was getting applied to code blocks which have class= "language-bash"
Closes #3665 
-   [x] I have verified all tests and …

Fix Inconsistent code block styles

---

config/routes/redirects.rb
spec/requests/redirects_spec.rb

Because:
* Our vanity url is dependent on the server having a level 3 boost.
This commit:
* Use ODIN_CHAT_URL for the discord route redirect.
* Add a request spec around our discord redirect.
Closes #XXXXX
-   [ ] The `This PR` section has a bullet point list describing the changes …

Chore: Use ODIN_CHAT_URL invite link for the discord redirect

---

app/javascript/components/project-submissions/containers/project-submissions-container.jsx

The project titles aren't currently being displayed in the project submssions component.
- Accesses the project title using `lesson.title` instead of `lesson.display_title`.
Closes #3688 
- …

Fix: project title display in `ProjectSubmissionsContainer` component

---

app/views/static_pages/community_rules.html.erb

The zap system is not in alignment with our professional expectations.
*  Updates the rules on website to updated format
Closes https://github.com/TheOdinProject/moderator/issues/58
We will not want to merge in this PR until we have the Discord rules channel updated & the Rules Screening process when new people join our server.
-   [x] The …

Fix: Update the rules with simpler format

---

app/javascript/components/lesson-preview/index.jsx
package.json
yarn.lock

Mermaid was introduced in https://github.com/TheOdinProject/theodinproject/pull/3708 but the package had to be downgraded to 9.4.3 from 10.0.2 as webpack was failing to compile.
- Updates mermaid to version 10.1.0 as the issue has been resolved in https://github.com/mermaid-js/mermaid/pull/4164
Closes #3716 …

Chore: Update mermaid to 10.1.0

---

app/javascript/components/lesson-preview/index.jsx
package.json
yarn.lock

Because:
* It is causing main to fail on CI and blocking other work.

Chore: Downgrade Mermaid

---

app/views/static_pages/about/_overview.html.erb
app/views/user_mailer/welcome_email.html.erb
app/views/user_mailer/welcome_email.text.erb

We are no longer required to mention Thinkful
* Removes Thinkful from the About page
* Removes Thinkful from the both email formats
-   [ ] I have verified all tests and linters pass after …

Chore: Remove references to our previous sponsor

---

app/controllers/static_pages_controller.rb
app/views/shared/_footer.html.erb
app/views/static_pages/privacy_policy.html.erb
config/initializers/odin_configuration.rb
config/routes.rb
spec/requests/static_pages_spec.rb

Because:
* We need our own privacy policy instead of linking to Thinkfuls.

Feature: Add Privacy Policy Page

---

db/fixtures/lessons/node_js_lessons.rb
db/fixtures/paths/full_stack_javascript/courses/node_js.rb
db/fixtures/paths/full_stack_javascript/seed.rb

Fix capitalization. Change "NodeJs" to "NodeJS"
- Change "NodeJs" to "NodeJS"
Closes #XXXXX
-   [ ] If this PR …

Fix: Change "NodeJs" to "NodeJS"

---

db/fixtures/lessons/foundation_lessons.rb
db/fixtures/paths/foundations/seed.rb

The CSS foundations lesson is exceptionally large compared to other lessons, containing a huge amount of information. To make it more digestible and easier to track progress through the lesson, it has been broken up into smaller lessons covering the major topics of the original lesson.
- Removed CSS Foundations
- Added Intro to HTML and CSS,
- Added Intro to CSS,
- Added The Cascade
Closes https://github.com/TheOdinProject/curriculum/issues/24064 by adding curriculum changes to main top site.
[curriculum changes PR](https://github.com/TheOdinProject/curriculum/pull/25260) …

Main repo lessons added for curriclum PR: #25260

---

db/fixtures/paths/full_stack_javascript/courses/javascript.rb
db/fixtures/paths/full_stack_rails/courses/javascript.rb

Installing and configuring Prettier and ESLint has been confusing for new learners who have not really been exposed to NPM packages at all yet, except to `npm install` what's needed in the "JavaScript Exercises" repo.
Moves the "Linting" lesson from the "Introduction" section of the JavaScript course back to the "JavaScript in the Real World" section.
Closes #XXXXX
Closes https://github.com/TheOdinProject/curriculum/issues/24987
I don't think the idea to have this content earlier in the curriculum is a terribly bad idea. In the future we could likely improve these lessons include a proper introduction to NPM and perhaps only introduce Prettier at the start. 
Currently, it's agreed to push the lesson back for now.
-   [x] I have thoroughly read and understand [The Odin Project Contributing …

Feature: JavaScript - Move linting lesson to 'JavaScript in the Real World' section

---

app/javascript/stylesheets/lesson-content.css
tailwind.config.js

Different variations (note, extra, warning) of lesson note boxes draw attention to readers for important/warning information.
- Added CSS classes to varied lesson note boxes, including the use of corresponding icon by Fontawesome.
Closes #3431 
-   [x] The `This PR` section has a …

Feature: Add CSS variations to lesson note boxes #3431

---

app/views/guides/community/before_asking.html.erb
app/views/guides/community/expectations.html.erb
app/views/guides/community/how_to_ask.html.erb

- Due to some reorganization some of the guide pages have dead links
- fixes those links
Closes #3840 
-   [x] If …

Fix: repoint links to correct locations

---

app/views/lessons/_header.html.erb
db/fixtures/lessons/foundation_lessons.rb
db/fixtures/lessons/getting_hired_lessons.rb
db/fixtures/lessons/javascript_lessons.rb
db/fixtures/lessons/node_js_lessons.rb
db/fixtures/lessons/ruby_lessons.rb
db/fixtures/lessons/ruby_on_rails_lessons.rb
db/fixtures/paths/foundations/seed.rb
db/fixtures/paths/full_stack_javascript/courses/getting_hired.rb
db/fixtures/paths/full_stack_javascript/courses/javascript.rb
db/fixtures/paths/full_stack_javascript/courses/node_js.rb
db/fixtures/paths/full_stack_rails/courses/getting_hired.rb
db/fixtures/paths/full_stack_rails/courses/javascript.rb
db/fixtures/paths/full_stack_rails/courses/rails.rb
db/fixtures/paths/full_stack_rails/courses/ruby.rb

- The lesson titles got incorrectly capitalised with `text-transform: capitalize` through the `capitalize` class
- Some lesson titles were incorrectly capitalised regardless of class
- fix incorrect capitalisation according to the [Chicago Title Capitalisation style rules](https://capitalizemytitle.com/style/Chicago/)
- remove `capitalize` class from titles
Closes #3812
- rspec test fail for community guides only, this is due to the Ruby version (mine is 3.1.2) according to Chook
- `Feature` - adds new or …

Fix: Incorrect capitalisation on titles and in lesson overview. Closes: #3812

---

app/javascript/application.js

**Because:**
* It makes the site blazingly™️ fast
* Mostly closes #3806 
* Remove global Turbo disable
* Add compatibility hacks for ReactRailsUJS to play nicely with Turbo

Feat: Enable Turbo Drive globally on site (#3806)

---

public/400.html

- Currently the comment points to the `400.html` file living in `public/404.html`, but it instead lives in `public/400.html`
- Corrects the comment to point to the right location
Closes #XXXXX
- …

Fix: fix location of file

---

app/components/complete/button_component.html.erb
app/components/complete/icon_component.html.erb
app/components/theme/switcher_component.html.erb

Removed attributes enabling Turbo in a couple of components, since now Turbo is enabled globally.
- Removed turbo: true from the [complete/icon_component.html.erb file](https://github.com/TheOdinProject/theodinproject/blob/main/app/components/complete/icon_component.html.erb#L1)
- Removed turbo: 'true' from the [theme/switcher_component.html.erb file](https://github.com/TheOdinProject/theodinproject/blob/main/app/components/theme/switcher_component.html.erb#L5)
- Removed data-turbo="true" from the [complete/button_component.html.erb file](https://github.com/TheOdinProject/theodinproject/blob/main/app/components/complete/button_component.html.erb#L2)
Closes #3873 
-   [x] I have thoroughly read and understand [The Odin Project Contributing …

Chore: removed Turbo true attributes

---

app/views/users/sessions/new.html.erb

This PR autofocus' the email field when a user clicks on the sign-in link on the landing page of the website.
- Added `autofocus: true` to the email form field on the sign-in page
Closes #3874  …

Feature: add autofocus to sign in page email field

---

app/views/guides/community/how_to_ask.html.erb

The wording of this guide did not match the !question bot command, which could bring some confusion. 
> Lesson link:
Code: [code sandbox like replit or codepen]
Issue/Problem: [screenshots if applicable]
What I expected:
What I've tried:
* 5 things to include match the language of the bot command
* Re-organizes the guide to group tips in before / preparing / after asking your question
* Adds some language from the community expectations that make more sense in this guide. https://www.theodinproject.com/guides/community/expectations
Relates to https://github.com/TheOdinProject/moderator/issues/65
We recently debated adding more information to our asking questions rule, like having users remain online and not asking follow up questions. At this time, I felt like these additions would bloat …

Fix: Update How To Ask guide to match language in !question command

---

app/views/guides/community/before_asking.html.erb

Site reorganization left a dead link. A previous PR fixed this issue for some links, but the one for _Problem Solving_ was missed.
The url is mistakenly: https://www.theodinproject.com/guides/community/lessons/foundations-problem-solving
The correct url is: https://www.theodinproject.com/lessons/foundations-problem-solving
- fixes link for Problem Solving page
Related to #3842 
- `Chore` - changes that have no user-facing value, refactors, …

Fix: repoint link for problem solving

---

app/views/static_pages/home/_curriculum.html.erb
app/views/static_pages/home/_how_it_works.html.erb

When running lighthouse it points out that the h_x_ ordering isn't quite right, hence header hierarchy needs to be fixed. This PR would provide a well-structured heading hierarchy which would not only help search engines, but also improves the readability and user experience, also fixing the h_x_ ordering.
Both "How it works" and "Learn everything you need to know" are h2, but the items under those headers are all h4. They should be h3, to make the hierarchy work.
Closes #3954 
- `Feature` - adds new or …

Feature: Fixed Header Hierarchy

---

.erb-lint.yml
app/views/lessons/completions/create.turbo_stream.erb
app/views/lessons/v2_project_submissions/create.turbo_stream.erb
app/views/lessons/v2_project_submissions/destroy.turbo_stream.erb
app/views/lessons/v2_project_submissions/update.turbo_stream.erb
app/views/project_submissions/v2_likes/create.turbo_stream.erb
app/views/themes/update.turbo_stream.erb

Because:
* We are using turbo more and more and have no lint coverage in these files.

Chore: Enable erblint in turbo stream files

---

app/views/guides/community/before_asking.html.erb

The links are broken / come out as "Page Not Found".
- Update "<a href="lessons/foundations...>" to "<a href="/lessons/foundations...>"
- Update "<a href="lessons/ruby-debugging....>" to "<a href="/lessons/ruby-debugging...>"
Closes #3970
link to a Discord discussion: https://discord.com/channels/505093832157691914/514204667245363200/1129164175491465317
- `Fix` - …

Fix: fix broken links in the page

---

db/seeds/success_stories.rb

Added link to my website
My website has lots of content about Turbo Native, and I was hoping it would inspire people to learn what is possible with Hotwire. 
- This is a one-line change with my website name
-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x ] The `Because` section summarizes the reason for this PR
-   [x ] The `This PR` section has a bullet point list describing the …

Feature: update success_stories.rb to include link to website

---

db/seeds/test_admins.rb

I'd like to be able to log in for testing purposes
- added `manon` to the list (because `kevin` was already taken)
Closes #XXXXX
-   [ ] I have verified all tests and linters pass after making …

Update test_admins.rb with my name: manon

---

db/seeds/test_admins.rb

This would eliminate the need for people to request to be added to the list, reducing possible unnecessary overhead.
After approval I can update the [wiki instructions](https://github.com/TheOdinProject/theodinproject/wiki/Review-Apps)
- add `tester` to the names
Closes #XXXXX
- …

Update test_admins.rb to include a generic testing account

---

app/views/static_pages/about.html.erb
app/views/static_pages/about/_overview.html.erb

It makes the usage of "The Odin Project" consistent
- Change casing
- Reword Odin to The Odin Project
Closes #XXXXX …

Fix: Make usage of "The Odin Project" consistent

---

app/views/guides/community/how_to_ask.html.erb

- The lesson contains inconsistent heading styles (non-sentence case)
- The lesson contains some grammar errors
- Fix the headings to sentence-case 
- Fix grammar errors
Closes #XXXXX
-   [ ] I …

How to ask a technical question: Fix heading styles and grammar errors

---

.gitignore
app/components/content_container_component.html.erb
app/components/content_container_component.rb
app/helpers/lessons_helper.rb
app/views/lessons/show.html.erb

Add links to lessons for learners to report issues with lessons instead of getting taken to make the changes themselves.
- Adds a `Report an issue with this lesson` link next to the `Improve this lesson` link at the bottom of every lesson
- Adds a `Learn how to contribute` link as well.
- Adds a font awesome flag icon and a book icon for the respective links 
- Adds a small amount of padding between the links
- **Moves links above the completion component**
- **Adds responsiveness to show only icon with tooltip on mobile view**
~This is a draft PR. More work needs to be done on where the report an issue will be linked to.~  ready for review.
discord link - https://discord.com/channels/505093832157691914/991035463949254767/1135930665502769226 
-   [x] I have thoroughly read and understand …

Feature: add `report lesson` and `how to contribute` links in lesson footers

---

app/views/guides/community/how_to_ask.html.erb

- The `improve this lesson on github` link was broken 
- Fix the broken link
#4033
I didn't realize this issue was something in regard to the `theodinproject` repository and not the `curriculum` repository of TOP. This is my first time contributing to this one, and I'm not quite sure if I solved the issue correctly. Below is the corrected link. 
- The current broken link is https://github.com/TheOdinProject/theodinproject/edit/main/app/views/static_pages/how_to_ask.html.erb
- The correct link should be https://github.com/TheOdinProject/theodinproject/edit/main/app/views/guides/community/how_to_ask.html.erb
-   [x] The title of this …

How to ask a technical question: Fix a broken link

---

app/components/card_component.html.erb
app/components/card_component.rb
app/views/static_pages/home/_success_stories.html.erb
app/views/static_pages/success_stories.html.erb
db/seeds/success_stories.rb

Success stories current always link to *somewhere*. Ostensibly, this would be the social_media_link associated with the success story, but not all success stories had a link. This created a confusing UX experience.
- Modifies the success story section on the home page to point to the specific story on the success_stories page.
- On the success_stories page, the user name and a link.svg are presented as links to the user's social media if their link is present.
- A normal `p` tag is rendered if there is no social media link present.
- Allows the CardComponent to take in an id.
Closes #3851
-   [x] The title of this PR follows the …

Chore: Improves success story redirects.

---

config/routes.rb

Because:
* These routes are no longer needed.

Chore: Remove unused routes

---

.github/ISSUE_TEMPLATE/chore.yaml

- Its useful to have a dedicated template for chores
- Adds a new Chore issue form: `chore.yaml`
Closes #4134 
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section

Feature: Add Chore issue template

---

.github/PULL_REQUEST_TEMPLATE.md

adds proper indenting for the title PR keywords
- adds more spacing to indent the keywords in the PR requirements section
Current: 
This PR Update: 
Closes #XXXXX
-   [ ] I have verified all …

Fix PULL_REQUEST_TEMPLATE.md indentation

---

app/views/guides/community/before_asking.html.erb
app/views/guides/community/expectations.html.erb
app/views/guides/community/how_to_ask.html.erb
app/views/guides/community/rules.html.erb
app/views/static_pages/dashboard_steps/_github_link.html.erb

- Make footer styling consistent between lessons and community guides
- Make the GitHub 'improve lesson' 404 link functional.
- Gives non-lesson content same 'Report issue' layout where appropriate. 
- Updated github_link_html.erb to point to an issue template in the correct repo
Closes #4061 
Related to #4057 
Note that due to the nature of the community guides, we only implemented a 'Report issue' link as the 'Improve on GitHub' link didn't make sense due to the files not being in markdown format. 
- …

Chore: footer fix community pages to match lesson content

---

config/locales/team.yml

Because:
* He's our first alumni

Team page: Add Erik

---

config/locales/team.yml

Closes #XXXXX
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If …

Fix: Typo with example core member

---

config/locales/team.yml

The Team Page does not have my information
Adds my information to it
Closes #XXXXX
-   [x] If this PR addresses an …

Update team.yml with Zach M

---

config/locales/team.yml

I was asked to do this :D
Adds myself to the list
-   [x] If this PR addresses an open issue, it is linked in the …

Feature: add myself to 'teams.yml'

---

config/locales/team.yml

We're adding ourselves to the Team page.
Adds me to the Team page.
-   [x] If this PR addresses an open issue, it …

Chore: Update team.yml for Zach Baird.

---

config/locales/team.yml

Because I was told to!
- Adds myself to the team yaml
N/A
-   [x] If this PR addresses an open issue, it is linked …

Feature: Add myself to team yaml

---

app/views/static_pages/about.html.erb

The gap between buttons in contact page is too small
updates the gap so it's the same with buttons in  [the contributing page](https://www.theodinproject.com/contributing)
Closes #4160
Shout out to Josh on Discord for helping me to run the project locally
-   [x] The `This PR` …

Feature: Add button gap in contact page

---

app/views/static_pages/home/_curriculum.html.erb

Aligning course titles in the course listing cards. 
- added tailwind class 'rounded-lg' to link
- added `flex grow items-center` to the headings
Related to #4153 
-   [ X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X ] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
-   [ X] The `Because` section summarizes the reason for this PR
-   [ X] The `This PR` section has a bullet point list describing the changes in this PR
-   [X ] I have verified …

Enhancement: Center course titles in course listing

---

config/locales/team.yml

All the cool kids are doing it
Add me in the alumni section in team.yaml
Closes #XXXXX
-   [ ] If this PR addresses …

Add self as alumni

---

config/locales/team.yml

Yes
- Add Javier to alumni
Closes #XXXXX
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` …

Chore: add javier

---

db/fixtures/lessons/getting_hired_lessons.rb
db/fixtures/paths/full_stack_javascript/courses/getting_hired.rb
db/fixtures/paths/full_stack_rails/courses/getting_hired.rb

This PR adds the new Professional Networking lesson that was merged into the Curriculum repo: https://github.com/TheOdinProject/curriculum/pull/26307
Added lesson reference in seeds
Added lesson routes in Getting Hired for each path
Closes #XXXXX
Thank you to all reviewers and maintainers for putting up with my nagging to get this in :)
-   [x] …

Add lesson: Add the professional networking lesson

---

db/fixtures/lessons/react_lessons.rb
db/fixtures/paths/full_stack_javascript/courses/react.rb
db/fixtures/paths/full_stack_rails/courses/react.rb

@01zulfi
I think I added the relevant changes, i followed [Adding-a-Lesson](https://github.com/TheOdinProject/theodinproject/wiki/Adding-a-Lesson).
I was going through [Running The Odin Project Locally](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally), I am stuck on this step with this error
Closes #XXXXX …

Feature: Reflect merge react conclusion

---

config/locales/team.yml

Adds macdaniel to the odin project team member page.
Closes #XXXXX
-   [x] If this PR addresses an open issue, it …

Added macdaniel to team page.

---

config/locales/team.yml

Adding my team member information.

add my team member information

---

config/locales/team.yml

Kevin created an awesome team page!
Adds my details
-   [ ] If this PR addresses an open issue, it is linked in the …

Add rlmoser to team page

---

config/locales/team.yml

I'm not on the team.yaml yet and I don't want to see what Kevin's "unfriendly" reminder to add myself looks like
Adds me to it
Closes #XXXXX
-   [ ] I have verified all tests and linters pass …

Chore: Add self to team.yml

---

config/locales/team.yml

Closes #XXXXX
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If …

Update team.yml for thatblindgeye

---

config/locales/team.yml

To update the team page on the website.
Updating team page
Closes #XXXXX
-   [ ] If this PR addresses an open …

Update team.yml for the team page

---

config/locales/team.yml

Updated from alumni back to a moderator
- Removes my information from alumni section
- Adds my information in Moderators section

Team.yml: Move self info to the moderators section

---

config/locales/team.yml

I'm a maintainer now :tada: 
- Move myself from mod to maintainer
Closes #XXXXX
-   [x] If this PR addresses an …

Team config: Move myself (josh) from moderators to maintainers

---

db/fixtures/lessons/html_and_css_lessons.rb
db/fixtures/paths/full_stack_javascript/courses/advanced_html_css.rb
db/fixtures/paths/full_stack_rails/courses/advanced_html_css.rb

Updates lesson details for `personal project` in advanced HTML/CSS to fall in line with the project rename and content edits as per [#26608](https://github.com/TheOdinProject/curriculum/pull/26608). PR suggested [here](https://discord.com/channels/505093832157691914/505093832157691916/1168166227672317962).
- Updates personal project details with new name, description and path to lesson's curriculum .md file
- Updates the Node pathway's fixture to fetch the updated lesson details
- Updates the Rails pathway's fixture to fetch the updated lesson details
N/A
**Requires the following curriculum repo PR to be merged alongside this:** [#26608](https://github.com/TheOdinProject/curriculum/pull/26608)
-   [x] I have thoroughly read and understand [The Odin Project Contributing …

Feature: Update personal portfolio project with new lesson details

---

app/views/guides/community/rules.html.erb

**DO NOT MERGE:** Depends on TheOdinProject/curriculum/pull/25402
- We're moving to support WSL2
- Updates the rules file to refer to WSL as a supported OS

Feature: Update rules to account for TOP now supporting WSL

---

app/views/guides/community/rules.html.erb

Using Windows is not the only tool that should not be recommended
* Changed Windows to a generic operating system
* Added two other examples: web browsers and code editors
Closes #XXXXX
https://discord.com/channels/505093832157691914/1181965268432461925/1182215817434234963
-   [x] …

Fix: Add more examples to rule

---

config/locales/team.yml

1. Ada Chiu
a) Image URL broken 
b) There is the mentioned image URL instead of github profile URL.
2. Eric Olkowski
Image link was broken, updated it with the latest linkedin photo (He probably changed it there, that's why it's broken)
- Fixed Image URL for Ada Chiu
- Fixed Github URL for Ada Chiu
- Updated image URL for Eric Olkowski
Closes #XXXXX
- `Fix` - bug …

Fix: replaced broken URLs in "Team" 

---

app/mailers/user_mailer.rb
app/views/user_mailer/welcome_email.html.erb
config/environments/production.rb
spec/mailers/user_mailer_spec.rb

This pr addressed #4002  . I have updated the relevant code and fixed the broken home page banner issue.

Fix broken home page banner

---

CONTRIBUTING.md

#4112 Removed Jest which tested React. There is no need - and no way - to correctly run `yarn test` on the current version of the app before submitting a PR.
Removes the line that asks a contributor to run `yarn test`
N/A …

Fix: remove jest testing from app PR instructions

---

db/fixtures/paths/full_stack_javascript/courses/javascript.rb
db/fixtures/paths/full_stack_rails/courses/javascript.rb

In #4326 I forgot to edit the course fixtures (which determine the order the lesson appears in the course). So this is basically just correcting my oversight in that PR :upside_down_face: 
Double checked that it's fully functional this time by populating the curriculum content locally and checking that things are in order. Lesson learned on that one.
- Fixes the ordering of the JSON lesson in the JavaScript course for both paths.
Closes #XXXXX
- …

Fix: Correct JSON lesson order in course fixtures

---

config/locales/team.yml

I'm a team member.
Adds me to the team on the site.

Team: Add scheals

---

db/fixtures/lessons/foundation_lessons.rb
db/fixtures/paths/foundations/seed.rb

The foundations lesson titled 'Fundamentals Part X' are not descriptive of what they actually teach, and should be renamed.
Rename fundamentals parts 1-5 to:
- Variables and operators
- Data types and conditionals
- Function basics
- Arrays and loops
- Object basics 
Closes #[27278](https://github.com/TheOdinProject/curriculum/issues/27278) in the curriculum repo.
Related to PR #[27342](https://github.com/TheOdinProject/curriculum/pull/27342) in the curriculum repo.
- `Feature` - adds new or amends existing …

Feature: Rename JavaScript Foundation Lessons to be more descriptive

---

db/fixtures/lessons/foundation_lessons.rb
db/fixtures/paths/foundations/seed.rb

The lesson titles in the curriculum follow (pretty sure) the Camel Case, which I've missed in my last PR to rename these lessons, this PR is a quick fix for that to ensure consistency for lesson titles.
- Correct capitalisation of newly-renamed foundation lessons
Closes #XXXXX
- …

fix: correct capitalisation of newly-renamed foundation lessons

---

config/locales/team.yml

I am new and was ordered to add myself, so here I am adding myself as ordered due to being new.
- Adds me to the maintainer portion of team.yml
N/A
Edit: reworded as referring to myself in the 3rd person is incredibly strange …

Chore: Add Mao to team.yml

---

config/locales/team.yml

- Because why not
- adds me!
Closes #XXXXX
-   [x] If this PR addresses an open issue, it is linked in the `Issue` …

Chore: Add Ben(raryay) to the team

---

config/locales/team.yml

Image is broken on teams page on site
- Updates image URL
Closes #4437 
-   [ ] If this PR addresses an open issue, …

Update user image for thatblindgeye

---

config/locales/team.yml

I have joined the team
Adds my details to the team info page
-   [ ] If this PR addresses an open issue, it is …

Feature: Update team.yml for new member

---

db/fixtures/lessons/ruby_on_rails_lessons.rb
db/fixtures/paths/full_stack_rails/courses/rails.rb

There's a new lesson for the Rails course on validations added in this PR to the curriculum repo: https://github.com/TheOdinProject/curriculum/pull/27651
- Adds new lesson to the Rails course fixtures
- Runs `db:seed` task
Closes #XXXXX
-   [x] The `This PR` section has a bullet …

Feature: Add ActiveRecord Validations lesson

---

CONTRIBUTING.md

Closes #XXXXX
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If …

Update URL in Contributing md

---

app/javascript/controllers/modal_controller.js

Fixes layout shift that occurs when opening a modal.
- Fixes layout shift that occurs specifically on mobile devices when opening a modal by updating `pr-4` to `sm: p-4`
This PR Closes [#4481]("https://github.com/TheOdinProject/theodinproject/issues/4481")
https://github.com/TheOdinProject/theodinproject/assets/49371751/00c63ea5-8109-401b-a828-beb9b40298e6
- `Fix` …

Fix: Modal Layout Shift

---

app/components/modal_component.html.erb
app/components/progress_circle/component.html.erb

This PR fixes the badge overlap that occurs when opening a modal over a progress bar on smaller screens.
- Changed the z-index from 10 to 30 within the `modal_component.html.erb` file
- Changed the z-index from 30 to 10 within the `progress_circle/component.html.erb` file
This PR Closes [#4480]("https://github.com/TheOdinProject/theodinproject/issues/4480")
[Screencast from 04-09-2024 09:12:12 AM.webm](https://github.com/TheOdinProject/theodinproject/assets/49371751/5d1768e1-2ee7-4e6c-942e-557dbe977c1f)
- …

Fix: progress badge overlap

---

app/components/progress_circle/component.html.erb

Fixes the progress bar z-index properties when someone has fully completed a course.
- Changed z-10 to z-20 within the main svg element
- Changed z-20 to z-10 within the child div element
This PR does not close specific issue.
Video showcasing the bug: 
[Screencast from 04-10-2024 07:58:10 AM.webm](https://github.com/TheOdinProject/theodinproject/assets/49371751/44004f9f-4d3f-4dc0-a914-bec49618e66c)
Video showcasing the fix:
[Screencast from 04-10-2024 09:40:23 AM.webm](https://github.com/TheOdinProject/theodinproject/assets/49371751/6fb44a40-0c8e-4c3c-9564-2cba8b84bbec) …

Fix: progress bar

---

db/fixtures/paths/full_stack_rails/courses/rails.rb

Corrects lesson order per [these](https://github.com/TheOdinProject/curriculum/issues/27477) closing comments
- simply switched two lines of text in the file `db/fixtures/paths/full_stack_rails/courses/rails.rb`
Related to #27477
-   [x] The `This PR` section has a bullet point …

Feature - Correct lesson order

---

.babelrc

We were missing syntax highlighting support for `bash` code blocks, and will also reasonably imagine having `json`, `yaml` and `properties` code blocks as well, all of which were also missing.
- Adds all 4 above languages to the PrismJS plugin options
Closes #4501
-   [x] The `This …

Chore: Add missing language support

---

app/assets/stylesheets/stylesheets/lesson-content.css
app/components/markdown/preview_component.rb
app/javascript/controllers/lesson_toc_controller.js
lib/kramdown/content_section.rb
lib/kramdown/converter/odin_html.rb
lib/kramdown/document_sections.rb
spec/lib/kramdown/content_section_spec.rb
spec/lib/kramdown/document_sections_spec.rb
spec/services/markdown_converter_spec.rb
tailwind.config.js

`h4` headings were generating IDs but were not clickable like with `h3` headings.
- Makes level 4 headings render `h4 > a` like with level 3 headings
- Moves the generated IDs to the heading elements themselves, instead of the parent `section`
- Replaces `section` `id` attribute with `data-title`
- Amends CSS and Tailwind accordingly
- Amends toc controller accordingly
- Amends rspec tests to account for new HTML structure
- Allows `data-title` to render in preview component
- Reduces duplication in a method
Closes #4503
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the …

Feature: Clickable h4 elements

---

app/javascript/controllers/modal_controller.js

- Adds and removes padding right from the body instead of padding around the full body.

Fix: Layout shift on desktop

---

spec/lib/kramdown/document_sections_spec.rb
spec/services/markdown_converter_spec.rb

#4507 changed the HTML structure generated by Kramdown, and existing tests for h3s and sections were adjusted to account for this in that PR. However, there were not any tests that actually tested the new h4 behaviour.
- Adds tests for Kramdown for the new h4 structure
N/A
-   [x] …

Chore/Tests: Add tests for new level 4 heading Kramdown behaviour

---

db/fixtures/lessons/git_lessons.rb

This PR fixes the `404 - page not found` error when clicking the `Improve on GitHub` link in the Intermediate Git: Working with Remotes lessons for the [Ruby](https://www.theodinproject.com/lessons/ruby-working-with-remotes) and [JavaScript](https://www.theodinproject.com/lessons/javascript-working-with-remotes) paths. 
- Add missing forward slash to the beginning of the github path
n/a
n/a
- `Chore` - changes that have no user-facing value, …

Fix: Correct broken path leading to 404 page

---

package.json
yarn.lock

Reverts TheOdinProject/theodinproject#4556

Revert "Upgrade: Bump @sentry/browser from 7.108.0 to 8.8.0"

---

app/views/admin_v2/flags/index.html.erb

Because:
- The flags details page is centered, and the layout should be consistent between these two pages.

Feature: Center admin v2 flags index page

---

app/controllers/admin_v2/flags_controller.rb
app/models/flag.rb
spec/models/flag_spec.rb

Because:
- When I am handling flags, I want to see the most recent first

Feature: Order flags by most recent

---

app/components/Ui/back_link_component.html.erb
app/components/Ui/badge_component.rb
app/components/Ui/dropdown/trigger_component.html.erb
app/components/admin/pagination_component.html.erb
app/components/flags/action_button_component.html.erb
app/views/admin_v2/announcements/edit.html.erb
app/views/admin_v2/announcements/index.html.erb
app/views/admin_v2/announcements/new.html.erb
app/views/admin_v2/announcements/show.html.erb
app/views/admin_v2/dashboard/show.html.erb
app/views/admin_v2/flags/index.html.erb
app/views/admin_v2/flags/show.html.erb
app/views/admin_v2/invitations/new.html.erb
app/views/admin_v2/team/_member.html.erb
app/views/admin_v2/team/show.html.erb
app/views/layouts/admin_v2/_nav_bar.html.erb
app/views/layouts/admin_v2/_sidebar_nav.html.erb
app/views/layouts/admin_v2/base.html.erb

Because:
- When I have dark mode enabled elsewhere on the site, I want admin V2 to be styled the same.
This commit:
- Adds dark mode styling for admin v2 dashboard, flags and announcement screens.

Feature: Admin V2 - Optimise Dark Mode

---

app/views/admin_v2/invitations/edit.html.erb

- The previous iteration had a small typo and pushed a lot of text inside a h2
- Fixes the typo
- Split the second line into a span instead of the h2 and slightly rewords it
-   [x] I have …

Feat: Admin v2: Tweak admin password creation screen

---

config/initializers/rack_attack.rb

Rate limit... 
- sign ups
- sign ins
- password resets
- Overall rate limit for every page when request count for an ip goes over a certain threshold. 
-   [x] I have verified all tests and …

Chore: Tune Rate limiting

---

db/fixtures/lessons/node_js_lessons.rb
db/fixtures/paths/full_stack_javascript/courses/node_js.rb

As per (https://github.com/TheOdinProject/curriculum/issues/27907), the new Environment Variables lesson would replace the previous Security Configuration lesson. We forgot to remove it from the course's lesson list.
- Removes "Security Configuration" from the Node course's lesson list
Closes #XXXXX
-   [x] The `Because` section summarizes the …

Feature: Remove Security Configuration lesson

---

db/fixtures/paths/full_stack_javascript/courses/databases.rb

Home page had repeating sections on databases, removed the redundant one.
- Removes the `course.show_on_homepage` attribute
Closes [#4624](https://github.com/TheOdinProject/theodinproject/issues/4624)
nil
-   [x] The `This PR` section has a bullet point list describing the changes …

Remove show_on_homepage attribute from Databases course fixture

---

db/fixtures/paths/full_stack_javascript/courses/databases.rb

- This is the NodeJS version, so it shouldn't mention Rails
- Mentioning ORMs at this stage is weird, since the learner won't have been introduced to them yet
- Rewrites the section description to be more generic
-   [x] The `This PR` section has a bullet point list describing the …

Feat: Rewrite Databases section description

---

config/spring.rb

Chore: Remove Spring

---

app/components/modal_component.html.erb
app/views/admin_v2/team_members/index.html.erb
app/views/layouts/admin_v2/_nav_bar.html.erb
app/views/layouts/admin_v2/_sidebar_nav.html.erb

- Modal overlay takes full screen
- Fix invite button centering when on smaller screens

Feature: Admin - v2 styling tweaks

---

app/controllers/admin_v2/team_members/resend_invitation_controller.rb
app/views/public_activity/admin_user/_reinvited.html.erb

When I resend an invite to an admin team member, I want an activity to be created.
Closes #4663
-   [x] If this PR …

Feature: Create an activity when resending an invite email

---

app/views/admin_v2/invitations/new.html.erb
app/views/devise/mailer/invitation_instructions.html.erb
app/views/devise/mailer/invitation_instructions.text.erb
config/locales/devise_invitable.en.yml
spec/requests/admin_v2/team_members/reactivation_spec.rb
spec/requests/admin_v2/team_members/resend_invitation_spec.rb
spec/system/admin_v2/invitations_spec.rb
spec/system/admin_v2/reactivations_spec.rb

This commit:
- A few tweaks to the invitation email copy
- Uppercase the roles in the role select field

Chore: Admin V2 - Copy updates

---

db/seeds.rb

- There is a stray accounts left over
- removes it 

Fix: remove stray accounts

---

db/migrate/20240806175334_drop_admin_comments_table.rb
db/schema.rb

Removes active admin comments table that is not used.
-  Generated a migration to drop the `active_admin_comments` table.
- The migration updates the schema to remove the `active_admin_comments` table.
Closes #4692
-   [x] The `This PR` section has a bullet point list describing …

Chore: remove admin comments table

---

app/assets/stylesheets/stylesheets/typography.css

- The link icon next to headers wasn't replaced when the font awesome icons were dropped in #4720
- Replaces them with the heroicon equivalent
-   [x] I have verified all tests and linters pass …

Fix: Fix icon not being replaced

---

package.json
yarn.lock

Because:
- We are a major version behind
- Closes: https://github.com/TheOdinProject/theodinproject/issues/3716

Chore: Bump Mermaid

---

config/application.rb
config/initializers/new_framework_defaults_7_1.rb

Follow up part 1 for https://github.com/TheOdinProject/theodinproject/pull/4736
Relates to https://github.com/TheOdinProject/theodinproject/issues/4735

Chore: Toggle low risk framework defaults for Rails 7.1

---

.github/workflows/ci.yml
.gitignore
app/javascript/src/sentry.js
esbuild.config.mjs
package.json
yarn.lock

Because:
- It will help us diagnose JavaScript exceptions

Chore: Add Sentry source maps

---

app/views/static_pages/about.html.erb
app/views/user_mailer/welcome_email.html.erb
app/views/user_mailer/welcome_email.text.erb
config/initializers/odin_configuration.rb
config/locales/en.yml

Our contact email has changed
Updates the contact email
Closes #XXXXX
-   [ ] If this PR addresses an open issue, …

Chore: Update contact email

---

package.json
yarn.lock

Because:
- We were a patch version behind

Chore: Bump Stimulus-use

---

package.json
yarn.lock

Because:
- We were a few patch versions behind

Chore: Bump Autoprefixer

---

package.json
yarn.lock

Because:
- We were a patch version behind

Chore: Bump browser list

---

config/locales/en.yml

- Removes the freelance and skimming the lessons parts from the `Who is the Odin Project for` question.
Closes #4762 
-   [x] I have verified all tests and linters pass after making these …

Fix: Update outdated info in FAQ

---

config/locales/team.yml

Outdated team page info
Updates team info
Closes #XXXXX
-   [ ] If this PR addresses an open issue, it is linked in …

Chore: Update team config file

---

config/locales/team.yml

Team changes
- Removes me from the active team member list
Closes #XXXXX
-   [x] If this PR addresses an open …

Chore: Update team page

---

db/fixtures/lessons/javascript_lessons.rb
db/fixtures/paths/full_stack_javascript/courses/javascript.rb
db/fixtures/paths/full_stack_rails/courses/javascript.rb

Fixes minor typo in a section and lesson title (Organizing Your Javascript Code...)
Capitalized the 'S' in 'Javascript'
Closes #4849
-   [ ] I have verified all tests and linters pass after …

Fix minor typo in Section and Lesson titles

---

config/locales/team.yml

Adds a moderator details.
- Adds "Lofty" to the moderators' team.
N/A
-   [x] If this PR addresses an open issue, …

chore: updates team.yml

---

config/locales/team.yml

- Adds onto Moderator list 
- Add's Tosh onto moderator list in teams yml
N/A
-   [x] If this PR addresses an open …

chore: update team.yml

---

config/locales/team.yml

Adds Elemeandor to Moderator list
- Adds Elemeandor to moderator list in team.yml
N/A
-   [x] If this PR addresses …

Chore: Add Elemeandor to team.yml

---

CONTRIBUTING.md

`yarn test` is no longer used in The Odin Project's main repo since React was removed, and needs to be removed from CONTRIBUTING.md instructions.
- `yarn test` removed from 'Testing Changes Locally' section in CONTRIBUTING.md
Closes #4856
-   [x] The `This PR` section has a bullet …

Chore: Removed yarn test from contributing guide

---

app/views/guides/community/expectations.html.erb

In Community Expectation page,change the channel name since #odin-general was outdated and replace to #odin-main
The problem is that in the Community Expectation Page, the #odin-general was outdated and was replaced to #odin-main a while ago so we need to update it to #odin-main
- Changed #odin-general to #odin-main from Community Expectation Page
Closes #XXXXX
- …

Fix: Change #odin-general to #odin-main

---

db/fixtures/lessons/ruby_lessons.rb
db/fixtures/paths/full_stack_rails/courses/ruby.rb

https://github.com/TheOdinProject/curriculum/issues/28940#issuecomment-2752058580
- Drops the Event Manager lesson
Related to TheOdinProject/curriculum#28940 …

Feat: Drop Event Manager from Files and Serialisation

---

app/assets/stylesheets/custom_styles/prism-theme.css

- The restriction to only bash has been broken for quite some time, and nobody has squealed.
- Drops the restriction from the codebase
Closes #4943 
-   [x] I have verified all tests and linters …

Chore: Drop copy button language restriction

---

app/views/shared/_footer.html.erb

- The `<h2>` element in the footer was using `text-gray-600 dark:text-gray-400`, which did not meet WCAG AA contrast standards.
- Updated the text color of the `<h2>` element in the footer to `text-gray-600 dark:text-gray-300` to meet WCAG AA contrast requirements.
Closes #4815 
NA …

Improve text contrast for accessibility

---

db/fixtures/paths/full_stack_javascript/courses/node_js.rb

The current placement of the “Introduction to Frameworks” lesson in the NodeJS course comes before students have learned basic backend concepts with Node.js. This can make it hard to appreciate what frameworks actually abstract away. Moving it to the top of the Express section improves the conceptual flow of the course.
- Moves the Introduction to Frameworks lesson from the “Introduction to NodeJS” section to the beginning of the “Express” section in the NodeJS course structure
- Helps learners encounter backend fundamentals before diving into abstraction
Closes #4964  …

Move 'Introduction to Frameworks' lesson to the beginning of the Express section in the NodeJS course structure

---

README.md

The Scrimba link in the Readme is leading to empty page
- Removes the scrimba link and the corresponding paragraph
Closes #4852
-   [ ] I have verified all tests and linters pass after making …

Fix: Scrimba link in Readme removal

---

db/fixtures/lessons/foundation_lessons.rb
db/fixtures/paths/foundations/seed.rb

To accommodate the changes in https://github.com/TheOdinProject/curriculum/pull/29705
Must be merged alongside that PR to avoid 404s for learners.
- Renames the "Arrays and Loops" lesson to "Loops and Arrays", including relevant paths
- Fetches renamed lesson in the Foundations path
N/A
-   [x] The `Because` section summarizes the reason for …

Feature: Rename "Arrays and Loops" lesson to "Loops and Arrays"

---

config/locales/team.yml

Reverts TheOdinProject/theodinproject#4847
:tada:

Revert "Chore: Update team page"
