- app/views/static_pages/_sg_js.html.erb
- app/views/static_pages/studygroups.html.erb
that was weird. not sure y ds_store got included. the js studygroup is open js studygroup with no specific agenda, so I didn't see a need to put a calendar up. I plan to have it every week for the foreseeable future.
> add js studygroup

- app/assets/stylesheets/static_pages.css.scss
- app/views/shared/_navbar.html.erb
- app/views/static_pages/chat.html.erb
- config/routes.rb
The current method of finding groups on odin is cumbersome as the user has to go into the account dropdown and then into study groups and then scan through the list of meet ups. It's hidden in a sense and I would bet money that some users on TOP haven't even found the list of meetups and groups because you really have to go looking for it.
A social drop down right on the navbar will be immediately visible and will be much more user friendly. with the integration of a slack chat it will make the odin project a much more social experience by bringing together everyone who is working through it.
> Added social option on navbar

- doc/linux_setup.md
- doc/mac_setup.md
This puts the guides under odin ownership instead of as gists of two different people. I also added a step to prepare the test database to both guides which was overlooked before.
Ticket for this PR:
https://trello.com/c/amDQiPhN/22-move-main-site-set-up-guides-over-to-be-odin-as-readme-s
> Moved guides into docs

- Gemfile
- Gemfile.lock
This is part of the ongoing simplification of the contributing process, when running bundle on the main site an issue with the rubyracer gem stopped the bundle. The solution was to remove the version from the gem file.
Ticket on Trello: https://trello.com/c/NyZxVJgB/19-fix-ruby-racer-gem-issue-on-main-site
> Removed ruby racer version

- lib/tasks/curriculum.rake
There is a bug for me where the same lessons are being updated even when it has not changed. It is really weird...
Anyway this will significantly reduce the time it takes to update content however there are a few caveats you should be aware of 
1. I tried lowering number of threads but database error is thrown
2. Occasionally errors will be thrown but rerunning rake task usually solves it
3. Output is well.. ugly lol
In my opinion I would be tentative to add this into production but I use it in my development environment.
> Add threading to rake task

- app/controllers/users_controller.rb
- app/helpers/bootstrap_flash_helper.rb
- spec/controllers/users_controller_spec.rb
Fixes #166 
- Remove the `handle_nil_user` method
- Rescue the exception in `set_user` method and redirect the user to `users_url`
- Add tests to check the behaviour of GET users#show with a controller spec
- Refactor the code in `bootstrap_help` method
> Redirect if a non-existent user is being searched

- db/seeds.rb
This removes the unneeded backbone lesson from web dev 101.
> removed backbone lesson from web dev 101

- app/helpers/admin_flash_helper.rb
- spec/helpers/admin_flash_helper_spec.rb
This is a refactor of the admin flash helper, It cleans up the long `disabled_flash_ids_from_cookies`method and the unit tests for this helper.
Fixes https://github.com/TheOdinProject/theodinproject/issues/218
> refactored admin flash helper

- app/views/static_pages/contributing.html.erb
I noticed the link to the Gitter chat on the Contributing page wasn't working so I just made a quick fix.
> Fix chat link on Contributing page

- app/assets/stylesheets/lessons.scss
Fix lc-end-circle and lc-active-circle appearing on top of breadcrumbs and scroll-effect-alert.
> Fix progress bar circles appearing on top of other elements

- db/migrate/20161017230606_drop_splash_emails_table.rb
- db/schema.rb
Addresses Issue #246 
I generated a migration to drop the existing splash_emails table from the database. After the migration, I confirmed that the table is no longer in the schema and then ran the specs to ensure nothing was broken in the process. All specs were green.
> Remove splash emails table from database schema.

- spec/models/lesson_completion_spec.rb
Addresses Issue 262
I replaced the two FactoryGirl variables with doubles, added shoulda matchers to test the validations and associations, and removed the last test. I did not address the existing comment about testing that the lesson completion is deleted when a lesson or user is deleted—slightly beyond my scope of knowledge.
> Refactor lesson completion model spec file

- features/lesson_navigation.feature
- features/step_definitions/navigation_steps.rb
This adds cukes to cover edge cases with the navigation buttons on lesson pages
> More cukes for lesson navigation feature

- config.reek
This removes the migration files from being evaluated by reek.
> Exclude migration files from reek

- app/assets/stylesheets/lessons.scss
All I've done is add a bit of css to all `ul`s on the main lesson content on lesson pages.  Doing it this way has the downside of potentially adding a scrollbar to other ul's on the lesson pages... but on the few I looked at this didn't happen.  Most lists on the lessons are `ol`s.
The other downside is that I can't _really_ add any other styling (a border might be nice) to the solutions box because it would effect the main content of the lesson
Doing it this way has the upside of being very simple... the alternative is adding html markup to the lesson pages which could be a big pain and hard to maintain.  I'm not opposed to doing it, but this way is much simpler to implement, at least initially.
I've attached a screenshot of what the change looks like on _my_ system.. but note that the …
> added a max-height and scrollbars to student solutions

- app/controllers/application_controller.rb
- app/models/user.rb
- db/migrate/20161022000746_remove_reg_before_conf_from_users_table.rb
- db/schema.rb
- spec/factories/factories.rb
- spec/features/email_spec.rb
This removes the work arounds for users who signed up before confirming emails was mandatory.
> removed reg before conf

- app/views/static_pages/studygroups.html.erb
I noticed that bit.ly link was pointing to the old CodeBuddies site. I just updated the link to go to the homepage.
> Update CodeBuddies link in studygroups page.

- app/assets/stylesheets/lessons.scss
as you can see.. this targets the second-to-last ul only.  this should clean up the subtle problems with other lists getting targeted.
this fix depends on "Additional Resources" being a ul, and being after the solution list... which is a situation that doesn't make me very happy, but ideally this whole thing is just a temporary hack to get us by until the redesign.
> made scrollbar only appear on the solutions list

- app/assets/stylesheets/lessons.scss
On small screens #lesson-nav appears on top of the scroll down menu.
> Fix #lesson-nav appearing on top of scroll down menu

- db/seeds.rb
This removes the ruby on the web section from the ruby course.
> removed ruby on the web section

- app/assets/stylesheets/components/success_stories.scss
- app/views/static_pages/success_stories.html.erb
#418 Redesign: Success Stories Page
CHANGES:
- Removed margin-top from class .success-stories-sign-up.
- Added `margin-bottom: 6em;` to .success-stories-page .success-stories-container. NOTE: I did not add the margin-bottom to the .success-stories-container embedded in .success-stories, only the one embedded in .success-stories-page.
- Added `margin-bottom: 3.6em;` to .success-stories-page .success-stories-sign-up to increase the spacing between the "Sign Up" button and the footer matching the spacing between the container and the "Start learning for free now" text.
- The p tag enclosing the student's name now has the class `student-name`. That class has `margin-bottom: 20px;`.
FIXES:
- Class `.success-content-full` was in the CSS but referred to as `.success-content` in the view. I …
> Complete redesign requests for success stories page

- app/assets/javascripts/navbar.js
Since we have a full-screen navbar implemented, there is no need to watch for a click event to collapse the navbar if the click was made outside the navbar.
> Remove click event listener

- app/views/courses/_course_overview.html.erb
Only a button linked to the course details, allowing the entire
title to be clickable is more intuitive.
> Wraps curriculum course cards in a link

- app/assets/stylesheets/components/login_page.scss
- app/assets/stylesheets/global.scss
Not sure if it closes #505 
Was not able to replicate the resizing of icons, but I did find that a right whitespace on mobile when you scrolled right, this was displaying for all the pages, This keeps the page in view only. Also noticed both signup card and login card was offset from view, instead of giving the various buttons and fields strict widths, this allows for good responsiveness.
> Fix mobile responsive bug

- app/assets/stylesheets/components/contributing.scss
- app/assets/stylesheets/components/courses.scss
- app/assets/stylesheets/mixins.scss
- app/views/static_pages/contributing.html.erb
This changes the buttons on the contributing page to use the new button component instead of the main button mixin. Because of this we can also remove that mixin.
> use button class on contribution page

- app/controllers/application_controller.rb
- app/controllers/registrations_controller.rb
- app/controllers/static_pages_controller.rb
- app/views/layouts/_confirm_email.html.erb
- spec/controllers/static_pages_controller_spec.rb
I didn't modify the `after_update_path_for` method because we're using `best_in_place` to perform in-place edits. Do we need that method? Is it fine to remove the `after_update_path_for` method?
/cc @KevinMulhern
> Redirect signed in users to the dashboard

- app/helpers/application_helper.rb
This small change updates the connect text on the how it works section of the homepage to focus on the community instead of pairing.
> Update connect text on the home page

- app/assets/stylesheets/lessons.scss
- app/views/lessons/show.html.erb
This changes the lesson title to a h2 and puts it in the lesson view instead of getting it from the lesson content on the curriculum. This will be merged when the lessons on the curriculum are amended to remove the title
> Change lesson headings

- app/controllers/omniauth_callbacks_controller.rb
- app/models/user.rb
- features/support/env.rb
- spec/controllers/omniauth_callbacks_controller_spec.rb
- spec/factories/factories.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
This feature serves two purposes:
1. It will set the  avatars of users who have signed up with github before the avatar feature was introduced
2. If the user changes their avatar on github, they just need to sign in to Odin again to update it on our site
> Update users avatar

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/users/_profile_card.html.erb
- db/migrate/20170629181228_remove_estimated_completion_date.rb
- db/schema.rb
This removes the estimated completion date that the user can set, it was decided that this would do more harm than good with how optimistic a lot of our students are with timeframes 😛 
When this is merged, https://github.com/TheOdinProject/theodinproject/issues/617 can be unblocked
> Removed estimated completion date from the user table

- app/assets/stylesheets/lessons.scss
Some list items are being covered by lesson nav..
Also tested on real mobile
> fixed lesson-nav overlaying navbar on mobile view

- app/assets/stylesheets/components/login_page.scss
- app/helpers/application_helper.rb
- app/helpers/button_helper.rb
- app/views/devise/registrations/_signup_form.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/lessons/show.html.erb
- app/views/projects/index.html.erb
- app/views/shared/_bottom_cta.html.erb
- app/views/shared/_github_button.html.erb
- app/views/static_pages/about.html.erb
- app/views/static_pages/contributing/_hall_of_fame.erb
- app/views/static_pages/faq.html.erb
- app/views/static_pages/home/_success_stories.html.erb
- app/views/static_pages/success_stories.html.erb
- app/views/users/show.html.erb
- spec/helpers/button_helper_spec.rb
Tasks done:
- Use the `bottom_cta` component for the ‘Have an account’ section
- Change column size to 6 in signup page
- Reduce the size of the icons within the input fields on mobile view
- Remove github icon from 'Sign up with Github' button in mobile view
> Tweak signup page

- app/assets/stylesheets/components/about.scss
- app/views/static_pages/about.html.erb
- app/views/static_pages/about/_contact.html.erb
Tasks done:
- Underline 'send us an email'
- Update 'Want to contact us' to a h2 and add a bottom margin of `1em`
-  Remove `60px` of padding bottom on 'Want to contact us' heading on mobile view
- Align 'Chat on gitter' button with the image, fix image being too small on 1020px and 768px
> Tweak about page

- app/assets/stylesheets/components/dashboard.scss
- app/views/users/_profile_card.html.erb
#646 
On medium screen sizes and up, user cards on the dashboard are thinner/shorter and aligned across. On mobile (sm), they remain centered.
> Simplify and horizontalize user card on dashboard

- app/assets/stylesheets/components/navbar.scss
**Included:** Excluded the divider in navbar from getting the hover functionality. Also, this makes the link area compressed in height as it was filling up a huge chuck outside the text.
> Change hover style for nav-item and excluded divider from functionality

- app/assets/stylesheets/components/dashboard.scss
- app/assets/stylesheets/components/settings/settings_view.scss
- app/assets/stylesheets/mixins.scss
- app/views/devise/registrations/_learning_goal.html.erb
- app/views/users/show.html.erb
> Issue #667: Dashboard Tweaks

- app/assets/javascripts/form_validations.js
- app/assets/stylesheets/components/form/form.scss
- app/assets/stylesheets/components/form/form_divider.scss
- app/views/devise/registrations/_form.html.erb
- app/views/devise/sessions/_form.html.erb
This refactors the naming of the auth form so is more generic and therefore can be used throughout the site. This will also allow the form validations to work with any form that follows the same structure.
> Refactor Auth Form to Make it Generic

- app/assets/stylesheets/typography.scss
- app/assets/stylesheets/utilities.scss
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
This makes the password reset forms usable and styles them the same as our other forms
---
---
> Style and Structure Password Reset forms

- app/assets/stylesheets/components/course-badge.scss
- app/views/courses/_course_overview.html.erb
- app/views/shared/_course_badge.html.erb
Resolves step one on https://github.com/TheOdinProject/theodinproject/issues/707
* Turns a badge for a course into a component
* New Raised style for the badge
This completes step 1 of the progress indicators for courses.
> Course Badge Component

- app/features/project_submission_feature.rb
- app/views/lessons/show.html.erb
- spec/features/project_submission_feature_spec.rb
This turns off the project submission feature so the redesign can go out.
> Turn off Project Submission feature in production

- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/services/course_progress.rb
- app/services/next_lesson.rb
- app/views/users/_course_buttons.html.erb
- app/views/users/_skill_progress.html.erb
- spec/services/next_lesson_spec.rb
Fixes https://github.com/TheOdinProject/theodinproject/issues/724
If the user has started a course it will now allow them to go straight to the next lesson in they are on in a course.
> Change Course Buttons to Resume on Dashboard

- app/assets/stylesheets/global.scss
The link focus styles were defaulting to bootstrap's style which included a color of `#014c8c`. This PR fixes it by updating styles of links on focus state.
> Update styles for focus on links

- app/helpers/course_helper.rb
- spec/helpers/course_helper_spec.rb
This makes projects a bit more obvious on a course page
> differentiate projects on course page

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/lesson/lesson_content.scss
- app/models/lesson.rb
- app/services/markdown_converter.rb
- app/views/lessons/show.html.erb
- spec/models/lesson_spec.rb
- spec/services/markdown_converter_spec.rb
We are switching to Kramdown for rendering markdown to html as it allows markdown to be wrapped in block level html elements.
> use kramdown for rendering markdown

- config/routes.rb
Fixes #788 
I tried putting it at the bottom next to the other deprecated links, but it wasn't worked
I think it has to do with entering the /courses/ scope or something
This does work though
> Added redirection route for deprecated external links

- db/seeds.rb
TheOdinProject/ruby_course#4
I'm not sure why the deletion looks like it's happening mid-lesson.
> Remove wd101/testing_basics from seed

- app/models/lesson.rb
- app/services/lesson_content_importer.rb
- config/environments/development.rb
- db/migrate/20171104233052_add_repo_to_lesson.rb
- db/schema.rb
- db/seeds.rb
- spec/models/lesson_spec.rb
- spec/services/lesson_content_importer_spec.rb
- spec/tasks/curriculum_spec.rb
This moves all ruby related lessons over to the [ruby course repo](https://github.com/TheOdinProject/ruby_course) and changes the way lesson content is imported so we can be more flexible with the repo lesson content comes from.
* Created `repo` column on lessons table
* Moved lesson content import logic into its own class
* Added the repo field to all lessons in the seeds file.
> Move Ruby Lessons to Its own Repo

- Gemfile
- Gemfile.lock
Report:
```
Name: nokogiri
Version: 1.8.0
Advisory: CVE-2017-9050
Criticality: Unknown
URL: https://github.com/sparklemotion/nokogiri/issues/1673
Title: Nokogiri gem, via libxml, is affected by DoS and RCE vulnerabilities
Solution: upgrade to >= 1.8.1
```
> Update nokogiri to fix vulnerability issue

- README.md
I added them to the "Contributing" section, since these information are most useful for (potential) contributors.
[Preview](https://github.com/chancancode/theodinproject/blob/8bba5341f5ac473a9c324644df4220f66141971b/README.md)
> Add Travis and Skylight badges to README [ci skip]

- app/assets/javascripts/analytics.js.erb
- app/controllers/lesson_completions_controller.rb
- app/views/layouts/application.html.erb
- app/views/lessons/_lesson_buttons.html.erb
- app/views/lessons/_lesson_completion_state.html.erb
We have been seeing quite a few unique validation errors in New Relic. After investigating I believe this is happening due to users clicking the complete lesson button multiple times in a short period of time.
This disables the complete and un-complete button until the ajax request for the lesson completions button is completed.
This error has occurred 65 times over the past 7 days:
This also includes a small fix for JS errors with jquery not being found with the lesson buttons ga tracking.
That was caused by the application.js files being recently moved to the bottom of the page so jquery was loaded after the script for the ga tracking.
> Fix Unique Validation Errors for Lesson Completions

- app/views/shared/_head.html.erb
Fixes #880 
Turbolinks 5.1 fixes this also so async can come back after gem is updated
> Use defer rather than async to get around Turbolinks bug

- db/migrate/20180413180306_add_student_index_to_lesson_completions.rb
- db/schema.rb
In exploring performance data on [Odin Project's Skylight page](https://oss.skylight.io/app/applications/g0gJSNnzYAws/recent/6h/endpoints), I noticed that this query was not optimized:
```sql
SELECT "lesson_completions".* FROM "lesson_completions" WHERE "lesson_completions"."student_id" = ?
```
While the query itself isn't currently super slow, we noticed that it occurs on every endpoint (You can see it on the Skylight event sequence as "SELECT FROM lesson_completions"), and we noted that as the lesson_completions table grows the query might start to have a bigger impact on performance.
Despite the fact that the [compound index](https://github.com/TheOdinProject/theodinproject/blob/master/db/schema.rb#L53) does provide some benefit if it is only partially used, [Postgres …
> Index lesson_completions on student_id

- db/seeds/02_ruby_course_seeds.rb
Just noticed this when setting up the project: two urls appear to be wrong in the seed data, causing some trouble for the content importer rake task.
> Fix some inconsistencies between seed/real data

- app/controllers/courses_controller.rb
- app/helpers/application_helper.rb
- app/models/course.rb
- app/models/user.rb
- app/services/course_progress.rb
- features/step_definitions/lesson_steps.rb
- spec/controllers/courses_controller_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/models/course_spec.rb
- spec/services/course_progress_spec.rb
This is a follow up to #888 (I also work at Tilde/Skylight).
Currently, a [significant amount of time](https://oss.skylight.io/app/applications/g0gJSNnzYAws/1523662560/6h/endpoints/CoursesController%23index?responseType=html) (up to 40%!) is spent in loading and initialize the lesson objects:
We originally suspected a missing index, but as @gitKrystan and @zvkemp pointed out, this wasn't the case. Turns out, the reason it is slow is because the lessons have a big `content` field, making them very expensive to load:
1. The database has to read a lot into memory
2. The database has to send back a big result
3. The Ruby driver has to parse/process the big payload
4. The `content` field need to be loaded/copied into big Ruby strings
5. Having these big strings in memory increases memory …
> Optimize `CoursesController#index`

- config/initializers/devise.rb
When we implemented Github oauth we must have copy and pasted the
instructions straight from the read me of the github-omniauth gem.
The example included a scope which requested full read and write
permission to the user's profile and repos on Github. We don't need
any of that and it creeps a lot of users out when prompted to review
permissions upon signing up.
This removes those permissions so we only request read only access to
the users profile on Github and nothing else.
> Change to Read Only Permission with Github Oauth

- app/assets/javascripts/lessons.js
For #903.
When Markdown is parsed, the header text is turned to lowercase, and any characters other than alphanumeric character, spaces, and hyphens are removed. Spaces are then replaced with hyphens to form the anchor.
> Excludes punctuation from header anchor links

- app/assets/stylesheets/components/lesson/_navigation.scss
fixes this:
and makes it look like this:
> fix lesson nav bullets with some CSS.

- Gemfile
- Gemfile.lock
- app/assets/javascripts/lessons.js
The side nav was rendering links to all headings on lessons instead of white
listed headings only.
This also updates Nokogiri to fix a security warning Jenkins was complaining about.
> Fix Side Nav Bug

- app/assets/stylesheets/components/lesson/lesson_content.scss
Per #920 slight styling change to the Summary tags in dropdowns. 
Increased font size and weight, as well as changing the colour back to the primary text colour, increases visibility and causes the heading of each detail drawer to stand out.
This goes along with a curriculum pull request. https://github.com/TheOdinProject/curriculum/pull/8075
> Fix for issue #920: Added class names to summary tag in installfest.

- db/seeds/06_javascript_course_seeds.rb
The new JS frameworks project isn't listed as a project in the seeds. This is my fix.
> update seeds for js frameworks project to style it as a project

- db/seeds/06_javascript_course_seeds.rb
Removes the 'Project: ' prefix from the `title` and `title_url` fields for 'Frameworks' project as we don't want the title to prefixed by double  'Project:'
ie. The lesson has been marked as a `project` and a project lesson has a [`title`](https://github.com/TheOdinProject/theodinproject/blob/seeds-update/app/decorators/lesson_decorator.rb#L4) method which returns the lesson title prefixed by 'Project' anyway.
> Update frameworks project title and title url in seeds

- app/assets/javascripts/lessons.js
- app/helpers/button_helper.rb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_navbar_modal.html.erb
- app/views/static_pages/about.html.erb
- app/views/static_pages/contributing/_contributing_options.html.erb
- app/views/static_pages/contributing/_hall_of_fame.erb
- spec/helpers/button_helper_spec.rb
This PR fixes a vulnerability on links with `target` attribute set to `_blank`.
For more info, check [this](https://developers.google.com/web/tools/lighthouse/audits/noopener) out.
> Adds rel='noreferrer' to external links

- spec/support/vcr.rb
- spec/vcr/lesson_content.yml
CI was failing every time it ran due to a missing vcr cassette. The cassette was
previously stored in `tmp/cassettes` which was not committed to git.
This fixes that by moving the storage location of vcr cassettes to `spec/vcr`.
> Fix Failing Test on CI

- spec/factories/factories.rb
Factory Bot is flagging up depreciation warnings when we run the unit tests.This Resolves them.
> Fix Factory Bot Depreciation Warnings

- app/views/layouts/application.html.erb
- app/views/shared/_fb.html.erb
Per conversation between @KevinMulhern and @adamelevenson, I was asked to add a FB pixel to the home page for tracking.
Please let me know if this is an acceptable way to do it. I based it off of the pattern I saw already in this codebase for Google Analytics.
I had looked into the [Rack Tracker](https://github.com/railslove/rack-tracker) gem for this, but decided against it once I saw the `_ga` partial. But do let me know if you think using Rack Tracker is a cleaner way to do it.
Thanks!
> add FB pixel

- Gemfile
- app/services/mailchimp_subscription.rb
- spec/services/mailchimp_subscription_spec.rb
Users who attempted to sign up with email and password were getting incorrectly
redirected to `/users` instead of to their dashboard. After investigation this was
caused by the Mail Chimp news letter sign up service.
It is currently erroring out when trying to connect to the Mail Chimp.
To stop this issue from affecting users we have wrapped the call to the
Mail Chimp api in a rescue block that will log any occurrences of this error to New Relic
so we have visibility of it.
> Fix Error With Email and Password Sign Up's

- app/models/user.rb
- spec/models/user_spec.rb
We see quite a few validation errors day from username validation failures when users
try to sign in through google or github omniauth.
Increasing the range of valid username sizes should reduce frequency of these errors
significantly.
> Ease Username Size Validations

- .travis.yml
We no longer use phantom so this can be removed from the Travis config
> Remove Phantom from Travis Config

- app/assets/stylesheets/components/navbar_modal.scss
Bug #960 - Navbar out of alignment
Setting the `line-height` and `height` of the `.nav-link` class to the same size (in this case 5vh) seems to have fixed the alignment of the "Community" drop-down menu link.
> Fix/Bug #960 - Navbar out of alignment

- Gemfile
- Gemfile.lock
- app/admin/dashboard.rb
- app/assets/javascripts/active_admin.js.coffee
- app/assets/stylesheets/active_admin.scss
- app/controllers/application_controller.rb
- config/initializers/active_admin.rb
- config/routes.rb
- db/migrate/20190204213636_create_active_admin_comments.rb
- db/schema.rb
Adds base functionality for activeadmin.
This makes use of the existing user model and utilises the existing admin flag for users.
For now unauthorised users who try to access the /admin path have been routed to root_path, we can modify this or add a flash as necessary.
Once merged and accepted as working ok we can start the process of registering the required models that admins will be able to access.
> Add active admin

- app/services/lesson_content_importer.rb
- spec/services/lesson_content_importer_spec.rb
Previously, when lesson content import failed, we were logging the `lesson.errors` object.
The PR updates it to log the exception message.
> Update lesson content importer exception handling

- app/views/static_pages/home/_curriculum.html.erb
Issue #[10452](https://github.com/TheOdinProject/curriculum/issues/10452)
I changed button to say "Get Started" instead of "view curriculum".
> Replace 'View Curriculum' with 'Get Started'

- app/views/static_pages/home.html.erb
The button on the homepage to View Full Curriculum currently still only
goes to the default RoR track. It should now go to the tracks path to
mirror the behaviour of the Curriculum link in the navigation menu
> Edit home page so that curriculum button shows track options

- db/seeds/tracks/full_stack_rails.rb
The original wording stated that the Ruby on Rails track takes a student
though the entire curriculum. With NodeJS as an option this is not
longer correct. This clarifies the track as specific to Ruby on Rails
> Update Ruby on Rails track description

- .rubocop.yml
- Gemfile
- Gemfile.lock
The rubocop post-install message now states performance cops will be
removed in Rubocop 0.68 and are now maintained in the Rubocop
Performance Gem. This adds the gem and requires the file in the rubocop
yml
> Add Rubocop Performance

- app/helpers/application_helper.rb
This adds the node badge to the available_courses helper which displays
all the badges on the home page.
> Add Node Badge to home page

- README.md
This adds those people who have helped push TOP forward to the
significant contributors list on the README
> Update significant contributors to Readme

- Gemfile
- Gemfile.lock
Because:
* The current version of puma we are running is a security rick.
This Commit:
* Bumps Puma to the latest version.
* Removes the version constraint for Puma in the Gemfile. The Gemfile.lock should be the source of truth for what versions we are running.
> Chore: Bump Puma

- app/views/lessons/_lesson_completion_state.html.erb
Because:
* although this does not impact users it makes a lot of noise in our NewRelic error logs.
This Commit:
* Adds a data-disable-with attribute to the lesson completion buttons so users cannot double click them.
> Fix Unique Validation Errors Being Raised On Lesson Completions

- README.md
- app/helpers/application_helper.rb
- app/views/shared/_footer.html.erb
- app/views/shared/_head.html.erb
- app/views/user_mailer/welcome_email.html.erb
- app/views/user_mailer/welcome_email.text.erb
- spec/helpers/application_helper_spec.rb
- spec/helpers/button_helper_spec.rb
This updates the discord invite links to point to the new #rules channel instead of throwing the new user into an empty space and having to click "rules" themselves.
> Updates discord link

- app/models/user.rb
- spec/helpers/button_helper_spec.rb
- spec/models/user_spec.rb
Because:
* We use the users name on their Google account to populate their username on TOP. Some Users have large names on their google account however.
This Commit:
* Increases the username max character limit to 100.
We should come up with a better solution for this long term, but this quick fix will resolve the issue for now.
> Fix: Google Omniauth Username Validation Error

- db/seeds/01_web_dev_101_seeds.rb
- db/seeds/02_ruby_course_seeds.rb
- db/seeds/04_rails_course_seeds.rb
This now moves all ruby and rails content to their relevant sections.
The aim is to have web dev 101 serve content that applies to all courses
and therefore these lessons aren't relevant to front_end or node course
participants
> Remove ruby and rails references from web dev 101

- db/seeds/04_rails_course_seeds.rb
Because:
* Theres a litle bit of duplication between the imported web dev 101 lessons and what was already in this course.
This Commit:
* Renames the first section from "The Track ahead" to "Introduction"
* Renames the "Your First Rails Application" project to "Installing Rails".
* Removes the Ruby on Rails Basics lesson.
* Moves the Blogger project to the end of the Routes, Views, Controller and Assets Section.
> Chore: Make First Section of the Rails Course Simpler

- db/seeds/04_rails_course_seeds.rb
Because:
* We want to keep file location names consistent between the seeds and curriculum.
> Chore: Update Rails Introduction File Locations

- db/seeds/04_rails_course_seeds.rb
Because:
* Its a little jarring with the new course introduction to install rails and then do sinatra lessons.
I would like these lessons to be in their own mini course before the rails course eventually. First we need a http section which can be shared between tracks.
> Chore: Remove Sinatra Section From Rails Course

- db/seeds/04_rails_course_seeds.rb
Because:
* This section isn't needed since we moved web dev 101 lessons into the full Rails course.
This Commit:
* Removes Projet: Getting Your Feet Wet
* Moves A Railsy Web Refresher Lesson into the next section.
* Moves Deployment lesson into next section.
* Removes Lets get Building Lesson
> Chore: Remove Introduction to Rails Section

- db/seeds/04_rails_course_seeds.rb
Because:
* This will now be the section that introduces students to rails and so it should be named as such.
This commit:
* Renames the section to "Rails Basics".
* Removes the basic routes, views and controllers project
* Renames the blogger project to "Project: Blog App"
> Chore: Tweaks to Second Section of Rails Course

- db/seeds/02_ruby_course_seeds.rb
Because:
* It was coming first in the basic ruby section.
> Chore: Move First Ruby Project

- db/seeds/04_rails_course_seeds.rb
Because:
* This was missed when removing the ror tutorial.
> Chore: Remove Advanced Associations Project

- app/assets/stylesheets/components/lesson/lesson_functions.scss
- app/helpers/lessons_helper.rb
- app/views/lessons/show.html.erb
Fixes https://github.com/TheOdinProject/theodinproject/issues/1095
> Add Github edit URL to the lesson pages

- .foreman
- Procfile.dev
Currently, we have to run the rails server in a tab and start the webpack dev server in another to start development. With the dev Procfile, we only have to run `foreman start -f Procfile.dev` and we are good to go.
I'll update [the docs](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally#running-the-app-locally) when this PR is merged. 
@KevinMulhern Just noticed the docs don't mention anything about installing the npm dependencies -- `yarn install`. Do you mind updating it?
> Add dev Procfile

- db/seeds/08_node_js_course_seeds.rb
I noticed the lessons URLs didn't have the `/` prefix.
> Update NodeJS lessons urls

- Procfile
- app/controllers/tracks_controller.rb
- app/models/track.rb
- app/views/shared/_navbar.html.erb
- db/migrate/20200423213901_add_slug_to_tracks.rb
- db/schema.rb
Chore: Add Friendly Id's to Tracks
Because:
* These slugs are more user/SEO friendly
---
Chore: Add Heroku Release Phase for Running Migrations
Because
* This will automate pending database migrations when we deploy.
> Chore: Add Friendly Id's to Tracks and Migrate DB on Release

- app/assets/stylesheets/components/lesson/lesson_button_group.scss
- app/views/lessons/show.html.erb
Because:
* This isn't needed as the student will know which lesson/project they are on.
* It opens up some real estate for the project submissions component.
> Chore: Remove Course and Lesson Title above Lesson Buttons

- package.json
I am not sure why the Heroku ruby buildpack does not install both dependencies and devDependencies as [Heroku Node.js buildpack](https://devcenter.heroku.com/articles/nodejs-support#package-installation) does. There is [a hacky solution](https://stackoverflow.com/questions/22954782/install-devdependencies-on-heroku) to get Heroku to install devDependencies but I am adding `babel-plugin-prismjs` to `dependencies` to get the Heroku deployment working for now. We'll have to revisit this to find a better solution.
> Move babel-plugin-prismjs to dependencies to get Heroku deployment working

- db/seeds/06_javascript_course_seeds.rb
I changed the unit description of the JS+Rails unit in the JavaScript course outline. 
A user in Discord was wondering whether he needed to (or could/should) do this unit if he'd not been exposed to Ruby, Rails, or Ruby on Rails before. He suggested he should not have to click on the unit link, just to find out it's not for him.
Solution: note added on the JavaScript course outline page to point out to users only doing Full Stack JS that they can skip this unit.
> JS and Rails unit description changed

- app/controllers/omniauth_callbacks_controller.rb
Because:
* We have Users raising this as an issue.
This commit:
* Sets a remember token that will expire in 2 weeks when users sign in with omniauth.
> Fix: Omniauth Sign In Not Remembering Users

- package.json
- yarn.lock
PR for issue #1154 
It appears that jQuery 3.5.0 broke the accordion on the FAQ page. PR bumps the version to 3.5.1, which rolled back the breaking change.
> 1154 faq accordion dropdown bug

- db/seeds/02_ruby_course_seeds.rb
Because:
* This lesson was missed when we released the new Ruby Baiscs Content.
> Feature: Add Predicate Enumerable Lesson to Ruby Basics

- db/seeds/05_html_css_course_seeds.rb
"View course" redirected to 404 in individual lessons in html and css course.
> fixed 404 page in html and css course lessons

- app/services/find_lesson.rb
- app/services/lesson_duration.rb
- spec/services/find_lesson_spec.rb
Because:
* It was calculating the duration between the current lesson and next lesson.
> Fix: Lesson Duration Task

- app/models/user.rb
- spec/models/user_spec.rb
Because:
* Usernames populated through Github can be less than 4 characters.
> Chore: Reduce Username Length Limit

- app/controllers/lessons/style_tests_controller.rb
- app/services/lesson_styles.rb
- app/views/lessons/style_tests/new.html.erb
- app/views/lessons/style_tests/show.html.erb
- config/routes.rb
- spec/services/lesson_styles_spec.rb
Because:
* We often don't know how Kramdown will render something until its in production. Being able to see how a lesson will render while developing will save time.
This Commit:
* Adds a service to render content from a pull request.
> Feature: Render Lesson Styles from Github Url

- app/assets/stylesheets/components/lesson/lesson_content.scss
Fixing the  [issue](https://github.com/TheOdinProject/curriculum/issues/18314)  from the curriculum:
> Fix long links wrapping in lessons

- config/initializers/rack-attack.rb
Because:
* Just incase anyone spams the report endpoint.
This commit:
* limits requests to the reports endpoint to 3 a minute from the same IP.
> Chore: Throttle Creating Reports

- app/javascript/components/project-submissions/components/create-form.js
- app/javascript/components/project-submissions/components/edit-form.js
- app/javascript/components/project-submissions/components/report-form.js
- app/javascript/components/project-submissions/components/submission.js
- app/javascript/components/project-submissions/components/submissions-list.js
- app/javascript/components/project-submissions/containers/project-submissions-container.js
Because:
* it makes more sense to have the edit modal in this component.
This Commit:
* Moves edit modal into submission component.
* renames edit and create forms by dropping "submission" from the name.
* Tidies things up in various places.
> Chore: Move Edit Modal into Submission Project.

- app/controllers/lessons_controller.rb
- app/javascript/components/project-submissions/ProjectSubmissionContext.js
- app/javascript/components/project-submissions/components/create-form.js
- app/javascript/components/project-submissions/components/edit-form.js
- app/javascript/components/project-submissions/components/flag-form.js
- app/javascript/components/project-submissions/components/index.js
- app/javascript/components/project-submissions/components/modal.js
- app/javascript/components/project-submissions/components/submission.js
- app/javascript/components/project-submissions/components/submissions-list.js
- app/javascript/components/project-submissions/containers/project-submissions-container.js
- app/javascript/components/project-submissions/index.jsx
- app/models/project_submission.rb
First, great job 🎉  I honestly think this was a great implementation and code. I only did minor refactoring and added the context to share some data that not all components needed.
To the context I added `userId`, `lesson` and `course` since these won't change unless user navigates to another lesson or course in which case a new component will be rendered anyways. The only data that was really being passed down multiple places without the need to, was `userId` but I included` lesson` and `course as well, it is redundant right now but it also doesn't cause any harm.
I tested this to the best of my knowledge, but it would be best to test this further as you have deeper knowledge of how exactly it is suppose to work and maybe I missed some crucial parts.
**Additionally:** besides the …
> Refactor and add context to project submission component

- config/application.rb
Because:
* the code for handling our custom 404 page was accidently removed when we upgraded to Rails 6 earlier this year.
> Fix: 404 Page Not Displaying

- app/javascript/components/project-submissions/components/modal.js
- app/models/project_submission.rb
Added to this PR is a fix for deleting project submission when it has been previously flagged. I am not sure what we want to do in this case for now I am assuming to just delete all flags if the owner of the submission decides to delete it. I am not sure if this is the behavior or outcome that is wanted. If it is not please let me know and I can change it.
> Fix project submission form not resetting after modal close

- app/models/user.rb
- config/environments/development.rb
- db/seeds/test_project_submissions.rb
Because:
* Currently we cannot test emails in development.
This Commit:
* Adds the development action mailer configuration.
* Removes the now un-needed rescue around the weclome email method call.
* Suppresses the welcome email from being sent when creating users in the seeds file.
> Fix: Letter Opener in Development

- app/models/user.rb
- spec/models/user_spec.rb
Because:
* These don't seem to be needed anymore since we have a custom omniauth signup process
This Commit:
* Removes password_required? and new_with_session methods from user model.
> Chore: Remove Methods on User Model For Old Omniauth

- app/controllers/project_submissions/flags_controller.rb
- app/javascript/components/project-submissions/components/index.js
- app/javascript/components/project-submissions/components/submission.js
- app/javascript/components/project-submissions/components/submissions-list.js
- app/javascript/components/project-submissions/containers/project-submissions-container.js
Because:
* This gives the user visual feedback that their flag was successful and explains what happens next.
This Commit:
* Moves the flag modal to the container so only one of them is ever rendered.
* Stops sending flag notification to discord on development.
> Feature: Display Thanks for Flagging Message

- app/controllers/registrations_controller.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- db/migrate/20200831182324_remove_provider_and_uid_from_users.rb
- db/schema.rb
Because:
* These are no longer needed since we have a seperate table for provider details
This Commit:
* Removes the provider column from the users table.
* Removes the Uid column from the users table.
> Chore: Remove Old Omniauth Columns

- .travis.yml
Because:
* CI shouldn't fail because of security issues in dependencies as this breaks automatic deploys until the gem can be bumped.
> Chore: Remove Bundler Audit from CI

- app/admin/flags.rb
- app/assets/stylesheets/active_admin.scss
- app/models/flag.rb
- app/services/admin/flags/dismiss.rb
- app/views/admin/flags/_flag_actions.html.erb
- spec/models/flag_spec.rb
- spec/services/admin/flags/dismiss_spec.rb
Because
* Submissions may be flagged by accident or for no reason.
This Commit:
* Adds a dismiss button to admin show flag page which when clicked will trigger a dismiss flag service.
* Disables the flag action buttons when the flag has been resolved.
> Feature: Allow Admins to Dismiss Flags

- app/assets/stylesheets/components/pagination.scss
- app/assets/stylesheets/components/project_submissions/submissions.scss
- app/assets/stylesheets/components/react_modal.scss
- app/controllers/lessons/project_submissions_controller.rb
- app/controllers/lessons_controller.rb
- app/controllers/project_submissions_controller.rb
- app/javascript/components/project-submissions/components/submissions-list.js
- app/javascript/components/project-submissions/containers/project-submissions-container.js
- app/javascript/components/project-submissions/index.jsx
- app/models/project_submission.rb
- app/queries/lesson_project_submissions_query.rb
- app/views/lessons/project_submissions/index.html.erb
- app/views/lessons/show.html.erb
- config/routes.rb
Because:
* We need a page to display all project submissions for a lesson as we only show the 10 most recent on the lesson page.
This Commit:
* Adds a lesson project submissions controller and index view.
* Adds a query object to encapsulate the logic for constructing the project submission list with the users submission at the top.
* Adds pagination so we only display 15 submissions at a time on the lesson project submissions page.
> Feature: All Project Submissions for a Lesson Page

- app/javascript/components/project-submissions/components/submission-title.js
- app/javascript/components/project-submissions/components/submission.js
- app/javascript/components/project-submissions/components/submissions-list.js
- app/serializers/project_submission_serializer.rb
- spec/serializers/project_submission_serializer_spec.rb
Because:
* This will make it easier for the student to view the project page for the submission.
This Commit:
* Adds a lesson_path value to the project submissions serializer.
* Adds a SubmissionTitle Component to hold the logic for displaying the submission title.
> Feature: Change Lesson Titles to Links in User Submission List

- app/queries/lesson_project_submissions_query.rb
- spec/queries/lesson_project_submissions_query_spec.rb
Because:
* The most recently created submissions should be displayed first
This Commit:
* Orders the lesson project submissions by created at descending.
* Adds a spec for the lesson project submissions query object.
> Feature: Order Submissions List by Created at Descending

- app/controllers/lessons/project_submissions_controller.rb
- app/features/project_submission_feature.rb
- app/javascript/components/project-submissions/components/create-form.js
- app/javascript/components/project-submissions/components/flag-form.js
- app/javascript/components/project-submissions/containers/project-submissions-container.js
- app/models/project_submission.rb
- app/models/track.rb
- app/views/lessons/show.html.erb
- app/views/users/show.html.erb
- spec/features/project_submission_feature_spec.rb
Because:
* We want to start testing this feature with users.
This commit:
* Enables the project submission feature for tic tac toe on production.
* Displays the add button for signed out users and prompts them to sign in if they click it.
* Enabled the all submissions page for signed out users.
* Checks if the project can have submissions in the lesson submissions controller and redirects them back to the project if it doesn't.
> Feature: Enable Project Submissions Feature for JS Tic Tac Toe Project

- app/admin/flags.rb
Because:
* The custom filters where loading all the users into memory.
> Fix: Active Admin Flags Memory Leak

- app/admin/flags.rb
Because:
* The filters have performance problems and we shouldn't need to edit a flag.
This Commit:
* Removes the edit endpoint in admin flags.
> Feature: Hide Edit Flag

- app/models/project_submission.rb
- app/services/notifications/daily_summary.rb
- spec/factories/lesson_completions.rb
- spec/models/lesson_completion_spec.rb
- spec/models/project_submission_spec.rb
- spec/services/notifications/daily_summary_spec.rb
Because:
* This allows us to keep an eye on the use of this feature.
This Commit:
* Adds a new line for project submissions to the daily summary notification
* Adds a created_today scope to the project submission model.
* Tidies up the lesson completions created today scope tests.
> Feature: Add Project Submissions to Daily Summary Notification

- app/javascript/components/project-submissions/components/submission.js
- app/javascript/components/project-submissions/schemas/project-submission-schema.js
- app/models/project_submission.rb
- spec/models/project_submission_spec.rb
Because:
* This is optional for every project right now.
This Commit:
* Removes required validation client side for live preview url
* Removes required validation on the project submission model for the live preview url.
> Feature: Don't Require Live Preview

- app/helpers/lessons_helper.rb
- app/javascript/components/project-submissions/components/submissions-list.js
- app/javascript/components/project-submissions/containers/project-submissions-container.js
- app/javascript/components/project-submissions/index.jsx
- app/views/lessons/show.html.erb
- spec/helpers/lessons_helper_spec.rb
Because:
* We should provide an easy way to view legacy solutions while the new submissions feature is adopted.
This Commit:
* Adds a helper for creating a url to the legacy submissions for a lesson on github.
* Passes a legacy submission url to the project submissions component.
* Displays the legacy submission url beside the link to the all submissions page.
> Feature: Display a Link to Legacy Submissions

- db/seeds/06_javascript_course_seeds.rb
Because:
* We want more feedback from students.
This Commit:
* Also updates the todo project url to point to its renamed file on the curriculum repo.
> Chore: Roll Submissions Feature Out to Organizing JS Section

- app/admin/flags.rb
- app/models/flag.rb
- app/views/admin/flags/_flag_actions.html.erb
- spec/models/flag_spec.rb
Because:
* There will be scenrios where we only want to remove the submission.
This commit
* Adds a remove submission button to the admin flag show page.
* Deletes the submission and redirects to the admin flag index page when the button is clicked.
> Feature: Admin - Remove Submission

- app/views/courses/_course_card.html.erb
- app/views/courses/course/_banner.html.erb
- app/views/shared/_course_badge.html.erb
- app/views/users/_skill.html.erb
Because:
* The link to the course was being removed when it was being re-rendered after clicking the lesson completion button.
This commit:
* Moves the wrapping course link into the badde component itself so it also re-renders when a lesson completion button is clicked.
> Fix: Broken Link in Course Badge

- app/controllers/application_controller.rb
- app/views/lessons/_lesson_buttons.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_navbar_modal.html.erb
- app/views/shared/_user_dropdown.html.erb
Because:
* We have had a few reports from users not being able to login via google oauth recently. They were getting url mismatch errors, instructing them to sign in through  the login page without the ref param in the url seemed to fix it.
* This param is not needed anyway, I suspect it was used with google analytics at one point to track sign up progression in the early days of TOP.
This commit:
* Removes the ref param from internal links.
> Chore: Remove Ref Param from Internal Links.

- db/seeds/06_javascript_course_seeds.rb
The React.js "Shopping Cart" Project lesson is currently inappropriately named for what's expected of the student.
This pull request:
- Updates the seeds file for the lesson to contain the appropriate lesson name.
> Fix: Project Shopping Cart titles

- app/javascript/components/project-submissions/components/create-form.js
- app/javascript/components/project-submissions/components/edit-form.js
- app/javascript/components/project-submissions/components/submissions-list.js
- app/serializers/project_submission_serializer.rb
- db/migrate/20200930164027_add_has_live_preview_to_lessons.rb
- db/migrate/20200930171734_change_project_submission_live_preview_url_default.rb
- db/schema.rb
- db/seeds/03_database_course_seeds.rb
- db/seeds/05_html_css_course_seeds.rb
- db/seeds/06_javascript_course_seeds.rb
- db/seeds/07_getting_hired_course_seeds.rb
- db/seeds/08_node_js_course_seeds.rb
- spec/serializers/project_submission_serializer_spec.rb
Because:
* Some Projects do not have any thing to deploy to a live preview site.
This Commit:
* Adds a has_live_preview field to the lessons table.
* Hides the live preview in the create and edit submission forms if that column is set to false.
> Feature: Allow the Live Preview Field to be Hidden for Individual Projects

- db/seeds/04_rails_course_seeds.rb
Because:
* We needed to break up the api projects for the submissions feature and had enough content for a new section.
This commit:
* Creates a new Rails API section.
> Feature: Rails API Section

- license.txt
Because:
* The old license.txt was erroneously removed.
> Fix: Add Missing MIT License

- app/assets/stylesheets/components/project_submissions/submissions.scss
- app/javascript/components/project-submissions/components/submissions-list.js
Because:
* It looks a bit odd when there are no submissions for a project.
This commit:
* Displays a blank slate message in place of the submissions list when there are no submissions.
> Feature: Add a Blank Slate Message to Submissions

- Dockerfile
- entrypoint.sh
- `MAINTAINER` is deprecated. Ref. https://docs.docker.com/engine/reference/builder/#maintainer-deprecated 
- `ADD` is anti-pattern and should be `COPY` unless there's any specific reason. Ref. https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
- Having DB dependency in docker build is not "portable", which is what Docker should bring us
I also can add `docker-compose` for PostgreSQL not just for those who want to use Docker for this Rails app, but also who don't want to prepare DB on their local environment.
> Better cache and remove DB dependency on docker build

- app/assets/stylesheets/components/project_submissions/submissions.scss
Because:
* Adding the tooltip to the flag override its position property.
> Fix: Position of Flag on Mobile

- app/admin/flags.rb
- app/models/user.rb
- spec/models/user_spec.rb
Because:
* This will allow us easily deduce if a flagger has a pattern of flagging submissions for no reason.
This Commit:
* Adds a number of times the flagger has had a dismissed flag column to the admin flag view.
* Adds the flag association to users.
* Adds a dismissed_flag instance method to the user model.
> Chore: Add Flaggers Dismissed Flag Count to Admin Flag View

- app/views/paths/index.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_navbar_modal.html.erb
Because:
* This will make it easier to view paths.
This commit:
* also change "My Courses" to "My Path" to keep the naming consistent.
> Feature: Add All Paths Nav Option

- .rubocop.yml
- config/routes.rb
Now that tracks have been renamed to paths this commit updates the routes file to redirect tracks to paths. This is to ensure anybody still trying to reach tracks doesn't find a missing page.
> Redirect tracks urls to paths

- app/helpers/course_helper.rb
- app/models/user.rb
- app/views/courses/course/_lesson_completion_button.html.erb
- app/views/lessons/_lesson_completion_state.html.erb
- spec/helpers/course_helper_spec.rb
- spec/models/user_spec.rb
Because:
* We had two methods doing the same thing.
This commit:
* Uses the completed?(lesson) method on the user model to choose which button should be displayed.
* Removes the completed_lesson? helper as it was doing the same thing.
* Hard codes the completed lesson icon class in the lesson complete icon on the course page as it will always have this class.
> Chore: Refactor Lesson Completion Buttons

- app/controllers/users_controller.rb
- app/views/paths/show.html.erb
- app/views/users/_skills.html.erb
Because:
* We have moved these to the all paths and path pages.
This Commit:
* Removes the prompt at the bottom of path pages.
* Removes the prompt on the dashboard.
> Chore: Remove Old Switch Path Prompts

- app/controllers/lesson_completions_controller.rb
- app/views/lesson_completions/create.js.erb
- app/views/lessons/_lesson_completion_state.html.erb
- db/schema.rb
- db/seeds/01_web_dev_101_seeds.rb
- spec/controllers/lesson_completions_controller_spec.rb
Because:
* We currently enroll students on the rails path by default and don't prompt them to consider their path.
This commit:
* Changes the complete button in the last lesson of web dev 101 to "Complete and Choose Path".
* Refactors the lesson completions controller to allow redirects and simplify its implementation.
> Feature: Prompt Student to Choose Path at the End of Web Dev 101

- app.json
Because:
* This is needed to create and seed the database.
> Chore: Add Post Deploy Script to Review Apps

- Procfile
- app.json
- bin/heroku_release
Because:
* It was trying to create a new db with db:migrate.
This commit:
* Adds a bash script for choosing to run db:migrate or db:schema during herokus release phase.
* Adds a formation config option to the app.json file used by heroku.
> Chore: Run db:schema:load in review apps during the release phase

- app.json
Because:
* We wrap our web process in this in the procfile, so the app will not run without it.
This commit:
* Adds the jemloc buildpack to app.json.
* Pulls in lesson content after the review app is deployed.
> Chore: Add Jemloc Buildpack

- app/controllers/api/points_controller.rb
Because:
* We should only return what we need.
> Chore: Allow Points Response to be Limited and Offset

- app/assets/stylesheets/components/card.scss
- app/helpers/paths_helper.rb
- app/models/path.rb
- app/models/path_prerequisite.rb
- app/views/paths/index.html.erb
- db/migrate/20201027214814_add_path_prerequisite_table.rb
- db/schema.rb
- db/seeds/paths/front_end.rb
- db/seeds/paths/full_stack_javascript.rb
- db/seeds/paths/full_stack_rails.rb
- spec/factories/path_prerequisites.rb
- spec/factories/paths.rb
- spec/helpers/paths_helper_spec.rb
- spec/models/path_prerequisite_spec.rb
- spec/models/path_spec.rb
Because:
* This will inform students that they are expected to complete the foundations path first.
This Commit:
* Adds a path_prerequisites table.
* displays the path prerequisites on path cards as links.
> Feature: Display Path Prerequisites on Path Card

- app/models/vote.rb
- app/services/notifications/daily_summary.rb
- spec/services/notifications/daily_summary_spec.rb
This code change:
- Adds a Vote model class we can use for things like the created_at scope which
- Was added to the daily report.
Additionally, repetitive "today"'s were removed at @KevinMulhern 's request.
> Adding daily reporting for project submission votes.

- db/seeds/06_javascript_course_seeds.rb
Resolving Issue #1480
- Swapped order of React and Async/API lessons so Async/API now comes before React in the Javascript course.
> Swapped order of React and Async lessons

- app/javascript/components/project-submissions/components/submission.js
- app/javascript/components/project-submissions/components/submissions-list.js
- package.json
- yarn.lock
Because:
* At present the submissions stay in the same position after being liked.
This commit:
* Reorders the submissions based on likes dynamically.
* Adds react-flip-move library to animate the submission items when they reorder.
> Feature: Reorder Submissions When Liked

- spec/factories_spec.rb
Because:
* Factories can become invalid when validations and the schema change.
> Chore: Add a FactoryBot Linter Test

- db/seeds/07_getting_hired_course_seeds.rb
Because:
The removal of this lesson warrants the removal of its seed.
see https://github.com/TheOdinProject/curriculum/pull/21922
This commit:
- Removes the seed information for the lesson.
> Remove "Alternate Paths to Web Dev Job" lesson seed

- app/helpers/lessons_helper.rb
- app/javascript/components/project-submissions/components/like.js
- app/javascript/components/project-submissions/components/submissions-list.js
- app/javascript/components/project-submissions/containers/project-submissions-container.js
- app/javascript/components/project-submissions/index.jsx
- app/queries/lesson_project_submissions_query.rb
- app/views/lessons/project_submissions/index.html.erb
- app/views/lessons/show.html.erb
- spec/queries/lesson_project_submissions_query_spec.rb
This code: 
- Adds liking functionality to the current user's submission, allowing them to like their own project submission.
- Removes prepending the list of submissions with the user's submission.
- Renders the user's submission separate from the rest so that user submission renders at the top and isn't duped when visibility is changed.
> Fixing dupe submission bug and adding likes to current_user's submission.

- app/helpers/lessons_helper.rb
- app/views/lessons/project_submissions/index.html.erb
- app/views/lessons/show.html.erb
- spec/helpers/lessons_helper_spec.rb
Because:
* It was finding the first submission associated to the user and displaying that submission in all submission lists.
This commit:
* Scopes the submission to the user and lesson.
> Fix: User Submission Not Scoped to Lesson

- db/seeds/08_node_js_course_seeds.rb
This code:
- Adds the NodeJS conclusion lesson to the seeds file. The lesson had been added to the curriculum repo but not to the site.
Resolves issue #1516
> Adding conclusion lesson to NodeJS seeds.

- app/javascript/components/project-submissions/components/submissions-list.js
- app/javascript/components/project-submissions/containers/user-project-submissions-container.js
This code:
- Fixes the bug where the modal would not close. The JS would bomb when the user container wasn't passing down a method for toggling likes.
- Tackles a bug where the dashboard submission list would start duplicating submissions client-side whenever Update's occurred. This is done by rendering SubmissionList differently if on the user dashboard and being more meticulous with updating submissions in the update method.
> Fixing user dashboard modal and submission list bugs.

- app/assets/stylesheets/components/lesson-preview.scss
- app/controllers/lessons/previews_controller.rb
- app/javascript/components/lesson-preview/components/lesson-content-input.jsx
- app/javascript/components/lesson-preview/components/lesson-content-preview.jsx
- app/javascript/components/lesson-preview/components/lesson-preview.jsx
- app/javascript/components/lesson-preview/index.jsx
- app/views/lessons/previews/show.html.erb
- config/routes.rb
- package.json
- yarn.lock
Because:
* We need an easy way to preview lesson markdown with the site styles applied.
This commit:
* Adds a lesson preview page which renders a react component that allows users to enter lesson content and preview it in a tab. Like Github comments.
> Feature: Lesson Preview

- .slugignore
Because heroku filters out devDependency files in production
This commit ensures any .test.js file is ignored by heroku as the
imported modules aren't available in production
> Fix: Add slugignore file to filter out any test files for production

- .circleci/config.yml
- package.json
Because:
* We recently added some react tests for the submissions feature.
This commit:
* Install yarn and cache yarn bundle on CI.
* Run RTL tests on CI
* Fix issue where it was seeding the database on CI.
> Chore: Run JS Tests on CI

- app/assets/stylesheets/components/paths.scss
quickfix to prevent gnarly overflows on low-res screens
> add media-query for all-paths page

- app/javascript/components/project-submissions/containers/project-submissions-container.js
Because:
* It is no longer a beta feature.
> Feature: Remove Project Submissions Beta Message

- .slugignore
Because:
* We changed the react test files to `.jsx` files.
This commit:
* Ignores any js tests that have the jsx extention when deploying to heroku.
> Fix: Not ignoring React Tests when Building

- db/seeds/06_javascript_course_seeds.rb
Hi there, thanks for The Odin Project - really cool! I think I'll be contributing more often :)
Not sure if I'm doing this correctly, but I wanted to fix the casing of JavaScript in the banner (and found a few more occurrences where it was incorrect):
I first looked in [TheOdinProject/curriculum](https://github.com/TheOdinProject/curriculum), but that doesn't seem to be the correct place for it... somewhat confusing, where to find the information here.
> Fix casing of JavaScript

- app/javascript/components/project-submissions/components/submissions-list.jsx
Because:
Currently the `submissions-list` sorted in decreasing order by number of likes. The description of the submissions-list indicates that they are the "most recent submissions"
This commit:
- Fixes the verbiage to be accurate.
- Updates the spacing to meet the current ESLint configuration.
> fix: project submissions list descriptor

- public/manifest.json
Adds the Name / Short name to the manifest.json file in order for the PWA icon to display a name
For issue: #1596
> Feature: add name / short_name for PWA

- config/puma.rb
Because:
* The app will use less memory: https://github.com/puma/puma#clustered-mode
resolves: https://github.com/TheOdinProject/theodinproject/issues/1678
> Chore: Enable preload_app in Puma Config

- app/javascript/components/project-submissions/components/create-form.jsx
- app/javascript/components/project-submissions/components/flag-form.jsx
Added missing whitespace between paragraph text and login anchor
to sign in modals on create-form.jsx and flag-form.jsx
Issue #1667
> Add whitespace on sign in modal

- config/puma.rb
Because:
* We were using an older configuration.
This commit:
* Changes the puma config to what Heroku currently recommends: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#adding-puma-to-your-application
> Chore: Modern Puma Config

- app.json
Because:
* We recently added a background worker for handling background jobs.
This commit:
* Adds a worker process to the review app formation.
* Adds a redis addon for the queue.
> Fix: Review App's need Worker Configuration

- db/seeds/08_node_js_course_seeds.rb
This PR is because I have been noticing people in discord frequently questioning why the JS path has no Database section. The Node card description is lacking compared to the rails one. To remedy this I made the Node card more enticing and added mention of MongoDB so when people are browsing the overviews of both paths when deciding they see mention of databases on the Node path as well ass updating the "Express" section to "Express & MongoDB" so it is clear where Databases are introduced.
> Updated Node.js card and Express card title to include MongoDB

- db/seeds.rb
Because:
* Rails 6.1 depreciated this method.
This commit:
* Use `update` in place of `update_attributes`
> Fix: Seeds File using Depreciated Method update_attributes

- app/controllers/registrations_controller.rb
- app/jobs/mailing_list_job.rb
- spec/jobs/mailing_list_job_spec.rb
Because:
* We should be making api calls to mailchimp asynchronously.
This commit:
* Adds a mailing list job and moves the MailchimpSubscription service into it.
> Chore: Move Mailing List Signup into a Job.

- config/initializers/friendly_id.rb
Added friendly finders and custom should_generate_new_friendly_id?
method to friendly_id initializer to resolve bug where slug would
not update properly when a path, course, or lesson title was
changed in the rails console.
Issue #1710
> Update slug when resource title is changed

- config/initializers/friendly_id.rb
Because:
* Circle didn't run and warn us about this in the PR it was introduced in.
> Fix: Friendly Id Initializer Linting

- app/assets/stylesheets/components/navbar.scss
- app/assets/stylesheets/components/odin-dropdown-menu.scss
- app/assets/stylesheets/utilities.scss
- app/javascript/packs/application.js
- app/javascript/src/js/navbar.js
- app/javascript/src/js/odinDropDownMenu.js
- app/views/shared/_navbar.html.erb
- app/views/shared/_navbar_modal.html.erb
- app/views/shared/_user_dropdown.html.erb
Because:
* It was covering half the avatar and looking a bit dated.
This commit:
* Fixes the alignment issues with the avatar and dropdown menu.
* Updates the styling of the dropdown to be more consistent with our cards.
* Use our own JS for the dropdown instead of the bootstrap provided JS.
---
Before:
After:
> Fix: Nav Bar User Dropdown Styling Issues

- app/views/lessons/_lesson_buttons.html.erb
- app/views/sitemap/index.xml.builder
- db/migrate/20210305002818_remove_title_url.rb
- db/schema.rb
- db/seeds/01_foundations_seeds.rb
- db/seeds/02_ruby_course_seeds.rb
- db/seeds/03_database_course_seeds.rb
- db/seeds/04_rails_course_seeds.rb
- db/seeds/05_html_css_course_seeds.rb
- db/seeds/06_javascript_course_seeds.rb
- db/seeds/07_getting_hired_course_seeds.rb
- db/seeds/08_node_js_course_seeds.rb
- spec/factories/courses.rb
- spec/factories/sections.rb
Because:
* We don't need to be storing this attribute as rails route helpers will generate urls using the title for us.
This commit:
* Removes the title_url attribute from the lessons, sections and courses tables.
* Removes setting the title_url in the seeds files.
* Updates the few instances we were using title_url to use rails route helpers instead.
> Chore: Remove Title Url

- app/services/lesson_content_importer.rb
- db/migrate/20210306162015_remove_repo_column_from_lessons.rb
- db/schema.rb
- db/seeds/01_foundations_seeds.rb
- db/seeds/02_ruby_course_seeds.rb
- db/seeds/03_database_course_seeds.rb
- db/seeds/04_rails_course_seeds.rb
- db/seeds/05_html_css_course_seeds.rb
- db/seeds/06_javascript_course_seeds.rb
- db/seeds/07_getting_hired_course_seeds.rb
- db/seeds/08_node_js_course_seeds.rb
- spec/factories/lessons.rb
- spec/services/lesson_content_importer_spec.rb
- spec/tasks/curriculum_spec.rb
Because:
* In the past we had the curriculum split up into different repos "javascript_course", "ruby_course" etc. We have since moved to a single repository so the repo column on every lesson is now redundant.
This Commit:
* Updates lesson content importer service to use "curriculum" as the repo by default.
* Removes the repo attribute from all lessons in the seeds files.
> Chore: Remove Repo Column From Lessons Table

- app/assets/stylesheets/components/lesson/_navigation.scss
- app/assets/stylesheets/components/lesson/lesson_content.scss
Because:
* There was a large space between the end of the lesson header and lesson content causing the top of the nav and content to be out of alignment.
This commit:
* Removes the top margin from the first lesson content heading to get rid of the redundant spacing and fix most of the alignment issue.
* Adds a little bit of padding to the top of the lesson nav wrapper so aligns better with the first heading in the lesson content.
---
Before: 
After:
> Fix: Lesson Nav and Content Alignment

- Procfile.dev
- config/puma_development.rb
Because:
* We should use the same app server in all environments.
This commit:
* Switches from using the rails default server to puma in development
* Adds a puma_development.rb config file as we don't need to use the production config in development.
> Chore: Use Puma in Development

- app/models/course.rb
- app/models/lesson.rb
- app/models/path.rb
Because:
* It will allow external links that contain an outdated url path for a lesson, course or path to still work as expected.
> Chore: Use Friendly ID Slug History.

- app/models/lesson.rb
- db/schema.rb
- spec/models/lesson_spec.rb
Because:
* Deleting a lesson loads all lesson_completions for that lesson into memory to delete them as well.
This commit:
* Adds a foreign key with a delete cascade so the database can handle deleting lesson completions associated with a lesson instead of Ruby.
> Fix: Deleting a Lesson on Production Hangs

- app/validators/url_validator.rb
Because:
* Using the shovel `<<` operator to add an error to an ActiveModel::Errors message array is deprecated.
* A warning was appearing everytime we ran the tests.
> Chore: Fix Url Validator Deprecation Warning

- app/admin/flags.rb
Because:
* We should provide an easy way to view the lesson the flagged submission belongs to.
> Feature: Display a Link to the Lesson on Admin Flags

- app/controllers/lesson_completions_controller.rb
- app/views/courses/course/_lesson_completion_button.html.erb
- app/views/lessons/_lesson_completion_state.html.erb
- db/migrate/20210309225335_denormalize_lesson_completions.rb
- db/schema.rb
Because:
* We will need the course and path ids to map lesson completions to the new lessons that will be created when we stop allowing shared courses between paths in the database. This is needed to allow an interlacing structure of lessons throughout many different courses that we are aiming for.
* These ids can also be used to scope the users completions to courses and paths, which will make it easy and performant to calculate the users progress through a course or path.
This commit:
* Adds lesson_identifier_uuid, course_id and path_id columns to the lesson_completions table.
* Stores these values when new lesson completions are created - older records will be backfilled with data migrations in the next few days.
* Disallow users to mark lessons as completed on paths they are not …
> Chore: Denormalize Lesson Completions Table

- app/jobs/application_job.rb
- app/notifications/flag_notification.rb
- spec/notifications/flag_notification_spec.rb
Because: we need to notify a user when their project submission has been
deleted
This commit: Creates a FlagNotification class that can be used to save
flag specific notifications to the notifications table
The default JobApplication class has also been created as the noticed
gem relies on it.
> Create a FlagNotification class

- Gemfile
- Gemfile.lock
Because:
The url without www is not working right now and we are seeing lots of skylight related logs.
> Fix Naked Domain Not working

- config/database.yml
- docker-compose.yaml
Because:
* It is convention to append the environment name to the db name.
> Chore: Rename Development Database to theodinproject_development

- .circleci/config.yml
Because:
* It would be helpful for the reviewer to see if the seeds file runs without any issues during the CI build.
This commit:
* Runs the seed task in a CI job
* Moves linters into their own jobs.
> Chore: Run Seeds Task During CI

- app/views/courses/course/_lesson_completion_button.html.erb
- app/views/lessons/_lesson_completion_state.html.erb
Because:
* It was using the friendly id and relying on the friendly id finder which seems to be a bit flaky.
This commit:
* Passes the lesson id to the lesson completions controller every-time instead.
> Fix: Lesson Completion Buttons Sometimes Cannot Find The Lesson.

- app/controllers/lessons/project_submissions_controller.rb
- app/views/lessons/show.html.erb
Because:
* It was using the title of the lesson instead of the lessons id to find it, many lessons can have the same title.
> Fix: All Submissions Url

- db/migrate/20210326125315_add_lesson_foreign_key_to_lesson_completions.rb
- db/schema.rb
Because:
* It will ensure lesson completions are properly deleted when a lesson is removed.
> Chore: Add Lessons Foreign Key to Lesson Completions

- Gemfile.lock
Because:
* The mimemagic version we had installed was yanked.
> Fix: Review Apps Not Building

- app.json
- bin/heroku_release
Because:
* We no longer need to manually run the seeds task now that the seeds task correctly updates changed seeds and deletes removed seeds from the db.
This commit:
* Adds running the seeds task to the heroku release phase script.
* Adds running the content import task to the heroku release phase script.
* Removes the post deploy script for review apps as the release script now handles these tasks.
> Chore: Run Seed and Import Lesson Content Tasks After Release

- app/models/lesson.rb
- app/views/static_pages/home.html.erb
- spec/models/lesson_spec.rb
Because:
* Students often ask if the curriculum is up to date.
This commit:
* Adds a link to the latest commits on the curriculum.
* The link has the latest lesson updated_at time stamp as its label.
> Feature: Add Last Updated Link to Home Page

- Gemfile
- Gemfile.lock
- config/initializers/sentry.rb
Because:
* We currently use NewRelic for error tracking but that has been limited and not very accessible.
This commit:
* Adds Sentry to the app.
> Chore: Set Up Sentry

- .rspec
- .rubocop.yml
- app/models/user.rb
- app/services/lesson_duration.rb
- spec/models/ability_spec.rb
- spec/spec_helper.rb
Because:
* We were getting quite a few warnings about adding new cops to our Rubocop.yml file and the warning list grew everytime we bumped Rubocop.
This commit:
* Enables all new cops to get rid of the warnings now and in the future.
> Chore: Remove Warnings

- app/controllers/application_controller.rb
Because:
* Providing details about the users errors are occurring for will help us diagnose the issues quicker.
> Chore: Set Sentry User

- app/javascript/packs/error_tracking.js
- app/views/layouts/_error_tracking.html.erb
- app/views/layouts/application.html.erb
- package.json
- yarn.lock
Because:
* We want to track JS errors in sentry too.
> Chore: Capture JavaScript Exceptions in Sentry

- db/fixtures/paths/foundations/seed.rb
Because:
* The title and description were better suited to the content that was in this section before.
This commit:
* Rename "Tying it all Together Maybe" section to "Conclusion".
* Tighten up description copy and make it clear the purpose of this section is to choose a path.
> Feature: Tidy up Foundations Last Section Copy

- config/routes/old_route_redirects.rb
- spec/requests/old_course_route_redirects_spec.rb
Because:
* We are getting a lot of traffic to these routes from an external source and they currently return the 404 page.
This commit:
* Redirects the old depreciated `/paths/path-name/courses` route to `/paths/path-name` instead.
Resolves: https://github.com/TheOdinProject/theodinproject/issues/1857
> Fix: Broken Path Courses Url Should Redirect to Path Page

- app/assets/stylesheets/components/courses/section_lessons.scss
- app/assets/stylesheets/components/lesson/lesson_button.scss
- app/views/courses/course/_lesson_completion_button.html.erb
Because:
* We should disable these buttons and give visual feedback to show the request is still submitting when they are clicked. This will help users avoid submitting multiple times at once.
This commit:
* Disables the lesson completion button on the path page with a loading spinner when clicked.
Resolves: https://github.com/TheOdinProject/theodinproject/issues/1856
> Feature: Path Lesson Completion Button Submitting State

- app/models/user.rb
- spec/models/user_spec.rb
Because:
* It was setting the users path to foundations on every user update instead of just on create.
This commit:
* Only set the users path to foundations when they register for an account.
> Fix: Switching Paths

- config/initializers/smtp.rb
Because:
- We were getting deprecation warnings when booting the app
This commit:
- Defers the initialization of ActionMailer until after Rails has been fully initialized.
Notes:
- There is a fix for this issue in the Rails repo that has not been shipped yet. When Rails is updated, please revert this change and check if the deprecation warning has been fixed. See #1844 for more information.
Resolves: #1844
> Chore: Fix ActionText::ContentHelper and ActionText::TagHelper Depreciation Warning on Boot

- app/views/lessons/_lesson_completion_button.html.erb
- spec/system/lesson_completion_spec.rb
Because:
* It wasn't running this spec since it didn't have `_spec` postfixed.
This commit:
* Adds _spec to the end of the lesson completions system spec file name.
* Fixes the logged out test for lesson completions.
> Fix: Lesson Complete System Test

- app/views/shared/_navbar.html.erb
Fixed issue where clicking "All Paths" causes the "Community" tab to highlight. #1832 
Attached is a photo of the working fix both logged out and logged in. Below is the rspec test in which two failures related to welcome email job occur. I can only assume this is because I did not set up the mail chimp integration. If these failures are a problem I can go back and look for errors but I was getting these before making changes so I don't believe they will be.
> Clicking AllPaths does not select Community

- app/admin/flags.rb
- app/services/admin/flags/ban_user.rb
- app/services/admin/flags/dismiss.rb
- db/migrate/20210428175951_add_resolved_by_id_to_flags.rb
- db/migrate/20210428222030_add_resolved_by_id_to_flags.rb
- db/schema.rb
- spec/services/admin/flags/ban_user_spec.rb
- spec/services/admin/flags/dismiss_spec.rb
This pull request addresses https://github.com/TheOdinProject/theodinproject/issues/1884
I hope this is an okay way to do it. 
Steps I took to add this feature:
1. Generated the migration AddResolvedByIdToFlags
2. Added `flag.update!(resolved_by_id: flag.flagger.id)` to `call` method of `Admin::Flags::Dismiss`
3. Added `flag.update!(resolved_by_id: flag.flagger.id)` to `call` method of `Admin::Flags::BanUser`
> add ability to track who resolved a flag

- app/assets/stylesheets/components/project_submissions/submissions.scss
The margin was to the left instead of to the right
before:
after:
> Fix: lack of margin on like button

- db/fixtures/paths/full_stack_javascript/seed.rb
- db/fixtures/paths/full_stack_rails/seed.rb
There were a significant amount of questions about the order courses in a path should be taken. This change aims to improve student clarity and outlines that courses in the paths should be taken in the order that they are displayed.
> adds clarifying copy to path descriptions

- app/javascript/packs/error_tracking.js
Because:
* We are seeing quite a few errors from extensions and external scripts reported.
This commit:
* Configures the sentry allowed urls list.
> Chore: Only Report Errors Originating from TheOdinProject

- app/views/shared/_navbar.html.erb
- spec/system/user_login_spec.rb
Because:
- We need end to end test coverage for user login
This commit:
- Adds test for valid sign in with username and password
- Adds test for leaving email and password fields blank
- Adds test for invalid email format
- Adds test for a password which is too short
- Adds test for oauth login with github
- Adds test for oauth login with google
Resolves #1868
> Chore: Add system tests for user login

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Because:
* We should make it easier for contributors to know exactly what information we expect from them when they make issues and pull requests to this repo.
This commit:
* Adds a pull request template.
* Adds a feature request issue template.
* Adds a bug report issue template.
Resolves: https://github.com/TheOdinProject/theodinproject/issues/1886
> Chore: Add Pull Request and Issue Templates

- Gemfile
- Gemfile.lock
- spec/models/lesson_spec.rb
- spec/services/notifications/daily_summary_spec.rb
- spec/support/time_helpers.rb
Because:
* We can replace it with the built in rails time helpers.
This commit:
* Removes the timecop gem.
* Configures rails time helpers for the test suite.
> Chore: Remove Timecop

- Gemfile
- Gemfile.lock
* This used to be required for deploying to Heroku on Rails 4 and below apps, we're currently on Rails 6.
> Chore: Remove rails_12factor gem

- app/assets/stylesheets/paths.scss
- app/controllers/users/paths_controller.rb
- app/views/paths/index.html.erb
- app/views/paths/show.html.erb
- spec/system/select_path_spec.rb
- spec/system/user_dashboard/start_course_spec.rb
Feedback from Ada:
> The wording of "switch" is confusing because once you’re prompted to pick a path, you essentially have not entered into either path yet so maybe the word "select" sounds more direct. "Switch" sounds like the user is already in something (which they are not)
* Replaces the "switch" copy with "select" which works for both cases of when a user has not chosen a path yet or decided to take the other path in the future.
> Feature: "Select" a Path instead of "Switching" to a Path

- app/views/shared/_course_badge.html.erb
- spec/system/course_progress_badge_spec.rb
* we need end to end test coverage for course badge progress.
* Resolves #1953 
* Adds test for a course that has not been started.
* Adds test for a course that is partially complete.
* Adds test for a course that is complete.
> Chore: Add System Tests for Course Badge Progress

- app/helpers/lessons_helper.rb
- app/models/project_submission.rb
* The default scope for returning kept project submissions was causing the flags project submission association to return nil after it is soft deleted.
* Removes the default kept scope from project submissions.
* Adds a discarded_at nil condition to the viewable project submissions scope.
* Uses the viewable scope when finding the users submission for a project.
> Fix: Broken Admin Flag Links For Removed Submissions

- .eslintrc.json
- app/javascript/controllers/index.js
- app/javascript/packs/application.js
- package.json
- yarn.lock
Because:
- Stimulus has been selected for use within the app
This commit:
- Installs the stimulus package and sets up the minimum required files
- Formats stimulus index.js file to follow linting guidelines
resolves #1965
> Add stimulus js

- lib/tasks/data_migrations/game_jam_message.rake
Because:
* We want to notify users that don't visit discord about the game jam.
This commit:
* Creates an admin flash message about the game jam.
> Chore: Notify Users of the Game Jam.

- package.json
- yarn.lock
Because:
* Tailwind requires Postcss 7 to compile.
This commit:
* Reverts TheOdinProject/theodinproject#1991
> Revert "Upgrade: Bump postcss from 7.0.35 to 8.3.0"

- db/fixtures/lessons/javascript_lessons.rb
- db/fixtures/paths/full_stack_javascript/courses/1_javascript.rb
- db/fixtures/paths/full_stack_rails/courses/5_javascript.rb
The Webpack lesson in the JS course needed to be re-ordered in the database. 
- adds the lesson to the "Organizing JS" module and removes it from the "Javascript in the Real World" module
> Changes order of webpack lessons in DB

- app/controllers/api/points_controller.rb
Because:
* It now inherits from application controller and wasnt skipping verify authenticty token.
This comit:
* Skips the authenticity token in the points api.
> Fix: Points Api

- app/models/point.rb
Because:
* `#increment` does not save the record.
This commit:
* Explicitly call save on the the record after its points have been incremented.
> Fix: Points Not Incrementing

- spec/models/point_spec.rb
Because:
* We should ensure the incremented points are persisted in the unit test.
This commit
* Reloads the points object to ensure the incremented point has been persisted.
> Chore: Improve Points Increment Test

- db/fixtures/lessons/html_and_css_lessons.rb
- db/fixtures/paths/full_stack_javascript/courses/2_html_and_css.rb
- db/fixtures/paths/full_stack_rails/courses/4_html_and_css.rb
Related to [issue #21944 in curriculum repo](https://github.com/TheOdinProject/curriculum/issues/21944).
Bootstrap lesson should be removed.
* Removes the bootstrap lesson from the html & css courses.
> Remove bootstrap lesson

- db/fixtures/paths/full_stack_javascript/courses/1_javascript.rb
I've been thinking about TDD and Battleship in the JS curriculum for a few days now, and more specifically how our students are approaching it in light of having just finished the react section.
The Battleship project is fantastic. In terms of its focus on testing and how it teaches the students to use tests to develop an application, it works very well. Using objects and methods to control the game logic, and testing those methods before creating a UI definitely helped me to refine the way I wrote object oriented code and separate logic from view.
However, there is one major flaw with the project, and that's the fact that it comes right after the react section of the course. Simply put, a beginner's understanding and mastery over react does not play well with this method of game logic …
> move testing lesson before react in js curriculum

- db/migrate/20210622162155_add_course_id_to_lessons.rb
- db/schema.rb
- lib/seeds/lesson_seeder.rb
- spec/lib/seeds/course_seeder_spec.rb
- spec/lib/seeds/lesson_seeder_spec.rb
Because:
* This will allow us to move lessons between sections in the same course without duplicating them in the db.
This commit:
* Add a course_id reference column to the lessons table.
* Replace the lesson seeder section_id constraint with course_id so lessons can be moved between sections in a course.
> Chore: Scope Lessons to Courses.

- app/javascript/components/lesson-preview/index.jsx
Because:
https://github.com/TheOdinProject/theodinproject/issues/1652
The code block highlighting does not currently persist on tab-switch when the `content` is the same due to only being triggered by the `convertedContent` state.
This commit:
fixes #1652 
- Removes the `useEffect` previously triggering the code highlighting
- Adds highlighting to Preview tab click handler.
- Adds state to track if the user is on the preview tab (to prevent preview requests being fired by repeatedly clicking on the preview tab)
I wasn't sure how critical the last point really was, but it seemed reasonable to prevent that behavior even if it's abnormal with minimal code added.
> fix: persist md preview code highlight #1652

- .buildcache
- .slugcleanup
- Gemfile
- Gemfile.lock
- app.json
- config/boot.rb
- lib/tasks/heroku.rake
Because:
* It will speed up our build time during deploy.
This commit:
* Adds Bootsnap for quicker boots.
* Adds buildcache that is used with the cache load and save heroku build packs.
> Chore: Cache Asset Compilation Between Builds

- app/controllers/github_webhooks_controller.rb
Because:
* The Github webhooks endpoint was trying to verify a csrf token.
This commit:
* Skips verify_authenticity_token in the Github webhooks endpoint.
> Fix: Automatic Curriculum Content Updates

- app/controllers/api/points_controller.rb
- app/models/point.rb
- spec/factories/points.rb
- spec/models/point_spec.rb
- spec/requests/api/points_spec.rb
* We want to award more points for different bot commands.
* Adds Request specs around the points api
* Changes the create points api to accept a value param.
* Allows the points model to increment by more than 1.
* Limits the increment to 5 at a time to ensure consumers cannot abuse the api.
Resolves: https://github.com/TheOdinProject/theodinproject/issues/2057
> Feature: Allow Points API Consumers to Pass through a Points Value to Increment By

- app/assets/stylesheets/components/lesson/lesson_content.scss
Resolves: https://github.com/TheOdinProject/theodinproject/issues/2017 
Added a blockquote selector to lesson_content.scss. 
Added left border and left padding to blockquote elements
Before:
After:
- [ X] You have verified the tests and linters all pass against your changes?
> Fixed blockquote styling in lesson content - resolves #2017

- app/javascript/components/project-submissions/components/create-form.jsx
- app/javascript/components/project-submissions/components/edit-form.jsx
- app/javascript/components/project-submissions/components/flag-form.jsx
- package.json
- yarn.lock
- There were breaking changes to react-hook-form preventing it from being updated
- Updates `react-hook-form` to version 7.11.0
- Updates `@hookform/resolvers` to version 2.6.1
- Updates edit-form, create-form, and flag-form to use the new versions
Resolves #1848
> Chore: Bump React Hook Form

- app/helpers/application_helper.rb
The 1000 hour time estimate in the FAQ seems to send a message we might not want to send, and causes some students to have bad first experiences on the server
Removes the 1000 hour estimate from our FAQ.
> Remove 1000 hour time estimate from FAQ

- app/assets/stylesheets/components/odin-dropdown-menu.scss
Because:
* If a flash message is on the screen and the user opens the dropdown menu, the flash message will appear on top of it.
This Commit:
* Sets the dropdown menu's background to white instead of using the default transparent value for the background color.
> Fix: Flash Overlapping User Menu.

- db/seeds.rb
- db/seeds/maintainer_users.rb
Because:
* We cannot use Github or Google oauth with the review apps and therefore have to sign up manually when testing which is a pain. Each maintainer can add their name to the names list and it will automatically make an account for them when the review app is building.
* I have also enabled this for development mode.
* This should also provide a nice opportunity for every maintainer to make a commit to the codebase.
This commit:
* set up a maintainer users seeds file and added myself.
> Chore: Create Maintainer Users to be Used with Review App's

- app/models/flag.rb
- app/services/admin/flags/notify_user.rb
- app/services/messages/dead_link.rb
- spec/models/flag_spec.rb
- spec/services/admin/flags/notify_user_spec.rb
- spec/services/messages/dead_link_spec.rb
Because: Admins should be able to resolve a flag for a project
submission with a dead link by notifying the user that they need to
update their submission.
This commit:
- Add notified_user to taken_action enum on the flag model
- Create admin flag service object for notifying users
- Add message class for a dead link
- Add tests for message class
- Add tests for notify_user
> feat: Add service objects for updating the flag to notify user and

- app/views/users/show.html.erb
- [N/A] You have verified the tests and linters all pass against your changes?
- [N/A] You have included automated tests for your changes where applicable?
> Edit My Dashboard text

- app/assets/stylesheets/components/settings/delete_account.scss
- app/controllers/users/progress_controller.rb
- app/javascript/src/js/settings.js
- app/services/users/reset_progress.rb
- app/views/devise/registrations/_danger_zone.html.erb
- app/views/devise/registrations/edit.html.erb
- config/routes.rb
- spec/services/users/reset_progress_spec.rb
- spec/system/user_reset_progress_spec.rb
* Users may want to reset their lesson completions if they restart TOP.
* Adds ResetProgressJob to delete lesson completions and reset path.
* Adds progress controller and route.
* Adds unit and system tests.
* Adds danger_zone partial and adjusts styling.
* Updates test environment config to have sidekiq run immediately.
* Updates settings.js to allow for element without toggler class.
Resolves: #2109 
The User model has the following method:
```
def enroll_in_foundations
default_path = Path.default_path
self.path_id = default_path.id if default_path.present?
end
```
This makes me wonder if Reset Progress Job `#perform` should also check for the existence of the default path.
If you do not like the red border on the Danger Zone, it can be removed. I added it because I felt like it added …
> Feature: User Lesson Completion Reset Progress

- db/fixtures/lessons/database_lessons.rb
- db/fixtures/lessons/javascript_lessons.rb
- db/fixtures/lessons/ruby_lessons.rb
- db/fixtures/lessons/ruby_on_rails_lessons.rb
- db/fixtures/paths/full_stack_javascript/courses/1_javascript.rb
- db/fixtures/paths/full_stack_rails/courses/1_ruby.rb
- db/fixtures/paths/full_stack_rails/courses/2_databases.rb
- db/fixtures/paths/full_stack_rails/courses/3_rails.rb
- db/fixtures/paths/full_stack_rails/courses/5_javascript.rb
Because:
* The project names were inconsistent.
* This made it difficult to parse the project submissions list on dashboard.
* This change makes it easier to navigate to a project quickly when helping someone on Discord.
This Commit:
* Updates titles for all named projects.
* Updates the lesson and course fixtures files.
Additional Info:
I have changed the title of each of the named projects, but left the un-named projects alone. For example, the `Authentication` project is now named `Members Only` because that is the name of the project, but left the unnamed projects like `Sending Confirmation Emails` alone.
> Chore: Updates the title of the named projects

- app/assets/stylesheets/components/faq.scss
Here style applied for `faq-10` but it doesn't need this style as it doesn't have  `ul`. This style is for `faq-9`. So class name `faq-10` updated to `faq-9`. So it will fix `faq-9`'s `ul`'s margin/padding issue. `faq-{id}` where id starts with `0` so `faq-9` refers `10th faq`.
https://www.theodinproject.com/faq
> Update faq.scss faq-10 to faq-9

- babel.config.js
Because:
* It was raising an error on boot locally.
This commit:
* Adds private property plugins to the babel config.
> Fix: Webpack Dev Server

- db/fixtures/paths/foundations/seed.rb
This PR removes the old html/css content from foundations, and removes the `(New Lessons)` tag from the new stuff
Don't merge until we're ready to do that. (give it a week or so)
> remove deprecated front end section

- app/views/paths/index.html.erb
- app/views/paths/show.html.erb
Because:
* These pages didn't have descriptive titles and were using the fallback.
> Chore: Add Descriptive Title Content to Path Show and Index Pages

- app/assets/stylesheets/components/lesson/lesson_content.scss
Because:
* The embeds were didn't have any bottom spacing.
This commit:
* Adds a bottom margin to all embeds.
Resolves: https://github.com/TheOdinProject/theodinproject/issues/2203
> Fix: Spacing Around Codepen Embeds

- db/seeds/test_project_submissions.rb
Because:
* The project submissions were being added to the google homepage project which was removed recently.
This commit:
* Add the test submissions to the recipe project instead.
> Fix: Test Project Submission Seeds

- db/fixtures/lessons/foundation_lessons.rb
Because:
Resolves issue#2209: https://github.com/TheOdinProject/theodinproject/issues/2209
This commit:
- Changed the title "Introduction" of the flexbox section from Foundations lesson to "Introduction to Flexbox".
> Fixed the intro title of flexbox section

- config/initializers/assets.rb
Because:
* It is making our CI runs flaky.
This commit:
* Removes the assets pre-compilation of the application_stylesheet since it is no longer supported and should already be done in the assets/manifest.js file.
> Fix: Seg Fault Error with Sassc Gem

- db/fixtures/lessons/javascript_lessons.rb
- db/fixtures/paths/full_stack_javascript/courses/1_javascript.rb
- db/fixtures/paths/full_stack_rails/courses/5_javascript.rb
As discussed on discord ( https://discord.com/channels/505093832157691914/540903304046182425/893182342011691008 ) the JavaScript `Async` lesson name could be improved for clarity, particularly when there is a later lesson named `Async and Await`
Updated the name of the lesson and it's description in `db/fixtures/lessons/javascript_lessons.rb`:
```rb
'Asynchronous Code' => {
title: 'Asynchronous Code',
description: 'Introduction to asynchronous programming',
```
Updated the lesson fetch functions in the `full_stack_rails` and `full_stack_javascript` course paths.
> Improve JavaScript Async introduction lesson name

- app/controllers/notifications_controller.rb
Because:
* We are seeing some errors in sentry for notifications being called on a nil current user.
This commit:
* Ensure the user is signed in before we call these controller actions.
> Fix: Notifications Controller

- app/services/next_lesson.rb
- spec/services/next_lesson_spec.rb
Because:
* When taking lessons out of order, the resume course button was not taking into account if
the next lesson after the users most recently completed lesson had already been completed or not.
This commit:
* Only return incomplete lessons from the next lesson service.
* General refactor of the next lesson service and specs for improved code quality and test coverage.
> Fix: Resume Course Should Start at the Next Incomplete Lesson

- .github/dependabot.yml
Because:
* We are getting a few too many each week, which increases the risk of a bump breaking something.
This commit:
* Reduces Ruby gem bumps to 5 a week
* Reduces JS package bumps to 5 a week
> Chore: Reduce Weekly Dependabot PR's

- app/controllers/application_controller.rb
Because:
* It was sometimes(rarely) storing the course progress json response as the last visited page.
This commit:
* Only allow the lesson page to be stored as the last visited page so log in redirects cannot go anywhere else.
> Fix: After Sign in Redirect

- app/controllers/static_pages_controller.rb
- app/views/shared/_logo.html.erb
- config/routes.rb
- spec/requests/static_pages_spec.rb
Because:
* When I'm signed in to TOP, then I want to be able to access the main homepage, so I can view it.
This commit:
* Removes the dashboard redirect on the homepage for signed in users.
* Changes the root path to be the dashboard for signed in users.
> Feature: Allow Users to Access the Main Homepage when Signed in

- app/views/layouts/application.html.erb
Because:
* I suspect this is whats causing the complete button to sometimes hit the wrong endpoint and cause an ActiveRecord::RecordNotUnique exception.
> Chore: Turn Off Turbolinks Caching

- app/models/lesson_completion.rb
- spec/models/lesson_completion_spec.rb
Because:
* We already have a unique index db constraint for the lesson_id and user_id on the lesson completions and should have a model validation too.
This commit:
* Adds a uniqueness validation to the user_id scoped to the lesson_id on the lesson completion model
> Chore: Add Unique Validation to LessonCompletion Model

- app.json
Because:
* This should reduce the app's memory consumption on Heroku and allow us to add more web processes.
* More details here: https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html
This commit:
* Adds the Jemalloc buildpack to our review apps.
> Chore: Add Jemalloc

- db/fixtures/lessons/foundation_lessons.rb
- db/fixtures/paths/foundations/seed.rb
- DOM manipulation lesson was split into [DOM Manipulation and Events](https://github.com/TheOdinProject/curriculum/pull/23080) and [Revisiting Rock Paper Scissors](https://github.com/TheOdinProject/curriculum/pull/23079)
- Removes the old DOM manipulation lesson
- Adds [DOM Manipulation and Events](https://github.com/TheOdinProject/curriculum/pull/23080) Lesson and [Revisiting Rock Paper Scissors](https://github.com/TheOdinProject/curriculum/pull/23079) Lesson
> Split DOM Manipulation Lesson

- db/seeds/success_stories.rb
Because:
* If an attribute for a story was changes it created a new record for the story and didn't remove the old one.
This commit:
* Use seed fu to create and update stories.
* Clean up any persisted success stories that are no longer in the seeds by deleting them.
> Fix: Success Stories Can Duplicate

- app/controllers/paths_controller.rb
- app/views/paths/show.html.erb
- spec/requests/paths_spec.rb
Because:
* When I'm visiting a path that only has one course, then I want to be redirected to that course instead of the path show page, so I can save myself a click.
This commit:
* Checks if the path has one course. Then redirects to the course page if it does.
* Adds request specs around the redirect.
> Feature: Skip the show path screen when a path only has one course

- app/controllers/project_submissions_controller.rb
- app/models/project_submission.rb
- spec/models/project_submission_spec.rb
Because:
* This error is happening frequently on Sentry and we think there is a race condition.
This commit:
* Uses create_or_find_by! as this will handle RecordNotUnique internally on creation and return the existing record instead.
* Add unique validation to project submissions model so we can funnel this error back to the user instead of returning a 500 response.
> Fix: Unique Constraint Race Conditions

- app/views/static_pages/before_asking.html.erb
- app/views/static_pages/community_rules.html.erb
- app/views/static_pages/dashboard_steps/before_asking.md
- app/views/static_pages/dashboard_steps/community_rules.md
- app/views/static_pages/dashboard_steps/how_to_ask.md
- app/views/static_pages/how_to_ask.html.erb
- config/routes.rb
Because:
* The community material needs to be more accessible.
* It is currently only in Foundations.
This Commit:
* Adds page of tips for users to do before asking others for help.
* Adds page of tips for users to do when asking others for help.
* Adds page of our community rules and guidelines.
To remove the community material out of the Foundations, so that no matter when someone joins Discord, they are required to learn how to ask a question. In addition, by putting our rules on the website, they are open-source and easy for anyone to update.
**After feature is complete, these 2 lessons can be removed from Foundations**
* [Join The Odin Community](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/join-the-odin-community)
* [Asking for …
> Adds static pages for our community material

- app/javascript/components/lesson-preview/components/__tests__/lesson-content-input.test.jsx
- lesson-content-input doesn't have tests
- add tests for lesson-content-input.jsx
> Add Tests for lesson-content-input Component

- Gemfile
Because:
* This message was being displayed when starting the dev server:
DEPRECATION WARNING: This manually engine loading is deprecated and will be removed in v3.0.0. Remove `require "view_component/engine"`
> Chore: Fix View Component Engine Deprecation Warning

- app/controllers/lessons/project_submissions_controller.rb
- app/controllers/lessons_controller.rb
- app/controllers/project_submissions_controller.rb
- app/helpers/lessons_helper.rb
- app/javascript/components/project-submissions/components/__tests__/submission-title.test.jsx
- app/javascript/components/project-submissions/components/submission-title.jsx
- app/models/project_submission.rb
- app/queries/lesson_project_submissions_query.rb
- app/serializers/project_submission_serializer.rb
- app/services/admin/flags/ban_user.rb
- app/views/lessons/project_submissions/index.html.erb
- app/views/lessons/show.html.erb
- db/migrate/20211229150146_remove_banned_from_project_submission.rb
- db/schema.rb
- spec/helpers/lessons_helper_spec.rb
- spec/models/project_submission_spec.rb
- spec/queries/lesson_project_submissions_query_spec.rb
- spec/serializers/project_submission_serializer_spec.rb
- spec/services/admin/flags/ban_user_spec.rb
- spec/system/lesson_project_submissions/add_submission_spec.rb
Because:
* We were only looking for the users public submissions when fetching the users submission for a lesson. When the submission was private it was treated like the user had not submitted a project for that lesson. This made the add project button appear, allowing users to add another project which caused a not unique exception on the project submissions table.
This commit:
* Fetches all of the users submissions including the private submissions when finding a submission for a lesson.
* Splits viewable scope into public_only and not_admin_removed scopes so we can use public_only on the submissions not belonging to the current user and not_admin_banned on both the users submission and all the rest - allowing more granular control of what we display.
* Refactor to use the …
> Fix: Marking a Submission as Private Allows Users to Add Another Submission

- spec/system/admin/admin_flashes_spec.rb
Because:
* The date used in the expires at date selector was hard coded to 1/1/2022.
This commit:
* Ensures the date is dynamic in the spec.
> Fix: Failing Admin Flash System Spec

- app/assets/stylesheets/components/about/about.scss
- app/assets/stylesheets/components/about/overview/odin_stat.scss
- app/views/static_pages/about.html.erb
- app/views/static_pages/about/_overview.html.erb
Will update the [about page](https://www.theodinproject.com/about) of the website
1. Fix punctuation in contact details section. Remove styling of "send us an email" link to be more consistent with the rest of the website
2. Github logo in overview now links to [theodinproject](https://www.github.com/theodinproject) on github
3. Update contributor count from "1500" to "5000+", since curriculum repo has 5000+ contributors
4. Update these stats cards to have "text-align: center;" irrespective of screen size
5. Too much white space here doesn't look good. Add fluff under "Origin of The Odin Project"
> Update about page

- app/assets/stylesheets/components/settings/delete_account.scss
Danger zone links have full width across the card, making them clickable throughout. Desktop users can get feedback that links are clickable throughout the width because of the hover effect on cursor and links. Not obvious for mobile users.
Set danger zone links' `width` property to `fit-content`
> Change danger zone links width

- db/fixtures/paths/full_stack_rails/seed.rb
Add 'using Ruby on Rails' at the end of the description
Reason: 
- To bring parity between Fullstack JS and Fullstack RoR path descriptions. Fullstack JS path description ends with "using JavaScript and NodeJs"
> Update ruby on rails path description

- app/assets/stylesheets/components/progress_circle.scss
Because:
* The course badge was positioned a little wrong for mobile.
> Fix: Broken Course Badge on Mobile

- app/assets/stylesheets/components/lesson/lesson_content.scss
- app/views/courses/course/_banner.html.erb
- app/views/courses/index.html.erb
- app/views/paths/index.html.erb
- app/views/paths/show.html.erb
Because:
* We enabled the TW base directive which resets some heading and list styles.
This commit:
* Re-centers some headings.
* Ensure ol elements use the decimal list style within lesson content.
> Fix: Bugs Caused by Enabling Tailwind Base Directive

- app/assets/stylesheets/components/lesson-preview.scss
- app/assets/stylesheets/components/lesson/lesson_preview.scss
- app/views/lessons/previews/show.html.erb
- The heading of the page is small:
- Fixes the page heading
- [A recent pr](https://github.com/TheOdinProject/theodinproject/pull/2503) created a lesson_preview.scss file. This commit merges the old lesson-preview.scss into the new file
> Fix: lesson preview page styles

- app/javascript/src/js/lessons.js
Because:
* The heading content was including carriage returns, this prevented the common headings from being found.
This commit:
* Trim any carriage returns from the heading content when checking if it's a common heading.
> Fix: Lesson Side Navigation on Safari

- app/views/devise/registrations/edit.html.erb
- app/views/static_pages/about.html.erb
- app/views/static_pages/contributing.html.erb
- app/views/static_pages/faq.html.erb
- app/views/static_pages/success_stories.html.erb
- Headings don't align in center when screen width reduced
- Add mx-auto class to affected headings
> Fix: headings don't align in center when screen width reduced

- app/javascript/components/project-submissions/components/__tests__/create-form.test.jsx
- app/javascript/components/project-submissions/components/__tests__/flag-form.test.jsx
- app/javascript/components/project-submissions/components/create-form.jsx
- app/javascript/components/project-submissions/components/edit-form.jsx
- app/javascript/components/project-submissions/components/flag-form.jsx
- app/javascript/layouts/typography.css
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/lessons/previews/show.html.erb
- app/views/paths/index.html.erb
- app/views/paths/show.html.erb
- app/views/static_pages/about.html.erb
- app/views/static_pages/contributing.html.erb
- app/views/static_pages/faq.html.erb
- app/views/static_pages/style_guide.html.erb
- app/views/static_pages/success_stories.html.erb
- app/views/users/show.html.erb
Because:
* The submission headings were not the correct size.
This commit:
* Adds page-heading-title class to the submission modal headings.
* Adds mx-auto to page-heading-title since it is needed for all the headings with this class applied.
* Removes a couple of guard clauses for checking if a user is signed in from the create and flag submission modals since the submission app will only render if a user is signed in now.
> Fix: Submission Headings

- app/assets/stylesheets/components/lesson/lesson_content.scss
reported in discord... ordered lists did not have the margin-bottom that unordered lists have, which was causing some strange spacing issues.
> add proper spacing to ordered lists

- app/views/shared/_off_canvas_menu.html.erb
Because:
* We were using an image of the logo in the mobile nav instead.
> Feature: Use Logo Component in Mobile Off Canvas Menu

- app/assets/stylesheets/dark-mode.css
Because:
* It was using the bg accent dark colour which did not blend correctly with the navbar.
This commit:
* Change the hero section to use the main dark mode background colour instead of the accent colour.
> Fix: Home Page Hero Section in Dark Mode

- tailwind.config.js
Because:
* Tailwind does not check within view component objects for classes to ignore during the purge.
This commit:
* Adds the view component ruby files to the paths Tailwind should inspect before purging unused classes.
> Fix: Tailwind Logo Text Classes being Purged

- app/components/user/profile_dropdown_component.html.erb
Because:
* When flash messages are present and the user opens their profile dropdown, the flash message will overlay the dropdown.
This commit:
* Increases the z-index of the profile dropdown menu.
> Fix: Profile dropdown hidden behind flash messages

- db/fixtures/paths/full_stack_rails/courses/ruby.rb
My original motivation for this was just to fix the capitalisation of
Git, but I noticed and fixed the 'for for' typo while I was here,
and figured the title could be slightly more descriptive too
There were grammar errors
Fixes capitalisation, removes an extra word and makes the title more descriptive
- [ x] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide)?
- [ x] You have verified the tests and linters all pass against your changes?
- [ x] You have included automated tests for your changes where applicable?
> Fix grammar in Ruby Git section

- app/views/devise/registrations/_form.html.erb
Because:
* The user should have their cursor automatically focused on the first input for ease of use.
This commit:
* Adds an autofocus attribute to the username text field on the sign up form.
> Feature: Autofocus on the  user name field when visiting sign up page

- app/controllers/lessons/installation_lessons_controller.rb
- app/models/lesson.rb
- app/views/lessons/installation_lessons/index.html.erb
- config/routes.rb
- db/fixtures/lessons/foundation_lessons.rb
- db/migrate/20220129182526_add_installation_lesson_column_to_lessons.rb
- db/schema.rb
- lib/seeds/lesson_seeder.rb
- spec/models/lesson_spec.rb
Because:
* We want to create an appendix of installation lessons.
This commit:
* Adds installation_lessons column to the lessons table.
* Adds scope to fetch all lessons marked as installation lessons.
* Adds route, controller and index view boilerplate.
* Marks a couple of lessons in foundations as installation_lessons to test everything is hooked up correctly.
Resolves: https://github.com/TheOdinProject/theodinproject/issues/2580#issue-1118301881
> Feature: Allow lessons to be marked as installation lessons

- app/models/project_submission.rb
Because:
* This validation only needs to run when the live preview is present.
This commit:
* Add guard clause to validation to return if the live preview is blank.
> Chore: Only validate live preview is allowed if it is present

- db/fixtures/lessons/html_and_css_lessons.rb
Resolves #2600 
- Added `accepts_submission` and  `has_live_preview` booleans in the lessons within the db directory.
- The booleans were added to 3 projects, Sign-up Form and Admin Dashboard within the intermediate section and Personal Portfolio within the advanced section.
- How the project pages looked before:
- How the project pages looks with this PR:
> Added missing project submissions in intermediate and advanced HTML/CSS

- app/javascript/components/project-submissions/components/__tests__/submissions-list.test.jsx
- app/javascript/components/project-submissions/components/submissions-list.jsx
- `submissions-list.jsx` component renders this message: "No Submissions yet, be the first!" even when there are no `submissions` but there exists a `userSubmission`
- have the `hasSubmissions` variable inside the component account for the `userSubmission`
- add a test case to verify the expected behavior
> Fix: project submissions renders 'no submissions' message when the current user's submission is the only submission

- app/assets/stylesheets/components/home/curriculum_details.scss
- app/assets/stylesheets/dark-mode.css
Resolves Issue #2343 
Adds box-shadow CSS for the .curriculum-details-tile class on hover. Screenshot examples are documented in the issue of both light and dark mode versions.
> Adds hover effect to course tiles on home page.

- spec/components/user/avatar_component_spec.rb
The user_avatar component spec tests were trying to look up, in the asset pipeline, the dummy 'avatar.png' used in the test
- Makes the user avatar name in the test a full url to illustrate where the avatar is expected to come from.
- Changes the test from have_css to have_selector as it is an element being matched and not any css
Closes #2574
> Skip the pipeline when rendering the user avatar

- app/views/layouts/application.html.erb
Because:
* Some users are reporting the site is unstyled when opening it in a new browser session.
This commit:
* Load fonts first.
* Load dark mode after the asset pipeline and tailwind.
* Defer loading JS until the page is parsed in the browser.
> Fix: CSS sometimes not loading

- db/fixtures/lessons/javascript_lessons.rb
- db/fixtures/paths/full_stack_javascript/courses/javascript.rb
- db/fixtures/paths/full_stack_rails/courses/javascript.rb
It's has been decided that the rails backend lesson needs to be split into two lessons and displayed depending on the path.
Relevant PR: https://github.com/TheOdinProject/curriculum/pull/23607
- updates the seed files to facilitate the splitting
- updates section description of 'JavaScript and the Backend' section
Do not merge until the curriculum changes are merged through this PR: https://github.com/TheOdinProject/curriculum/pull/23607
> Split rails backend lesson to serve them depending on the path

- app/controllers/themes_controller.rb
Because:
* We were storing the users preferred theme in a session cookie.
This commit:
* Use a permanent cookie (20-year expiry) which will persist between browser sessions.
> Fix: Losing Preferred Theme Starting a New Browser Session

- Gemfile
- Gemfile.lock
- config.reek
> Chore: Set Gems to Minor Versions

- app/helpers/application_helper.rb
<hr>
Because:
* These course links on the …
> Fix: Broken Course Links on Homepage

- app/assets/stylesheets/components/lesson/lesson_content.scss
> Fix: Update list styling in lessons

- app/views/static_pages/community_moderation.html.erb
- app/views/static_pages/community_rules.html.erb
- app/views/static_pages/dashboard_steps/_github_link.html.erb
- app/views/static_pages/dashboard_steps/moderation_matrix.md
- app/views/static_pages/how_to_ask.html.erb
- config/routes.rb
<hr>
With the implementation of the moderation matrix, we do not currently have it on our website and we need it.
In addition, it has been suggested that these files are hard to find, since they …
> Feature: Add Moderation matrix static page

- package.json
- yarn.lock
Problem:
https://github.com/TheOdinProject/theodinproject/issues/2717
Due to a bug that was introduced into the `react-tabs` dependency. 
This commit:
- Downgrades React-Tabs, such that the Lesson Previewer works as intended.
> downgrade react-tabs

- app/assets/stylesheets/components/lesson/lesson_content.scss
> Feature: improve image sizes in lessons

- app/assets/stylesheets/dark-mode.css
I propose this as a fix to the Thinkful icons, because right now, they're black in dark mode, making them difficult to see. So this is a quick fix making them white in dark mode.
Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently …
> Fix: Change SVG advert icons from Black to White in Dark Mode

- package.json
- yarn.lock
<hr>
Because:
* We have been seeing some …
> Fix: Stimulus in Older Browsers

- app/admin/announcements.rb
- app/models/announcement.rb
- app/views/shared/_announcement.html.erb
- db/migrate/20220414212627_rename_announcements_expires_column.rb
- db/schema.rb
- spec/factories/announcements.rb
- spec/models/announcement_spec.rb
- spec/system/admin/announcements_spec.rb
<hr>
Because:
* Rails conventions.
This …
> Chore: Rename announcements expires column to expires_at

- .circleci/config.yml
-   [x] The title of this PR follows the `keyword: brief description of change` format
<hr>
These images are no longer supported and will not be receiving security updates
**2. This PR:**
Updates the deprecated images
**3. Additional Information:**
See this [blog post](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) for more information about the deprecation.
There is no longer a ram option for the postgres image. I opted to go for the most recent version but can …
> Chore: Update deprecated circleci docker images

- db/fixtures/lessons/javascript_lessons.rb
Teensy typo was causing curriculum import task to fail for Battleship content.
cc @01zulfi
> Fix: Correct typo in lesson seed that broke github import

- .github/workflows/deploy.yml
Because
* [Heroku's GitHub integration has been disabled until further notice](https://status.heroku.com/incidents/2413).
This commit:
* Trigger Heroku deploy Github action when push to main event happens.
Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later …
> Chore: Use Github Action to Deploy

- bin/dev
- bin/setup
- bin/test
- bin/update
- bin/yarn
-   [x] The title of this PR follows the `keyword: brief description of change` format
<hr>
It provides several optional but convenient shortcuts that streamline several common workflows
**2. This PR:**
* Regenerate default rails binstubs
* Tweak setup and update scripts to use yarn and run curriculum import task
* Add foreman convenience stub (copied verbatim from Rails 7 default)
* Add script to run all linting and test tasks
**3. Additional Information:**
If people like this I think it …
> Chore: Update and improve bin scripts

- app/javascript/layouts/buttons.css
- app/views/shared/_omniauth_buttons.html.erb
Because:
* The OAuth buttons had their classes applied by interpolating the OAuth provider. This was causing purge CSS to not see those classes being used and removing them during the asset compilation phase during deploys.
This commit:
* Explicitly define the OAuth buttons instead of rendering them in a loop and interpolating the provider.
- `Chore` - changes that have no user-facing value, refactors, …
> Fix: OAuth Buttons Have no Styling

- app/components/progress_badge_component.html.erb
<hr>
Because:
* Safari is miscalculating …
> Fix: Progress Cirlce Misaligned When Zoomed out on Safari

- .gitignore
Because:
* Puma needs the tmp/pids directory to run.
This commit:
* Removes tmp/pids from gitignore.
-   [x] I have verified all tests and linters pass against my changes, …
> Chore: Keep Tmp Pids Directory

- .gitignore
- spec/rails_helper.rb
Because:
* It allows us to use the handy `--only-failures` feature of Rspec
Credit to the book 'Effective Testing with Rspec 3' for the idea
Usage: After updating, run specs at least once. You can now pass `--only-failures` or `--next-failure` to only run failed specs from the last run. `--next-failure` will bail after hitting one failure whereas `--only-failures` will run all previously failed specs
```
bundle exec rspec --only-failures
bin/rails spec:jobs --next-failure
```
> Chore: Update Rspec config with example persistence

- db/migrate/20220618032614_add_null_constraint_to_course_badge_uri.rb
- db/schema.rb
- spec/lib/seeds/course_seeder_spec.rb
- spec/lib/seeds/path_seeder_spec.rb
Because:
* Originally done in PR #2889, but need to stagger to avoid
a chicken/egg problem when changing the null constraint
This commit:
* Add a null constraint now all courses in prod have a non null value
Follow up from #2889 / #2883
> Chore: Add null constraint to course badge_uri field

- Gemfile.lock
- babel.config.js
- package.json
- yarn.lock
Because:
* We have been experiencing some odd bugs with webpacker.
This commit:
* Bring babel config inline with more recent rails configs.
* Explicitly define webpacker and webpack cli dependencies in package.json.
* Update to the latest version of Webpacker.
Complete the following checkbox ONLY IF …
> Chore: Update Webpacker Config to be Inline with Recent Rails Defaults

- app/admin/announcements.rb
- app/models/announcement.rb
- app/models/user.rb
- db/migrate/20220621121447_add_created_by_to_announcements.rb
- db/schema.rb
- spec/factories/announcements.rb
Closes #2993 
**2. This PR:**
* `Announcment` now `belongs_to` `user`
* `Announcement` admin form has hidden field to track `user_id`
* Add index view to active admin with `Created by` column + sorting
**3. Additional Information:**
First time working with Active Admin, fairly annoying :laughing: 
If this approach is ok, I can add a bit of extra polish - adding a user field to the search filter and fixing up the naming conventions (`Created By` wants to default to `User` due to how associations are set up, and manually configuring is somewhat tedious.
**Todo**
**Bonus**
> Feature: Store Announcement Creator

- db/migrate/20220706080835_add_null_constraint_to_path_badge_uri.rb
- db/schema.rb
- spec/lib/seeds/path_seeder_spec.rb
Because:
* Paths should always have a badge. Follow up to #3053
> Chore: Add null constraint to path badge uri (#3054)

- app/javascript/packs/error_tracking.js
**Because:**
* The bug reduces our ability to see real errors
* Implements one of the fixes suggested here https://github.com/getsentry/sentry-javascript/issues/5179
**Notes:**
* Unsure how to thoroughly test this aside from pushing it and seeing what happens, but open to ideas
* Should probably revisit once an official fix is found
> Fix: Temporary workaround for excessive JS errors in Sentry (#3048)

- app/views/courses/_course.html.erb
Because:
* It was centered under the course title instead of being left aligned.
This commit:
* Left aligns the lesson count on medium and above screen sizes.
-   [x] I …
> Fix: Course Card Lessons Count Alignment

- app/views/shared/_navbar.html.erb
- config/routes.rb
Because:
* We set `/` as the dashboard when authenticated which makes it difficult to accurately tell the difference between homepage and dashboard page visits on analytics.
This commit:
* Authenticated root redirects to the /dashboard path instead of setting root as the dashboard.
* Move the dashboard nav link to the first position in the nav when logged in to promote its importance.
- `Chore` - …
> Feature: Use /Dashbord as the Root URL When Authenticated

- app/components/paths/view_button_component.html.erb
- app/views/paths/index.html.erb
Because:
* A few visual and structural tweaks.
This commit:
* Display action buttons in header of foundations path card when on medium screen size or above.
* Display action buttons in the footer of the foundations path card when on smaller screen sizes.
* Remove the fixed height from path card body and ensure the cards are always the same height using flex-grow.
- `Chore` - changes that have no …
> Chore: All Paths Page Polish

- app/javascript/controllers/syntax_highlighting_controller.js
- app/javascript/src/js/lessons.js
- app/views/lessons/show.html.erb
Because:
* We are modularising the lessons.js file behaviour into separate Stimulus controllers as part of the move to Tailwind.
This commit:
* Extract syntax highlighting behaviour into Stimulus controller.
Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it …
> Chore: Extract Syntax Highlighting JS

- .github/workflows/heroku-review-app-on-label.yml
Because:
* We have to log into Heroku and manually create review apps for pull requests originating from forks - https://devcenter.heroku.com/articles/github-integration-review-apps#automatic-creation
* Being able to create and destroy review apps from the pull request itself will save us time.
* Closes: https://github.com/TheOdinProject/theodinproject/issues/3084
This commit:
* Add a GitHub workflow for creating and destroying heroku review apps with labels.
- …
> Chore: Create and Destroy Heroku Review Apps Using GH Labels

- app/javascript/controllers/external_link_targets_controller.js
- app/javascript/src/js/lessons.js
- app/views/lessons/show.html.erb
Because:
* We are modularizing the lessons.js file behaviour into separate Stimulus controllers as part of the move to Tailwind.
This commit:
* Move JS for setting external link targets out of lessons.js into a Stimulus controller.
Complete the following checkbox ONLY IF it is applicable to your PR. …
> Chore: Extract External Link Targets JS

- app/assets/stylesheets/dark-mode.css
- app/views/users/_skill.html.erb
Because
* The text was dark gray instead of white when dark mode is enabled.
This commit:
* Give the open course button the odin-dark-clear-button helper class.
-   [x] I …
> Fix: Dashboard Open Course Button on Dark Mode

- app/assets/stylesheets/components/lesson/_navigation.scss
- app/assets/stylesheets/components/lesson/lesson_content.scss
- app/components/progress_badge_component.html.erb
- app/javascript/src/js/lessons.js
- app/views/lessons/_header.html.erb
- app/views/lessons/show.html.erb
Because:
* We are moving all of our CSS to Tailwind.
This commit:
* Align lesson content slighter more left instead of on center for greater balance and fit between lesson nav and lesson content side by side.
* Move lesson nav right of lesson content for better reading experience.
* Move lesson nav within alignment of outer edges of page navbar in larger screens
* Adjust boldness in the lesson content headings to be a little lighter.
- `Feature` - adds new or amends …
> Feature: Convert Lesson Content Layout to use Tailwind

- app/views/shared/_bottom_cta.html.erb
Because:
* The text content was taking the full width of the page on the about page.
This commit:
* Constrains the width of the bottom cta by giving it a max width.
- …
> Fix: Bottom CTA Max Width

- app/views/lessons/show.html.erb
Because:
* The nav was able to slightly overlap the content between breakpoints.
This commit:
* Add a horizontal gap to the lesson content and nav grid.
-   [x] I have …
> Fix: Gap Between Content and Nav on Lesson page

- app/views/lessons/show.html.erb
Because:
* The font size we are using is slightly too big for content and code blocks etc.
-   [x] I have verified all tests and linters pass against my changes, and/or I …
> Feature: Reduce Lesson Content Text Size

- app/javascript/src/js/lessons.js
- app/services/markdown_converter.rb
- lib/kramdown/content_section.rb
- lib/kramdown/converter/html_sections.rb
- lib/kramdown/document_sections.rb
- spec/lib/kramdown/content_section_spec.rb
- spec/lib/kramdown/document_sections_spec.rb
- spec/services/markdown_converter_spec.rb
Because:
* Currently, we create sections in lesson content using a JS script so that scrollspy knows which section the user is currently on.
* It is much more efficient to create the sections while processing the markdown in a background job instead of on client side.
* This opens the door to move more of our lesson content processing such as setting external link attributes and wrapping images in anchor tags into Kramdown extensions.
This commit:
* Extend Kramdown to create sections when it encounters a level 3 heading in markdown.
* When the content does not start with a level 3 heading, create a generic content section for the beginning content.
* When the content does not have any level 3 headings, do not create any sections.
* Remove build scrollspy sections function from lesson js. …
> Chore: Create Content Sections During Markdown to HTML Processing

- lib/kramdown/converter/html_sections.rb
- spec/lib/kramdown/document_sections_spec.rb
Because:
* We were making sections for all heading 3's in the document.
This commit:
* Only make sections with the top level headings 3's.
-   [ ] I have verified all …
> Fix: Nested heading threes breaking detail lists

- lib/tasks/curriculum.rake
Because:
* It provides a nicer visual representation of the import progress.
-   [x] I have verified all tests and linters pass against my changes, and/or I have included …
> Chore: Add Progress Bar to Curriculum Import Task

- app/views/lessons/_header.html.erb
- app/views/lessons/show.html.erb
Because:
* It was too narrow.
This commit:
* Content can take up as much width as max-width-prose allows on medium breakpoints and below.
* Center the header badge and title on md breakpoint and below.
Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if …
> Fix: Lesson Content Width on Medium Breakpoint

- spec/tasks/curriculum_spec.rb
Because:
* The import task progress bar does not need to be displayed in the specs.
This commit:
* Stubs out stdout in the curriculum rake task.
-   [x] I have verified …
> Chore: Suppress Progress Bar Output in Specs

- app/services/markdown_converter.rb
- lib/kramdown/converter/odin_html.rb
- spec/services/markdown_converter_spec.rb
Because:
* We use h4's for some of the knowledge checks but aren't generating id's for those headings at the moment.
This commit:
* Generate ids for all headings, we were being overly cautious by turning off auto ids incase they conflicted with the section ids.
* Call parameterize on the generated id used for links wrapping h3's to ensure they are always the same as the section ids.
- `Chore` - changes …
> Fix: Broken Knowledge Check Links

- app/javascript/components/lesson-preview/components/lesson-content-preview.jsx
- app/views/static_pages/before_asking.html.erb
- app/views/static_pages/community_expectations.html.erb
- app/views/static_pages/community_rules.html.erb
- app/views/static_pages/dashboard_steps/_github_link.html.erb
Because:
* We removed most of the styles hooked to the lesson-content class
This commit:
* Apply Tailwind prose classes to the content in community pages.
* Apply Tailwind prose classes to lesson previews.
Closes: https://github.com/TheOdinProject/theodinproject/issues/3169
Complete the following …
> Fix: Content Styling on Lesson Preview And Community Pages

- app/javascript/controllers/lesson_toc_controller.js
Because
* Words like GitHub were being split in two at the capital letter, producing git-hub as the id.
This commit:
* Lowercase the headings before they are converted to id's with kebabCase.
Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not …
> Fix: Headings with Capital Letters Don't Work with Lesson Toc

- config/initializers/patch_enable_extension.rb
Because:
* Heroku recently changed how they handle Postgresql extensions which has introduced breaking changes when running rails db:schema:load
* https://devcenter.heroku.com/changelog-items/2446
This commit:
* Patches the issue as described in this [Stack Overflow thread](https://stackoverflow.com/questions/73214844/error-extension-btree-gist-must-be-installed-in-schema-heroku-ext/73289426#73289426) until a longer term fix can be found.
- `Feature` - adds new or …
> Fix: Review App's Failing on Release Phase During Deploy

- .slugcleanup
- .slugignore
- app.json
Because:
* To ensure our slug size is always small
This commit:
* Add the cleanup buildpack which is needed for the .slugcleanup file to work.
* Add spec, github and docs directories to slugignore as they are not needed to build the app.
Complete the following checkbox ONLY IF it is applicable to …
> Chore: Heroku Slug Cleanup

- .slugcleanup
- app/mailers/user_mailer.rb
- app/views/user_mailer/welcome_email.html.erb
- config/environments/production.rb
- spec/mailers/user_mailer_spec.rb
Because:
* We have removed the assets/images folder from our slug.
This commit:
* Render the image from the public directory (as it should be) for the user welcome email. …
> Fix: Rendering Images on User Welcome Email

- app/javascript/stylesheets/lesson-content.css
- app/views/lessons/show.html.erb
Because:
* A few tweaks to help the toc blend in while reading the main lesson content.
This commit:
* Lighten the toc item color and heading.
* Use font medium to improve toc item contrast and make them look more "clickable".
* Use gold border for active toc item to stay on brand.
Complete the …
> Feature: Lesson Toc Style Tweaks

- app/views/lessons/show.html.erb
Because:
* Long words like urls were overflowing in smaller screens.
This commit:
* Breaks words in lesson content when they overflow. …
> Fix: Word Wrapping in Lesson Content

- db/fixtures/paths/full_stack_rails/courses/ruby.rb
Because:
* Having the Pattern Matching lesson between the Blocks lesson and Custom Enumerables project has been the cause of some confusion.
-   [x] I have verified all …
> Feature: Move Ruby blocks Lesson Before Custom Enumerables Project

- tailwind.config.js
Because
* Just some tidying.
This commit:
* Replace the hardcoded color for the prose class with its equivalent color in the Tailwind theme object.
* Change h3 font weight to its default of 600 - the heading contains a link which is reducing font weight.
Complete the following checkbox ONLY IF it is …
> Chore: Replace Hardcoded Prose Color with Theme Color in Tailwind Config

- app/assets/stylesheets/typography.scss
Because:
* All of our headings are styled with tailwind now and these old styles are causing some sizing inconsistencies.
-   [x] I have verified all tests and linters …
> Chore: Remove old heading styles

- app/javascript/src/js/analytics.js
<hr>
Closes https://github.com/TheOdinProject/theodinproject/issues/3194 …
> Chore: add dashboard button tracking analytics & remove jQuery analytics

- app/views/shared/_flash.html.erb
Because:
* It looks more natural as an alert notification when not constrained to the page container.
-   [x] I have verified all tests and linters pass against my …
> Feature: Move alerts closer to view port right edge

- app/views/static_pages/about.html.erb
- app/views/static_pages/about/_overview.html.erb
- config/locales/en.yml
Because:
* Just a few UI tweaks
This commit:
* Move belief hash items to locale file
* Use our page-container instead of Bootstraps container
* Style email link to make it stand out from the surrounding text
* left align introduction text to make it more readable
> Feature: About Page Tweaks

- .github/dependabot.yml
Because:
* Too many bumps per week is risky and time consuming.
This commit:
* Reduce bundler gem bumps limit from 5 to 3
* Reduce npm package bumps limit from 5 to 3
> Chore: Reduce Weekly Dependabot Bumps

- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
Because:
* We are moving all our forms to Tailwind and have new form styles we want to use across the site.
This commit:
* Use our new Tailwind form builder on new password form.
* Use our new Tailwind form builder on edit password form.
> Feature: Use New Tailwind Form Design on Forgot Password Forms

- app/assets/images/icons/lightning-bolt.svg
Because:
* We don't use it anywhere.
> Chore: Remove lightning bolt icon

- app/javascript/components/project-submissions/components/form/text-area.jsx
- app/javascript/components/project-submissions/components/form/url-field.jsx
- app/views/shared/_footer_cta.html.erb
- app/views/users/passwords/edit.html.erb
- app/views/users/passwords/new.html.erb
- app/views/users/profiles/edit.html.erb
- app/views/users/registrations/edit.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- tailwind.config.js
Because:
* We want the Tailwind form styles to be automatically applied to any new form fields in the future.
This commit:
* Enable the Tailwind form plugin by default in Tailwind config.
* Remove the classes used to enable the Tailwind form plugin for individual fields.
* Fix email footer cta dark mode styling.
> Chore: Enable Tailwind Form Plugin by Default

- .babelrc
Because:
* For the code examples in the new React course.
> Feature: Support JSX Syntax Hightlighting

- app/controllers/lessons/previews_controller.rb
- app/javascript/components/lesson-preview/components/lesson-content-input.jsx
- app/javascript/components/lesson-preview/index.jsx
Because:
* We recently enabled the Tailwind form plugin by default which applies a form reset to all form fields.
This commit:
* Updates the styling of the lesson content/preview to match the new form design we are using across the site.
* Updates styling for react tabs to match the overall design.
> Fix: Lesson Preview Styling

- app/admin/announcements.rb
- app/assets/images/icons/x.svg
- app/assets/stylesheets/dark-mode.css
- app/components/announcement_component.html.erb
- app/components/announcement_component.rb
- app/javascript/controllers/announcement_controller.js
- app/views/layouts/application.html.erb
- app/views/shared/_announcement.html.erb
- db/migrate/20220917151628_add_learn_more_url_to_announcements.rb
- db/schema.rb
- spec/components/announcement_component_spec.rb
- spec/factories/announcements.rb
Because:
* The old Announcements had the same styles as our flash messages, making it easy to confuse them as toast messages.
closes: https://github.com/TheOdinProject/top-meta/issues/213
This commit:
* Redesign announcements to be a banner at the top of pages.
* Add learn more url to announcement model so we don't need to add raw links to the message.
* Move announcement partial markup into a view component so we can test it and choose to render it or not easily.
* Only display the latest announcements one at a time until dismissed - before it was possible to have a list of announcements display.
Before: 
After:
> Feature: Announcements Redesign

- app/components/oauth/connect_button_component.html.erb
- app/components/oauth/connect_button_component.rb
- app/views/shared/_omniauth_buttons.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- spec/components/oauth/connect_button_component_spec.rb
Because:
* We are moving all of our CSS to Tailwind.
* Closes: https://github.com/TheOdinProject/top-meta/issues/207
This commit:
* Change all styles on the sign up view to use Tailwind classes.
* Refactor oauth buttons shared between sign up/in pages to a single component.
* Remove old shared oauth buttons partial.
*
> Feature: Convert Sign up Page Styles to Tailwind

- app/views/users/sessions/new.html.erb
- tailwind.config.js
Because:
* Checkboxes do not have our custom styles applied in production.
This commit:
* The styles in the tailwind form builder were being purged.
> Fix: Checkbox styling

- app/views/users/registrations/new.html.erb
Because:
* The sign up form card  was overflowing into the footer.
This commit:
* Remove h-full utility from sign up page container. It is not needed on this page and causing the overflow issue.
> Fix: Sign Up Form Height

- app/views/notifications/index.html.erb
Because:
* To keep this page consistent with the rest.
> Chore: Use Page Container on Notification Index

- app/views/static_pages/success_stories.html.erb
Because:
* All cards on the site should be using the card view component.
This commit:
* Use card component for success story items.
* Simplify mark up.
> Chore: Refactor Success Stories Page to use Card Component

- app/components/progress/badge_component.html.erb
- app/javascript/controllers/progress_controller.js
- tailwind.config.js
Because:
* We recently upgraded to Tailwind 3 which changes how some things work like class overriding and where Tailwind checks for classes that are used.
This commit:
* Check all view component files for Tailwind classes.
* Remove the opacity-0 instead of overriding it with opacity-100 when the progress badge is loaded.
> Fix: Progress Badge Percentage Visibility

- app/javascript/stylesheets/lesson-content.css
Because:
* It is incorrectly applying a gray background to code blocks in pre tags.
This commit:
* Ensure code blocks within pre elements use the pre element background.
> Fix: Code Blocks in Lesson Panel Background

- app/views/static_pages/about.html.erb
- app/views/static_pages/contributing.html.erb
- app/views/static_pages/contributing/_contributing_options.html.erb
- app/views/static_pages/contributing/_hall_of_fame.html.erb
- app/views/static_pages/faq.html.erb
- app/views/static_pages/home/_how_it_works.html.erb
- config/locales/en.yml
**Because:**
The translation file was beginning to become unwieldy and could benefit from some organisation
* Namespaces keys in translation file in the way expected by I18n
* Converts existing translations to use lazy look-up
**Notes:**
Branched off of and pointed at #3150
> Chore: Restructure YAML keys in locale files

- config/locales/en.yml
**Because:**
The key is wrong so the the title is not rendering.
**Notes**
Was originally correct, but a regression snuck in after a rebase. 
Find at `/about`. Should display like so:
> Fix: Incorrect translation key for about page beliefs

- app/javascript/controllers/form_validation_controller.js
- spec/system/sign_up_spec.rb
- spec/system/user_login_spec.rb
- spec/system/user_settings_spec.rb
> fix: update form input validator to remove errors if appropriate on re-validation

- app/controllers/themes_controller.rb
- app/models/users/theme.rb
- spec/models/users/theme_spec.rb
Because:
* We had the theme names duplicated in the themes controller.
This commit:
* Adds an exists? method to the theme value object
* Refactor the themes controller to check if the theme exists or return an appropriate alert if it does not.
> Chore: Move Allowed Theme Behaviour into Theme Value Object

- app/javascript/components/project-submissions/components/submissions-list.jsx
Because:
* Links should be coloured gold so it's obvious they are links
* Closes #3391 
Post Fix:
> Fix: Add gold colour to 'view all submissions link' (#3391)

- app/views/users/show.html.erb
Because:
* It should display profile card items in a column on mobile
> Fix: Dashboard Profile Card on Mobile

- app/javascript/stylesheets/layout.css
- app/views/courses/show.html.erb
- app/views/lessons/installation_lessons/index.html.erb
- app/views/lessons/project_submissions/index.html.erb
- app/views/paths/index.html.erb
- app/views/paths/show.html.erb
- app/views/static_pages/faq.html.erb
- app/views/static_pages/terms_of_use.html.erb
Because:
* Now that all pages have been switched over to Tailwind, we should use only one page-container across the site to keep all pages consistent.
Closes: https://github.com/TheOdinProject/top-meta/issues/238
This commit:
* Remove .tmp-container-spacer utility class
* Remove and replace content containers with page containers and explicit max widths
> Chore: Remove Tmp Containers

- tailwind.config.js
**Because:**
* They should be pink
**This Commit:**
* Adds the correct colour to the Tailwind config file, which was missing a weight
* Closes #3397
**Additional Information:**
Seems to be a rule in `app/javascript/stylesheets/lesson-content.css`, but it's only targeting children of `a` elements. Unsure where the pink was coming from before :shrug: 
```css
.lesson-content a > code {
@apply text-pink-500;
}
```
> Fix: Inline code blocks not using correct colour

- app/views/users/show.html.erb
> Fix: Long usernames overflowing in profile card

- app/javascript/stylesheets/lesson-content.css
Because:
* It should match the color of the toc items.
> Feature: Reduce brightness of TOC border color in dark mode

- app/components/content_container_component.html.erb
- app/components/content_container_component.rb
- app/views/lessons/show.html.erb
- app/views/static_pages/before_asking.html.erb
- app/views/static_pages/community_expectations.html.erb
- app/views/static_pages/community_rules.html.erb
- app/views/static_pages/how_to_ask.html.erb
- app/views/static_pages/terms_of_use.html.erb
- spec/components/content_container_component_spec.rb
Because:
* We were repeating content classes in a few different files and needed to update each one when making changes to our content styling.
This commit:
* Add content container component with configurable classes and data attributes
* Use content container with lesson content
* Use content container with community page content
> Chore: Content Container Component

- bin/test
Because:
* Every linter that runs in CI should also run the test script
> Chore: Add Erblint to Test Script

- app/components/complete/icon_component.html.erb
Because:
* We've seen some reports about it being a little hard to tell whats complete and incomplete on the course page
This commit:
* Use a darker shade of gray for the the incomplete icon
Before:
After:
> Feature: Improve contrast between complete and incomplete icons

- app/views/courses/_course.html.erb
Because:
* The lesson count on course cards was hard to see on light mode.
Before:
After:
> Fix: Course Lesson Count Contrast

- db/fixtures/paths/foundations/seed.rb
- db/fixtures/paths/full_stack_javascript/seed.rb
- db/fixtures/paths/full_stack_rails/seed.rb
- db/fixtures/seed.rb
- lib/seeds/course_builder.rb
- lib/seeds/lesson_builder.rb
- lib/seeds/path_builder.rb
- lib/seeds/section_builder.rb
- spec/lib/seeds/course_builder_spec.rb
- spec/lib/seeds/lesson_builder_spec.rb
- spec/lib/seeds/path_builder_spec.rb
- spec/lib/seeds/section_builder_spec.rb
Because:
* The seeder classes were named incorrectly. They are instead builders which _build_ the curriculum up bit by bit by adding courses, sections and lessons to a path. We should reveal this in the code with the appropriate naming.
> Chore: Rename Seeder's to Builders

- .github/PULL_REQUEST_TEMPLATE.md
Because
If the details are first, they are viewable in Discord's webhook
This PR
* Moves the detail sections to the beginning of the template
* Moves the checklist section to the end of the template
* Adds an issue section to link the issue
* Adds the Because, This PR, and Issue sections to checklist
* Reduce wording that is not essential
Additional Information:
Related to https://github.com/TheOdinProject/curriculum/pull/24779
- `Feature` - adds new or amends …
> Fix: Flip order of PR checklist and details

- app/javascript/controllers/lesson_toc_controller.js
Firefox on `/lessons/foundations-installations` page is showing some non-functional anchor links.
<details>
<summary>Before screenshot (and as is in GoogleChrome)</summary>
</details>
<details>
<summary>After screenshot</summary>
</details>
- To a quick fix, I added a new condition (by section) to display the anchor links on lesson contents, making firefox have the same behavior as Google Chrome.
Closes #3444 
- `Chore` - changes that have no …
> fix: remove strange behavior on anchor for lesson nested content

- app/components/sections/lesson_component.html.erb
Because:
* Lesson icons can shrinks too much when paired with longer lesson names on mobile.
This commit:
* Don't allow lesson icons to shrink
Before:
After:
> Fix: Lesson Icon Shrinking on Mobile

- Gemfile
- Gemfile.lock
- app/views/layouts/component_preview.html.erb
- config/environments/development.rb
- config/routes.rb
- spec/components/previews/about_page/belief_component_preview.rb
- spec/components/previews/announcement_component_preview.rb
- spec/components/previews/complete/button_component_preview.rb
- spec/components/previews/complete/icon_component_preview.rb
- spec/components/previews/flash_component_preview.rb
- spec/components/previews/lessons/title_link_component_preview.rb
- spec/components/previews/paths/select_button_component_preview.rb
**Because:**
- It provides a nice visual interface for testing, designing and otherwise interacting with ViewComponents
**This Commit:**
- Adds lookbook gem
- Adds config for ViewComponent previews
- Adds several previews for individual components
**Notes**
- This PR is intended as a proof of concept / spike to see if this feature would be useful. There's a lot of places it could be polished improved, such as adding move variants to previews, mproving the default layout and adding the entire component library.
- Components with helpers are slightly harder to get working, although likely not impossible. Currently the Flash Preview is broken because it relies on a helper. 
- Adding more previews could be a good Hacktoberfest contribution for people midway+ through Rails
- I explored using …
> Feature: Add Lookbook and ViewComponent Previews

- .github/workflows/add_to_project.yml
* It's a common task that's useful and easy to automate
* Adds a Github action to workflows
Closes #3092
- [Action docs](https://github.com/actions/add-to-project)
- This is will require an admin [setting up a PAT](https://github.com/actions/add-to-project#creating-a-pat-and-adding-it-to-your-repository) before it works - current name `ADD_TO_PROJECT_PAT`
- Probably wortwhile giving a PAT organisation level access to repos, so that it can be re-used to automate other projects if it works as intended
- Current settings are very broad and will add all issues and PRs, but it is possible to make it more fine grained (ie issues only, based on certain labels or tags etc)
- This will eventually be a native feature to projects, so it should be removed when that becomes reality
> Feature: Add GitHub action to automate project board (#3092)

- app/components/notification_component.html.erb
- app/components/notification_component.rb
- app/views/errors/not_found.html.erb
- app/views/notifications/index.html.erb
- spec/components/notification_component_spec.rb
- spec/system/user_notification_spec.rb
- tailwind.config.js
Because:
* Since moving to Tailwind 3, we can use arbitrary values in place for custom config.
* We had custom colors for notifications which are no longer needed.
Closes: https://github.com/TheOdinProject/theodinproject/issues/3486
This commit:
* Remove custom height, margin and padding config only used on our not found page.
* Remove custom colors for notifications and replace them with default Tailwind colors.
> Feature: Clean Up Tailwind Config

- app/javascript/stylesheets/lesson-content.css
Because:
* This will allow us to make keyboard keys distinctive within lesson content.
This commit
* Add kbd element styling
> Feature: Keyboard Key Styles

- .github/workflows/add_to_project.yml
Because:
* There are permission issues for dependabot and people outside of the organisation. Additionally dependabot PRs don't add much value to project tracking, and contributors should have a related issue.
This PR:
* Closes #3517
> Chore: Remove PRs from add to project action (#3517)

- app/javascript/components/project-submissions/components/submission.jsx
Currently, long usernames are overflowing student solutions.
- Fix username overflowing solutions by usage of `truncate`
- Add responsive `max-width` in `p` element, so overflowing doesn't occur when resizing the window.
I was supposed to fix this a while ago but I ended up fixing the overflow in the profile card first. I decided to make a new PR because the initial issue is no longer open.
Below are the before and afters of two different cases.
Case 1: Longest personal name ever used || [Before](https://user-images.githubusercontent.com/112586034/204267397-580c451d-b37e-435e-b1a8-fcb9ad38b103.png) | [After](https://user-images.githubusercontent.com/112586034/204267425-f29867af-8dc4-4057-b7a5-694f234961c4.png)
Case 2: A really long username (no spaces) || …
> Fix: Long username overflowing the submission panel.

- app.json
Because
* Heroku has removed their hobby-dev Postgresql plan
This commit:
* Use Heroku's mini Postgresql plan
> Fix: Heroku Review App's

- app/views/users/sessions/new.html.erb
The reason for this change is because with the h-screen class the footer and the "sign in" section of the page overlaps on mobile phones once phone keypad is popped up for typing. It's also very noticeable if phone is in landscape.
Changing it from h-screen to min-h-screen class solves this issue.
Closes #XXXXX …
> Change Tailwind utility class from h-screen to min-h-screen

- CONTRIBUTING.md
The links to the suggestions-bugs channel in the Discord were out of date. They linked to an old channel that was not able to be used anymore.
- Changed two links from the [old channel](https://discord.com/channels/505093832157691914/540903304046182425) to the [new channel](https://discord.com/channels/505093832157691914/1010231881033330819)
Closes #3556 
N/a
- …
> Fix: Update links to #suggestions-bugs discord channel in Contributing.md

- app/javascript/components/project-submissions/components/__tests__/submissions-list.test.jsx
I changed the test description to make it easier to be read, since the context of 'no submissions' wasn't very clear.
Another alternative would be using double quotation marks, but it would not fit the other descriptions in the code.
The context of 'no submissions' wasn't clear enough in the code.
Closes #XXXXX …
> Improved code on line 102

- CONTRIBUTING.md
The background here is that I have a different minor change to propose (to one of the lessons), and I was about to bring it up on Discord in [#suggestions-bugs](https://discord.com/channels/505093832157691914/1010231881033330819), but then I was wondering if maybe it's a small enough change that it would be better to just make it in a fork and open a PR. So then I went to the [#faq](https://discord.com/channels/505093832157691914/823266307293839401), and while it's not directly addressed there, there is a link to GitHub, to follow the [contributing guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md). So I read through that, and found the ["Check Before Doing Anything"](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md#check-before-doi …
> Fix: Add links to open issues and PRs in CONTRIBUTING doc

- .circleci/config.yml
Because:
* An update to the browser tools orb is borking the checkout step.
* Related reports/discussion: https://discuss.circleci.com/t/cannot-checkout-anymore/46671/5
This commit:
* Implement suggested work around by moving the checkout step before the browser-tools step.
> Fix: Circle CI Test Job.

- db/fixtures/lessons/html_and_css_lessons.rb
Because:
* I noticed a couple of lessons were not updating their content.
This commit:
* Fix the "More CSS Properties" lesson's Github path.
* Fix the "Positioning Grid Elements" lesson's  Github path.
> Fix: Broken Lesson Github Paths

- app/assets/images/icons/arrow-left-circle.svg
- app/javascript/components/project-submissions/containers/project-submissions-container.jsx
- app/views/lessons/project_submissions/index.html.erb
There's no easy way to navigate back to the lesson one is currently on when browsing its submissions page.
- Adds a link to go back to lesson while browsing project submissions.
Closes #3518 
The way this is implemented it probably will get user to land on the very top of the page as if they were there first time. Possibly for best UX, we should get them back to the `Solutions` component but that'd require having an anchor in there. Not sure if that anchor would render in the `Lesson contents` and if that'd be something we want to happen. We possibly might make the link anchor onto `Additional Resources` - somewhat close and we have that already.
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CO …
> Feature: add link to go back to a lesson from project submissions page

- app/models/content.rb
- app/models/lesson.rb
- app/services/lesson_content_importer.rb
- app/views/lessons/show.html.erb
- db/migrate/20221014124812_create_contents.rb
- db/migrate/20221014130631_remove_content_from_lessons.rb
- db/schema.rb
- spec/factories/contents.rb
- spec/factories/lessons.rb
- spec/models/content_spec.rb
- spec/models/lesson_spec.rb
- spec/services/lesson_content_importer_spec.rb
**Because:**
* It avoids an expensive operation when it is not needed
* Spike for / closes #3423
* Remove content column from lesson
* Create new content table
* Update lesson importer to point to new table
* Beat Factory Bot into submission
> Chore: Move lesson contents to new table (#3423)

- db/migrate/20230115072941_add_index_to_announcements_expires_at.rb
- db/schema.rb
Because:
* We look up announcements based on it's expires at value.
This commit:
* Add an index to announcements expires_at
> Chore: Add Index to Announcements Expires At

- db/fixtures/lessons/ruby_on_rails_lessons.rb
- db/fixtures/paths/full_stack_rails/courses/rails.rb
Because:
* We need to provide more deployment options since Heroku no longer has a free tier.
This commit:
* Remove preparing for deployment lesson - it was all about setting up Heroku and no longer needed.
* Move deployment lesson after the first blog project so we can give the learner the assignment of deploying their finished blog app.
Curriculum changes: https://github.com/TheOdinProject/curriculum/pull/25042
> Feature: New Rails Deployment Lesson

- db/seeds.rb
- lib/generators/rails/seed_uuids/USAGE
- lib/generators/rails/seed_uuids/seed_uuids_generator.rb
Because:
* It is frustrating and time consuming having to manually generate uuids and then copy and paste them into the seed files.
* To get a random uuid automatically created for you, you just need to give any identifier_uuid attribute the value of `"create_uuid"` and then run the seeds as normal.
This commit.
* Adds a seed_uuids generator which will look for any "create_uuid" strings within the fixtures files and replace any instances with a new random uuid.
* New generator can be invoked form the command line manually with `bin/rails g seed_uuids`.
* Generator is invoked during the seed task everything is done with one command instead of needing to manually run the uuid generator first and then and then the seeds task.
> Chore: Automate Setting New UUID's When Running the Seeds Task

- lib/generators/rails/seed_uuids/seed_uuids_generator.rb
Because:
* It was finding all matches in a file and replacing them all with the same UUID.
This commit:
* Use a block with `gsub_file` as it will generate a new uuid for each match.
> Chore: Generate unique UUID's for matches in the same seed file

- config/routes/redirects.rb
it would be neat to link to discord via our own route.
Adds a route at theodinproject.com/discord
Closes #3694
- …
> Feature: Add discord route

- db/fixtures/lessons/shared_lessons.rb
- db/fixtures/paths/foundations/seed.rb
- db/fixtures/paths/full_stack_javascript/courses/node_js.rb
- db/fixtures/paths/full_stack_rails/courses/rails.rb
- db/seeds.rb
Because:
* We introduce the backend at the end of foundations, well before that information will become relevant. By the time learners get to the backend courses in each path, this information will no longer be fresh in their heads. This moves those lessons closer to where they will be useful for learners.
This commit:
* Add a shared lessons seed file where we can keep lessons that have the same content but are in different courses in each path.
* Move foundation backend lessons to the introduction section of the Rails and Node courses.
> Feature: Move Backend Section From Foundations

- app/views/static_pages/contributing/_hall_of_fame.html.erb
This solves the bug on the [Contribute Page](https://www.theodinproject.com/contributing) Hall of Fame section where the images are vertically stretched using the Safari browser. 
- Removed the class `h-full` from each image. This was forcing all images to have a `height:100%`.
- When the `h-full` class is removed, the `height:auto` is set with the code below:
`img, video { 
height: auto;
max-width: 100%;
}`
Closes #3662
- `Chore` - changes that …
> Fix: Stretched TOP contributor images bug for Safari browser

- app/controllers/application_controller.rb
- app/controllers/courses_controller.rb
- app/controllers/lessons/completions_controller.rb
- app/controllers/lessons_controller.rb
Because:
* Lesson completions check boxes can sometimes get into the wrong state due to http caching when using the browsers back and forward navigation buttons.
* Closes https://github.com/TheOdinProject/theodinproject/issues/3717
This commit:
* Don't use http no cache header with lesson and course pages so a fresh page is always sent in response.
> Fix: Lesson and Course Page Caching

- app/javascript/controllers/complete_button_controller.js
- package.json
- yarn.lock
Because:
* We don't need to pass params to completions controller since we are using the lesson_id in the url path.
This commit:
* Remove humps package.
* Remove data attribute from the completions request.
> Chore: Remove Humps Package

- config/webpacker.yml
- package.json
- yarn.lock
Because:
* Resolve warning: Webpacker::VersionChecker - Version mismatch detected
This commit:
* Enable ensure_consistent_versioning option in Webpack config
* Bump Shakapacker package to 6.6 to match the gem version.
> Chore: Ensure Shakapacker package and gem versions are the same

- app/javascript/components/project-submissions/components/submission.jsx
- app/javascript/stylesheets/pagy.css
- app/views/lessons/project_submissions/index.html.erb
This pull request fixes the page overflow issue on The Odin Project's project_submissions page. Currently, when users click on the "View full list of solutions" link on any project page ( eg. [View full list of solutions](https://www.theodinproject.com/lessons/596/project_submissions) ), the resulting page layout is broken on mobile devices and smaller screen sizes. The issue is caused by two main problems: the hint--top class from the Hint.css library and the pagination's fixed width as shown below with some screenshots.
1.  The hint--top class from Hint.css library was contributing to the page overflow. Below is a screenshot to demostrate my claim. 
2. The pagination is not responsive and also results to page overflow. Below is the screenshot.
After fixing the above below are the …
> Fix: fix project submissions' page overflow bug.

- db/fixtures/lessons/foundation_lessons.rb
Because:
* This lesson was in an incorrect folder in the curriculum repo.
* Related curriculum PR: https://github.com/TheOdinProject/curriculum/pull/25474
This commit:
* Move it into the html_foundations folder which represents its section on the site.
> Chore: Move Introduction to HTML & CSS Lesson

- db/fixtures/lessons/foundation_lessons.rb
Because:
* These lessons were in the top level HTML and CSS folder instead of in the CSS Foundations folder which represents the section the lessons are within on the curriculum.
* Related curriculum PR: https://github.com/TheOdinProject/curriculum/pull/25490
> Chore: Chore: Move introductory CSS lessons into correct Folder

- db/fixtures/lessons/foundation_lessons.rb
Because:
* This lesson was in the top level HTML and CSS folder instead of the CSS Foundations folder, which represents the section the lesson is within on the curriculum.
* Related curriculum PR: https://github.com/TheOdinProject/curriculum/pull/25492
> Move inspecting HTML and CSS lesson into correct folder

- .rubocop.yml
Because:
* They're already loaded as part of Rubocop-rspec. Silences recommendation to add when linting
> Chore: Add Capybara and Factorybot to Rubocop config

- db/fixtures/lessons/foundation_lessons.rb
Because:
* Renaming it "project-landing-page" to make the file easier to find and moving it to the flexbox folder which is the section where the project is displayed on the site.
* Related curriculum PR: https://github.com/TheOdinProject/curriculum/pull/25509
> Chore: Rename and Move Landing Page Project Folder Location.

- spec/lib/seeds/course_builder_spec.rb
Because:
- It causes intermittent `ActiveRecord::RecordNotUnique` errors
[Example failure](https://app.circleci.com/pipelines/github/TheOdinProject/theodinproject/5376/workflows/d570a01e-3cc4-4505-a545-224c60b4e409/jobs/15167/tests#failed-test-0)
> Fix: Remove hardcoded id from course_builder_spec.rb

- config/initializers/active_admin.rb
Because:
* Save admins from needing to remember the url path for the sidekiq dashboard.
> Feature: Admin menu link for Sidekiq Dashboard

- db/fixtures/lessons/foundation_lessons.rb
Because:
* All lessons should be in the folders which represent the section they live in on the site.
* Related curriculum PR: https://github.com/TheOdinProject/curriculum/pull/25575
This commit:
* Move block and inline lesson to CSS foundations folder
* Move box model lesson to CSS foundations folder
> Chore: Move CSS Foundation Lessons to Correct Folder

- app/views/admin/flags/_flag_actions.html.erb
Because:
* Rails 7 has switched button_to helpers to use button instead input elements. But, Active admin styles buttons by targeting input elements.
This commit:
* Use form with submit button to get back input elements for the flag buttons - This is kind of a hacky work around until we can migrate from active admin or they update their CSS.
> Fix: Admin Flags Button Styling

- app/controllers/guides/community_controller.rb
Because:
* Now that we're on Ruby 3.2, we can use the built-in Data class in place of structs :tada:
This commit:
* Use Data class instead of  OpenStuct when creating guide page objects.
> Chore: Replace OpenStruct with Data class

- app/assets/images/icons/flag.svg
- app/assets/images/icons/heart.svg
- app/components/project_submissions/item_component.html.erb
- app/components/project_submissions/item_component.rb
- app/controllers/lessons/v2_project_submissions_controller.rb
- app/views/lessons/_project_submissions.html.erb
- app/views/lessons/show.html.erb
- app/views/lessons/v2_project_submissions/index.html.erb
- config/routes.rb
Because
* We can simplify and make our project submissions feature more robust by using Hotwire.
This commit:
* Add v2_project submissions feature flag, controllers and routes so we can move things over gradually.
* Add project submission item component to replicate the submission item component we have in react.
* Lazily load the submission list with Hotwire - displays a loading spinner until the list response is rendered.
> Chore: Display project submissions list using Hotwire

- app/components/oauth/connect_button_component.html.erb
Turbo was re-enabled, breaking the logging in functionality through Github & Google. This PR resolves that issue.
- Adds `data-turbo: false` to the Github & Google login buttons, and any future provider that is added using the Omniauth button component
- Resolves CORS error caused by Turbo
Closes #3853
Related #3806
Various users reported this in Discord, and I confirmed that I could not log in using Github or Google on my end as well, before the fix.
- `Feature` - adds new or amends existing user-facing …
> Fix: Disable Turbo when using omniauth to sign in

- app/javascript/controllers/lesson_toc_controller.js
Because:
* Turbo is caching lesson tables of contents and duplicating them on return visits.
* Closes: https://github.com/TheOdinProject/theodinproject/issues/3863
This commit:
* Tear down a lessons table of contents when navigating away from the lesson and the TOC stimulus controller disconnects.
> Fix: Lesson table of contents duplicating on Turbo restoration visits

- app/views/layouts/application.html.erb
Because:
* Turbo drive needs a track data attribute on stylesheet links in order to perform full page reloads when style changes are deployed.
This commit:
* Add data-turbo-track='reload' to all stylesheet links
> Fix: Full page reload when style changes are deployed.

- app/views/users/registrations/edit.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- Globally enabling turbo has broken logging in, creating an account with, and updating passwords for any account using the email + password login method
- Sets `turbo: false` on the submit buttons associated with those actions. This appears to fix the issue
Per request, @LeoKirasic 
First reported on Discord at https://discord.com/channels/505093832157691914/505093832157691916/1121055621836451890
- `Chore` - changes that have no user-facing …
> Fix: fix email login

- app/views/users/profiles/edit.html.erb
- app/views/users/registrations/edit.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- config/initializers/devise.rb
Because:
* Devise needs a couple of config changes to work properly with Turbo. Otherwise unsuccessful sign-ins will return JS errors.
This commit:
* Update Devise error responses to return a 422(unprocessable_entity) status
* Update Devise redirects to return a 303(see_other) status
* Change reset progress and cancel account links to use the turbo http delete method instead of ujs http delete method
> Chore: Update Devise Config for Turbo

- app/javascript/controllers/lesson_toc_controller.js
Because:
* We are removing the toc items so they won't be cached, but we are still observing them with an intersection observer.
This commit:
* Unobserve all headings before destroying them on page navigation.
> Fix: JS error with toc item on page navigation.

- app/components/nav/item_component.html.erb
- app/components/nav/item_component.rb
- app/components/user/profile_dropdown_component.html.erb
- app/views/shared/_off_canvas_menu.html.erb
- config/routes.rb
- spec/components/nav/item_component_spec.rb
Because:
* Using a get for something destructive like signing out is a security issue. Users could be made to unintentionally sign out if they clicked on a "https://theodinproject.com/sign_out" link someone sent them.
This commit:
* Change sign_out path to delete instead of a get request.
* Refactor nav item component to take an options hash which we can use for the mobile flag and this new method option.
> Feature: Use delete request with sign out

- spec/support/precomple_assets.rb
- spec/tasks/curriculum_spec.rb
- spec/vcr/lesson_content.yml
Because:
* We have been encountering an increasing number of timeouts in our CI builds lately. Investigating leads to lazily loaded assets sometimes taking a while to fully load.
This commit:
* Add a RSpec before hook to precompile assets before the test suite runs.
> Chore: Precompile Assets Before Tests

- spec/serializers/project_submission_serializer_spec.rb
FactoryBot increments ids each time a factory is created, there is potential for those specs to flake depending on the randomized run order
- Removed the hardcoded ids when creating a factory
- Use the ids created by factory when creating serialized project submission
Closes #3897  …
> Fix: Remove hardcoded ids

- CONTRIBUTING.md
- We've removed the usage of the `#suggestions-bugs` channel for on Discord discussion of issues, in favor of using per repo issues
- Removes references to `#suggestions-bugs` and rewrites some of the surrounding content to account for this
Part of #3892 
-   [x] The `This PR` …
> Fix: update CONTRIBUTING.md to remove references to Discord

- app/views/guides/community/rules.html.erb
Our asking question rule did not clearly communicate the importance of putting forth effort in asking questions. We have had a number of learners struggle with asking good questions, so strengthening our wording in our rules help us communicate to them the importance of asking context-rich questions.
* Adds link to our How to Ask community guide
* Adds 3 examples of low effort questions
* Add note about the importance of this rule
Closes https://github.com/TheOdinProject/moderator/issues/65
After approval this will need to be updated with Dyno in our rules channel. …
> Fix: Expand asking question rule

- app/views/layouts/component_preview.html.erb
This commit:
* Remove shared/ga partial call - it no longer exists.
* Add missing closing body tag
> Fix: Component Preview Layout

- app/assets/images/icons/pencil-square.svg
- app/components/project_submissions/item_component.html.erb
- app/components/project_submissions/item_component.rb
- app/controllers/lessons/v2_project_submissions_controller.rb
- app/views/lessons/v2_project_submissions/_form.html.erb
- app/views/lessons/v2_project_submissions/edit.html.erb
- app/views/lessons/v2_project_submissions/index.html.erb
- app/views/lessons/v2_project_submissions/new.html.erb
- app/views/lessons/v2_project_submissions/update.turbo_stream.erb
- config/routes.rb
- spec/system/v2_lesson_project_submissions/delete_submission_spec.rb
- spec/system/v2_lesson_project_submissions/edit_submission_spec.rb
Because:
* We are moving our project submissions feature to Hotwire
This commit:
* Add action menu to every project submission. The users submission will display edit and delete links, everyone else's will have the report link (yet to be implemented)
* Add edit and update actions/views for v2 project submissions
* Add delete action for v2 project submissions
> Feature: Edit and Delete Submission with Hotwire

- app/javascript/stylesheets/lesson-content.css
Because:
* It will improve contrast between default and link text.
> Feature: Reinstate underlines for links

- spec/system/v2_lesson_project_submissions/add_submission_spec.rb
Because:
* On some test runs, it is not waiting long enough to find the submit button.
This commit:
* Use the project submission form page object submit button finder.
> Fix: Flaky project submissions test

- app/views/errors/not_found.html.erb
- Currently when loading the 404 page in dark mode the links are inaccessible
- Changes them to a more visible color, and also makes the underline go away on hover
Closes #3932 
-   [x] I have …
> Fix: change not_found links to a more accessible color

- app/controllers/lessons/v2_project_submissions_controller.rb
- app/views/lessons/v2_project_submissions/_add_button.html.erb
- app/views/lessons/v2_project_submissions/create.turbo_stream.erb
- app/views/lessons/v2_project_submissions/destroy.turbo_stream.erb
- app/views/lessons/v2_project_submissions/index.html.erb
- spec/system/v2_lesson_project_submissions/add_submission_spec.rb
- spec/system/v2_lesson_project_submissions/delete_submission_spec.rb
Because:
* The add button was not displaying again after deleting your submission.
This commit:
* Breaks the add submission button out into its own partial so it can be rendered within turbo streams.
* Adds a destroy turbo stream response to remove the submissions and display the add button.
* Add a couple of expectations to ensure this cannot regress in the future.
> Fix: Hotwire submissions add and delete flow

- app/assets/images/icons/ellipsis-vertical.svg
- app/assets/images/icons/trash.svg
- app/components/modal_component.html.erb
- app/components/project_submissions/item_component.html.erb
- app/controllers/lessons/v2_project_submissions_controller.rb
- app/controllers/project_submissions/flags_controller.rb
- app/javascript/controllers/modal_controller.js
- app/views/layouts/application.html.erb
- app/views/project_submissions/flags/create.turbo_stream.erb
- app/views/project_submissions/flags/new.html.erb
- config/routes.rb
- spec/support/capybara.rb
- spec/support/cuprite.rb
- spec/system/v2_lesson_project_submissions/add_submission_spec.rb
- spec/system/v2_lesson_project_submissions/flag_submission_spec.rb
Because:
* We are moving our React components to Hotwire.
This commit:
* Renders Flag form within a Hotwire modal
* Amends flags controller to work with both the Hotwire and React versions of the flag form.
* Improves dark mode style of the submission action menu dropdown.
* Add `wait_for_turbo` system test helper - lazily loaded turbo frames may not be available when Capybara tries to interact with its content. This helper ensures it ready to be interacted with.
Cuprite config changes:
When working with the tests I couldn't run in non-headless mode. After some investigating, Cuprite was not being passed our custom config options set when registering the driver with Capybara. 
Changing the name we use to the register the driver from "cuprite" to "odin_cuprite" fixed it. I haven't been …
> Feature: Convert project submission flagging feature from React to Hotwire

- spec/system/v2_lesson_project_submissions/add_submission_spec.rb
Because:
* It has appeared again: https://app.circleci.com/pipelines/github/TheOdinProject/theodinproject/5600/workflows/5c7ebb19-cdbc-4c1f-822d-25b3e547137a/jobs/15911/tests#failed-test-0
* Capybara is trying to open the form before the project submissions turbo frame is finished loading.
This commit:
* Wait until the turbo frame is finished loading and then open the submission modal.
> Fix: Flaky add submission test (round 2)

- app/javascript/stylesheets/layout.css
- app/views/static_pages/home/_success_stories.html.erb
- package.json
- yarn.lock
Because:
* The dependabot bump was previously failing because of an import duplication error.
This commit:
* Remove our layout gradient class, it was causing the build to fail because it [duplicates an import](https://github.com/tailwindlabs/tailwindcss/issues/11473). We were only using this class in one place so I just moved the styles to the element.
* Bump to latest version of Tailwind.
> Feature: Bump Tailwind

- app/views/static_pages/about.html.erb
- config/locales/en.yml
I noticed the wording of the "Motivation is fueled by working with others" was not quite accurate. It was suggested to reword these into more of a "How it works" section.
* Renames the beliefs section to "What you can expect at The Odin Project"'
* Reword each section to encompass similar things that we value and want our learners to be aware of.
- `Fix` - bug …
> Feature: Update wording of our beliefs

- app/components/theme/switcher_component.yml
- app/components/user/profile_dropdown_component.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/themes/update.turbo_stream.erb
**Because:**
* Current behaviour is inconsistent and confusing
**This PR:**
* Moves theme switcher out of dropdown menu when logged in
* Adjusts position to be consistent when logged in or out
* Tidy broken Lookbook previews due to removal of GA tracking
> Fix: Improve theme switcher UX (#3497)

- app/components/modal_component.html.erb
- app/javascript/controllers/modal_controller.js
- spec/support/capybara.rb
- spec/system/v2_lesson_project_submissions/add_submission_spec.rb
Because:
* We listen for esc keydown events when the submission modal is open to close it. But this is being ignored in the test env and firing on any keydown event.
Running the test in non-headless with slow mo and stimulus debug enabled shows whats happening (notice all the modal close events being fired after the first field is filled in lol)
https://drive.google.com/file/d/1oR29fmg0gboZT-Sm57hc9nb-u4dsprv8/view?usp=drive_link
This commit:
* Filters the keydown event manually with a new function on the modal controller instead of using a [Stimulus JS keyboard event filter action](https://stimulus.hotwired.dev/reference/actions#keyboardevent-filter).
* Disables animations in system tests - it's generally recommended.
> Fix: Modal closing on any key press in test env

- app/views/lessons/_lesson_buttons.html.erb
- the current secondary buttons at the bottom of each lessons are both inaccessible and also distracting when placed directly next to a primary button ("Mark complete") in this case.
- Changes the button style to `button--clear`
Part of #3923 
-   [x] The `This PR` section has a …
> Feature: Change lesson buttons to clear style

- app/helpers/button_helper.rb
- app/views/static_pages/about.html.erb
- spec/helpers/button_helper_spec.rb
- Our current button styling doesn't meet WCAG contrast requirements
- Changes links to Discord to `button--clear`
Part of #3923 
-   [x] I have verified all tests and linters pass after making …
> Feature: Change Discord buttons to clear style

- app/components/project_submissions/item_component.html.erb
- app/components/project_submissions/item_component.rb
- app/components/project_submissions/like_component.html.erb
- app/components/project_submissions/like_component.rb
- app/controllers/lessons/v2_project_submissions_controller.rb
- app/controllers/project_submissions/v2_likes_controller.rb
- app/javascript/controllers/sort_controller.js
- app/models/project_submission.rb
- app/services/project_submissions/mark_liked.rb
- app/views/lessons/v2_project_submissions/index.html.erb
- app/views/project_submissions/v2_likes/create.turbo_stream.erb
- config/initializers/pagy.rb
- config/routes.rb
- package.json
- spec/models/project_submission_spec.rb
- spec/system/v2_lesson_project_submissions/like_spec.rb
- yarn.lock
Because:
* We are moving our React components to Hotwire
This commit:
* Add like view component to encapsulate the like button.
* Add like singular resource route and controller - now with a proper delete route instead of reusing the create action.
* Decorates submissions with current user likes when they are being fetched. This saves us from checking each one individually and hitting the database each time.
* Adds a reusable sorting stimulus controller - can be used to automatically sort lists on page load or when a list item changes.
> Feature: Liking project submissions with Hotwire

- app/components/project_submissions/item_component.html.erb
- app/views/lessons/v2_project_submissions/_add_button.html.erb
- app/views/lessons/v2_project_submissions/_form.html.erb
- app/views/lessons/v2_project_submissions/index.html.erb
- spec/system/v2_lesson_project_submissions/add_submission_spec.rb
- spec/system/v2_lesson_project_submissions/delete_submission_spec.rb
Because:
* A few final touches before we start rolling this out to users.
This commit:
* Move the add solution button hook outside of the current users solution conditional - this is needed for the button to display correctly when the user deletes their solution after refreshing the page.
* Change "Add submission" button text to "Add solution" - to fit the solutions title.
* Add a hidden class to the drop down so it does not flash visible for a brief moment during re-render
> Feature: Moving project solutions to Hotwire final tweaks

- app/helpers/application_helper.rb
- app/views/paths/show.html.erb
- app/views/static_pages/success_stories.html.erb
- Currently the combo either show sign up or view curriculum button is called `sign_in_or_view_curriculum_button`, despite the possible actions being either `sign_up` or `view_curriculum`
- Corrects it to `sign_up_or_view_curriculum_button`
-   [x] The `This PR` section has a …
> Fix: change button name to correctly reflect button type

- app/helpers/button_helper.rb
- spec/helpers/button_helper_spec.rb
- Neither `sign_in_button` or `create_new_account_button` are used anywhere within the app, nor do I see an use in the immediate future; we use "Sign up" as a call to action for signing up, and we (almost?) always direct people to sign up, not to sign in.
- Drops the button definitions and their associated tests …
> Chore: Drop unused buttons

- app/components/logo_component.html.erb
- app/views/shared/_navbar.html.erb
- app/views/static_pages/about/_overview.html.erb
- Currently there isn't anything describing where the logo links go to, which presents issues when using a screen reader
- Adds a `aria-label` to make it clear where the links go to
-   [x] I …
> Fix: Add aria-label to logo links

- app/components/oauth/connect_button_component.html.erb
- app/components/paths/view_button_component.html.erb
- app/helpers/button_helper.rb
- app/javascript/stylesheets/buttons.css
- app/views/courses/_course.html.erb
- app/views/lessons/_lesson_buttons.html.erb
- app/views/paths/show.html.erb
- app/views/static_pages/about.html.erb
- app/views/users/_skill.html.erb
- app/views/users/profiles/edit.html.erb
- spec/helpers/button_helper_spec.rb
- While working on #3923 @KevinMulhern rightfully pointed that out that by replacing (almost) all occurrences of `button--secondary` with `button--clear` we had essentially just replaced one with the other. This PR makes that change formal by renaming `button--clear` to `button--secondary`. While I could have renamed the old `button--secondary` to something like `button--gold` I opted to not do so given its inherent contrast issues.
- Renames `button--secondary` to `button--clear`
- Drops the old `button--secondary` styling
Closes #3923 
-   [x] The title of this PR follows the `keyword: brief description of change` format, using …
> Feature: Rename button--clear to button--secondary and drop old secondary class

- app/views/shared/_footer.html.erb
- The current text color of the footer is both inaccessible and also just doesn't match the rest of TOP
- Changes it to the default text colors
Closes #3963  …
> Feature: Change footer text color to match the default

- app/views/errors/unprocessable_entity.html.erb
- The error code in the title accidentally says `500` instead of `422`
- Changes it to 422
> Fix: fix title of 422 page

- app/views/courses/_course.html.erb
Because:
* The lesson count was too light - darkens the title to better match the new lesson count color.
Before:
After:
> Feature: Darken course title and lesson count in light theme.

- app/javascript/stylesheets/lesson-content.css
Because:
* We were only removing the underline on hover for external links. This resulted in some links sections having links with different hover behaviour.
* I think this rule was added so the links in headings wouldn't display an underline on hover - but it doesn't seem to be needed anymore.
https://github.com/TheOdinProject/theodinproject/assets/7963776/4b43c711-4674-4679-ba5d-2f34f8868451
This commit:
* Removes the http matcher regex from the lesson content link selector.
> Fix: Inconsistent link hover behaviour

- app/components/announcement_component.html.erb
- app/components/faq/item_component.html.erb
- app/javascript/components/project-submissions/components/submissions-list.jsx
- app/views/errors/internal_server_error.html.erb
- app/views/errors/unprocessable_entity.html.erb
- app/views/lessons/_project_submissions.html.erb
- app/views/lessons/show.html.erb
- app/views/paths/index.html.erb
- app/views/static_pages/about.html.erb
- app/views/static_pages/contributing/_hall_of_fame.html.erb
- app/views/static_pages/dashboard_steps/_github_link.html.erb
- app/views/static_pages/home/_success_stories.html.erb
- app/views/static_pages/success_stories.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- `text-gold-600` / `text-gold` (which comes down to the same) doesn't meet minimal contrast requirements
- cleans up all remaining in-text uses, except the main page header
- For most pages this meant either stripping it entirely or replacing it with `underline hover:no-underline text-gray-600 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300`
- A few exceptions
- The "start here" above Foundations on `/paths` has always been small, and without color didn't stand out at all. Given that the design of the page already makes clear what is happening I opted to instead strip it entirely
- When not logged in on a lesson page with projects a user would see "Please [Sign in](https://www.theodinproject.com/sign_in) or [Sign up](https://www.theodinproject.com/sign_up) to view user …
> Feature: clean up usage of gold text

- app/views/paths/show.html.erb
- app/views/shared/_bottom_cta.html.erb
- app/views/static_pages/about.html.erb
- app/views/static_pages/success_stories.html.erb
- Currently `shared/_bottom_cta.html.erb` requires a `sub_heading` to be passed. Sometimes this isn't wanted however, and to avoid errors people simply pass an empty string. This however leads to weird empty `p` elements.
- Makes `sub_heading` optional, and doesn't render anything if nothing is passed
- Fixed all cases where `sub_heading` is an empty string
- …
> Fix: Make subheading optional

- app/views/static_pages/home.html.erb
Upon initial loading of the homepage, the hero background moves around a bit. 
After solving this, the page will load smoothly due to browser knowing the pre-made space the banner requires.
- Adds ``class: 'w-full h-full' `` to the homepage [banner](https://github.com/TheOdinProject/theodinproject/blob/main/app/views/static_pages/home.html.erb#L15) element.
Closes #3949
- `Chore` - changes that have no user-facing value, refactors, dependency …
> Feature: Give homepage hero background full width and height

- app/views/user_mailer/welcome_email.html.erb
Hi. 
Removed space after `mailto:` keyword protocol - fix for Welcome message.
Issue fix: https://github.com/TheOdinProject/theodinproject/issues/3999
Changed to valid email address.
#3999
Useful resource:
"URLs cannot contain spaces. URL encoding normally replaces a space with a plus (+) sign, or %20."
https://www.w3schools.com/html/html_urlencode.asp#:~:text=URLs%20cannot%20contain%20spaces.,(%2B)%20sign%2C%20or%20%20.
-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
- `Chore` - changes that …
> Fix email address - mailto

- app/views/users/profiles/edit.html.erb
- app/views/users/registrations/edit.html.erb
Because:
* The bottom border radius is being overlapped by the action bar on settings cards.
This commit:
* Adds a bottom border radius to the action bar which matches the rest of the card.
> Fix: Bottom border radius on settings card

- app/assets/images/icons/folder-plus.svg
- app/components/project_submissions/item_component.html.erb
- app/views/lessons/_project_submissions.html.erb
- app/views/lessons/v2_project_submissions/_blank_state.html.erb
- app/views/lessons/v2_project_submissions/create.turbo_stream.erb
- app/views/lessons/v2_project_submissions/destroy.turbo_stream.erb
- app/views/lessons/v2_project_submissions/index.html.erb
Because:
* When there are no solutions we should prompt the learner to add one.
This commit:
* Adds a blank state to be displayed when there are no solutions.
* Adds logic for adding/removing the blank state when the user adds/removes their solution.
* Included some responsive fixes for solution items.
> Feature: Solutions blank state

- app/components/faq/item_component.html.erb
- app/views/shared/_bottom_cta.html.erb
- app/views/static_pages/contributing/_contributing_options.html.erb
- app/views/static_pages/contributing/_hall_of_fame.html.erb
Some headings of our static pages are not using the correct hierarchy.
1. For `/faq` page, changed `components/faq/item_component.html.erb` heading from `h3` to `h2`.
2. For `/about` page, changed `views/shared/_bottom_cta.html.erb` heading from `h4` to `h2`.
3. For `/contributing` page, changed two headings's hierarchy.
Closes #3965 
This is a resubmitted PR due to my remote branch conflicts. The previous PR #3995 is closed.
- `Chore` - changes …
> Fix: wrong hierarchy for some headings

- app/components/project_submissions/item_component.html.erb
- app/views/lessons/v2_project_submissions/_form.html.erb
- spec/support/pages/project_submissions/form.rb
- spec/system/v2_lesson_project_submissions/add_submission_spec.rb
Because:
* Some solutions do not accept previews - for example the early Ruby projects.
This commit:
* If the project does not accept live previews...
* Hide the live preview input.
* hide the live preview button
> Feature: Hide live preview input and button

- app/controllers/users/profiles_controller.rb
Provides the user with visual feedback when an email they have entered is already in use.
- Add `status: :unprocessable_entity` to line 11 of profiles_controller.rb
Closes #3984 
-   [x] I have …
> Feature: Display error if email in use

- app/javascript/controllers/lesson_toc_controller.js
Because:
* With turbo caching enabled we need to tear down the lessons table of contents(toc) before the page is cached. We were doing this by unobserving each toc item. However, in some cases this wasn't finishing fast enough and was trying to unobserve toc items after they'd already been destroyed - resulting in an exception being thrown.
This commit:
* Create the toc intersection observer on connect and assign it as a controller attribute.
* Disconnect the entire observer instead of unobserving each item.
> Fix: TOC observer race condition when disconnecting.

- app/components/project_submissions/like_component.html.erb
- app/components/project_submissions/like_component.rb
The purpose of the PR is to fix the contrast for submissions in light theme so it is easier to see
- Improves the contrast in like_component to AA level in light theme
Closes #4013
Note: In `def bg_color_class` I left the string empty so that the heart icon will inherit the color from the button
-   [x] The `Because` section summarizes the …
> Fix: Improve contrast for like_component

- app/controllers/project_submissions/flags_controller.rb
Because:
* The flags controller was refactored with our move to project submissions v2, but we forgot to switch the flag used with the discord notifier method to an instance variable.
> Fix: Notifying Discord when a flag is created.

- app/components/project_submissions/title_component.html.erb
Because:
* Hovering on the submission title in dark mode makes the title too dark to read.
This commit:
* Make the title link lighter when hovering on dark mode.
> Fix: V2 project submissions title hover in dark mode

- app/assets/images/icons/heart.svg
- app/components/project_submissions/like_component.html.erb
- app/components/project_submissions/like_component.rb
Because:
* A few tweaks to make the like component look more polished.
This commit:
* Use smaller font size for the like count
* Display like heart icon with no fill color when submission us unliked
Before:
After:
> Feature: Like styling tweaks.

- app/javascript/components/lesson-preview/components/share-button.jsx
This PR resolves the bug that @ManonLef reported with sharing lesson previews. The issue lives [here](https://github.com/TheOdinProject/theodinproject/issues/4014).
The Clipboard's API's usage across browser's is very inconsistent, which led to some of the changes in this PR.
- Adds a method to detect the browser in the Share Button component.
- Uses this method to determine how to write the preview link to the clipboard.
- If the browser is Safari, the ClipboardItem object is used.
- If the browser is anything else, the existing clipboard logic fires.
Closes #4014 
I'm not in love with having to detect the Browser the way I did, but felt this was the simplest solution for now. I found no documentation on using browser features as a more-sturdy approach.
-   [x] I have thoroughly read and …
> Fix: Resolves Lesson Preview share bug on Safari.

- db/fixtures/paths/full_stack_javascript/courses/react.rb
- db/fixtures/paths/full_stack_rails/courses/react.rb
It fixes the typo in the title 'The React Ecocsystem' in file `react.rb` in both full_stack_rails and full_stack_javascript folders. The file locations are: https://github.com/TheOdinProject/theodinproject/blob/5ae47989ad1d42ba0c045bac7534c8b3592b9e63/db/fixtures/paths/full_stack_rails/courses/react.rb#L90
https://github.com/TheOdinProject/theodinproject/blob/5ae47989ad1d42ba0c045bac7534c8b3592b9e63/db/fixtures/paths/full_stack_javascript/courses/react.rb#L90
- 'The React Ecocsystem' was changed to 'The React Ecosystem' in 6 instances, 3 in each file.
Closes #4034  …
> Fix: typo in title 'The React Ecocsystem'

- app/components/about_page/belief_component.html.erb
- app/components/course/badge_component.html.erb
- app/views/courses/progress/show.html.erb
- app/views/paths/index.html.erb
- app/views/static_pages/home/_curriculum.html.erb
- app/views/static_pages/home/_how_it_works.html.erb
- app/views/static_pages/home/_success_stories.html.erb
- app/views/static_pages/success_stories.html.erb
- config/locales/en.yml
Some images like course badges, illustrative images, and user avatars have `alt` not optimized for a11z.
1. For **Course Badge** images, their `alt="Ruby"` is changed to its course's name since these images are inside of links.
2. Except for the **flexbox of course badges** on landing page, their `alt=""` is set to empty since their siblings are headers with course names and their parents are links. Setting `alt` to course names would result in screen readers reading duplicate names.
3. For some **illustrative images**, their `alt=""` is set to empty since they are purely decorative and images are not conveying any meaningful messages because they have texts beside them.
4. **Users' avatars** under success stories now have `alt=""` because again they are accompanied by users' names as …
> Fix: improves a11y on images' alt attribute

- app/components/project_submissions/item_component.html.erb
- app/models/project_submission.rb
- app/views/project_submissions/_form.html.erb
- db/fixtures/lessons/database_lessons.rb
- db/fixtures/lessons/foundation_lessons.rb
- db/fixtures/lessons/getting_hired_lessons.rb
- db/fixtures/lessons/html_and_css_lessons.rb
- db/fixtures/lessons/javascript_lessons.rb
- db/fixtures/lessons/node_js_lessons.rb
- db/fixtures/lessons/react_lessons.rb
- db/fixtures/lessons/ruby_lessons.rb
- db/fixtures/lessons/ruby_on_rails_lessons.rb
- db/migrate/20230728225009_rename_lessons_has_preview_column_name.rb
- db/schema.rb
- lib/seeds/lesson_builder.rb
- spec/factories/lessons.rb
- spec/factories/project_submissions.rb
- spec/lib/seeds/lesson_builder_spec.rb
- spec/models/project_submission_spec.rb
- spec/queries/lesson_project_submissions_query_spec.rb
- spec/services/messages/dead_link_spec.rb
- spec/support/pages/project_submissions/form.rb
- spec/system/admin/flags_spec.rb
- spec/system/lesson_project_submissions/add_submission_spec.rb
- spec/system/user_notification_spec.rb
The new column name is Railsyer.
- Adds a migration to rename lesson.has_live_preview to lesson.previewable
- Changes all instances of has_live_preview to be previewable in the codebase.
Closes #4003 
As a matter of clarification, the task assumed the has_live_preview column was in the project_submissions table. It was actually on the lessons table.
- `Fix` - bug …
> Chore: Renames has_live_preview column to previewable.

- app/javascript/stylesheets/static-pages.css
- app/views/static_pages/support_us.html.erb
the OC widget is broken and looks bad on our homepage.
I asked for help in the OC slack channel, but couldn't resolve it, so for now let's just remove it.
If i find a solution that makes it look right, we can put it back.
> remove opencollective iframe from support page

- app/controllers/api/points_controller.rb
- spec/requests/api/points_spec.rb
Related to the issue in odin-bot-v2 issue of unauthenticated GET requests: https://github.com/TheOdinProject/odin-bot-v2/issues/175
Changes the controller to requrie autherization of API GET Requests
Closes #XXXXX
-   [ ] The `This PR` section has a bullet point list describing the …
> Chore: Update authentication requirement for API GET requests

- .github/workflows/heroku-review-app-on-label.yml
Because:
* The permissions set within the label were conflicting with the permissions we already have on our action settings, causing the job to fail.
* See https://github.com/TheOdinProject/theodinproject/actions/runs/5641371440/job/15279321454 and https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac
This commit:
* Remove the permissions key from the action.
> Fix: Create review app action

- app/javascript/stylesheets/lesson-content.css
Because:
* We recently changed to a smaller base font size for lesson content and the kbd padding needs tweaked to fit in.
Before
After
> Feature: Reduce kdb padding

- app/views/shared/_footer.html.erb
**_FLAIR_**
- Adds a little transition when hovering over the brand logos in the footer, which turns them to their brand colour
https://github.com/TheOdinProject/theodinproject/assets/76259120/fba1682c-9c3b-4fe9-b8d7-76f0adb7cfa7
-   [x] The `This PR` section has a bullet point …
> Feature: Add flair to brand logos

- app/components/project_submissions/item_component.html.erb
The current behaviour clicking "Live preview" button of a submitted project is to open a new tab with such url, but when no url is provided, now it opens a new tab of the current lesson page.
The correct behaviour should be NOT showing the "Live preview" button at all when the project submission does not provide a preview url.
- `/components/project_submissions/item_component.html.erb`: now renders the "Live preview" button only when this lesson has previewable projects, AND when this project submission has live preview url.
Closes #4059 
-   [x] The title of this PR follows the `keyword: brief description of change` format, using …
> Fix: project submissions do not show preview button without preview url

- app/views/shared/_footer.html.erb
Currently there is very little whitespace between the learn more and donate buttons, leading to a cramped feeling
- Gives them both a bit of horizontal margin …
> Give donate buttons slightly more horizontal space

- app/javascript/stylesheets/lesson-content.css
- tailwind.config.js
Current `lesson-note--warning` and `lesson-note--tip` etc has colours and icons not meeting good a11y standards.
- `lesson-note` div now has vertical margins with `my-4`.
- `lesson-note--tip`'s colour is now **blue**
- `lesson-note--warning` now has **orange** colour instead of red, and uses a warning icon
- `lesson-note--critical` variation is added, with colour of **red**, and uses a critical icon
- All of lesson-note sections now will render an icon **in front of the first descendent** element (assuming `h1-h6`) with the appropriate font-size. 
- Otherwise if the section **only has one descendent** (assuming only `p`), the icon will be rendered at the top left corner, with an enlarged `font-size: 1.8rem`
Closes #4045 
-   [x] I have thoroughly read and understand [The Odin Project …
> Fix: update lesson-note--variations styles a11y

- .circleci/config.yml
Because:
* Google have released a new version of chrome but have not released a new version of chrome-driver for it yet. 
* https://github.com/bullet-train-co/bullet_train/commit/4fbab7b61d9c1c18591be3ed1132a8d12fdb31df
> Fix: Circle CI Chrome install failing

- README.md
This PR adds an interactive screencast to the README that gives a general overview of the contributing guide to new collaborators. It helps people who may be new to contributing to this or any other repo get a sense of the code base and how to get it running locally. I used a new Scrimba feature that lets one make a video screencast with all the assets of a github repo.
- Added link to interactive screencast (scrim) to __README__ in the __Contributing__ section
Related to #3470
Here is a link to the screencast (scrim): https://scrimba.com/scrim/cEggQncE
I can also turn this into an image that links to the scrim video instead of text if you prefer that.
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/m …
> Feature: Add screencast link to README to giving overview for contributors

- app/controllers/project_submissions/flags_controller.rb
Because:
* When creating a flag on a review app it was returning a 500 response because the discord notifier isn't configured.
* We don't want testing flags on review apps to create noise in our Discord channel.
This commit:
* Do not run the discord notifier service if we're in the development environment or staging (review apps).
* Removes the json responses for creating flags, those were used from the removed react implementation of the flag form.
> Fix: Creating flags on review apps attempting to notify our flags Discord channel

- app/views/shared/_footer.html.erb
- config/routes/redirects.rb
- spec/requests/redirects_spec.rb
- Its useful to have a single canonical internal url for linking to the TOP blog, both for consistency and for being able to maintain and change it later on
- Redirects `/blog` to https://dev.to/theodinproject
- Changes the blog link in the footer to point to this new link
-  Adds a new test for this behavior
Closes #4108 
-   [x] The `Because` …
> Feature: Add redirect from /blog to the TOP blog

- app/admin/flags.rb
Because:
* Our legacy data don't have reasons populated.
> Fix: Admin Flags

- app/views/layouts/application.html.erb
Because:
* We need a pack stylesheet tag to load fontawesome styles.
* Fixes: https://github.com/TheOdinProject/theodinproject/issues/4133
> Fix: Note icons

- config/initializers/sidekiq.rb
Because:
* We upgraded our Redis instance on Heroku and need to add config for the verify mode.
* Closes: https://github.com/TheOdinProject/theodinproject/issues/4139
> Fix: Redis OpenSSL::SSL::SSLError

- app.json
Because:
* To bump Sidekiq to the latest version, we need an up to date version of Redis too.
> Chore: Switch our Redis provider to Heroku

- .github/ISSUE_TEMPLATE/chore.yaml
- I accidentally used a numbered list instead of check boxes in the placeholder
- Makes them actual check boxes
> Chore: chore.yaml: actually use checkboxes

- app/views/static_pages/support_us.html.erb
Because:
* It simplifies the markup
* Consistency with content on other pages.
This commit:
* Use the prose plugin on the base element
* Removes styling of individual elements
* Remove August expenses disclaimer; we have a couple of expenses in OC now.
> Feature: Use Tailwind prose plugin on support page

- app/components/application_component.rb
- app/components/card_component.html.erb
- app/components/card_component.rb
- app/components/content_container_component.html.erb
- spec/components/card_component_spec.rb
Because:
* We can simplify and use Rails 7's [`tag.attributes` helper](https://blog.saeloun.com/2021/05/05/rails-7-transform-hash-into-html-for-erb-interpolation/) instead
This commit:
* Removes `html_data_attributes_for` view component helper method.
* Removes data attributes parameter from card components - it wasn't used anywhere.
* Adds a couple of spec for testing cards with ids and custom classes
> Chore: Remove view component data attribute helper

- app/views/static_pages/support_us.html.erb
Resolves conflicts in #4196 due to forgetting `git pull upstream main`
Simple typo fix
- Replace `happend` with `happened`
N/A
N/A
-   [x] I have verified all tests and linters pass after making …
> Chore: Fix typo in support us page

- app/views/static_pages/home/_success_stories.html.erb
The success stories on the homepage don't align correctly.
Fixes the success stories' alignment on the homepage.
Closes https://github.com/TheOdinProject/theodinproject/issues/4162
-   [x] I …
> Fix success stories alignment

- db/fixtures/lessons/git_lessons.rb
- db/fixtures/paths/full_stack_javascript/courses/javascript.rb
- db/fixtures/paths/full_stack_rails/courses/ruby.rb
I'm adding a new lesson to the Intermediate Git section  
- I turned the working remotes section into its own lesson, so now this PR adds it to the Intermediate Git section.  
Closes (https://github.com/TheOdinProject/curriculum/pull/26118)
This pull request is a work in progress. I'm currently having syntax issues whenever I do the `bin/rails db:seed` command in my terminal. Suggestions to solve this problem would be greatly appreciated.  
- …
> Feature: adding working with remotes lesson

- app/views/lessons/project_submissions/_blank_state.html.erb
- app/views/lessons/project_submissions/create.turbo_stream.erb
- app/views/lessons/project_submissions/destroy.turbo_stream.erb
- app/views/lessons/project_submissions/index.html.erb
Because:
* It simplifies the code.
This commit:
* Adds an only pseudo class modifier to display the blank state it is the only item in the submissions list container, otherwise hide it.
* Remove the submissions blank state partial
* Removes the any if condition around submission items
* Removes the turbo stream to remove the blank state when adding a new submission
> Chore: Refactor submissions blank state to hide and display using a only pseudo class modifier

- .github/ISSUE_TEMPLATE/feature_request.yaml
- The placeholders are currently all over the place; one of them is a bug not a feature request, and two different feature requests are intermixed
- Harmonizes them to be about a single example feature request
-   [x] The `This PR` section has a bullet point list describing the …
> Feature: Feature Request template: harmonize placeholder text

- app/helpers/lessons_helper.rb
- app/views/lessons/show.html.erb
- spec/helpers/lessons_helper_spec.rb
- Currently learners have to copy/paste the URL when reporting an issue via the "report an issue" link
- Uses GitHub's ability to fill fields via url parameters to automatically fill it in when using the "report an issue" link
- Actually adds tests for "report an issue"
-   [x] The …
> Feature: Add lesson URL when reporting content

- app/javascript/application.js
- app/javascript/src/js/axiosWithCsrf.js
- package.json
- yarn.lock
Because:
* We no longer use it anywhere in the codebase. Any remote fetching is done with Rails/Request.js
> Chore: Remove Axios

- spec/rails_helper.rb
- Rspec by default truncates the output of failed tests, but it doesn't do so in an intelligent way, instead just taking half the allowed characters from the front and the other half from the back, and replacing all characters in between with a single ellipsis. This means that with some test errors (such as the ones I encountered in #4242), it can be impossible to see which part of a string isn't matching.
- Sets `max_formatted_output_length` to `nil`, which makes Rspec always print the full string
- …
> Chore: Don't restrict Rspec output length

- config/locales/team.yml
Because:
* It was broken.
This commit:
- Use Ada's GH avatar
> Fix: Ada's Avatar

- app/javascript/controllers/diagramming_controller.js
I noticed an issue recently with mermaid diagramming where the markdown was being rendered raw rather than drawing the actual diagram.
Steps to reproduce:
1. Visit the [Foundations Course](https://www.theodinproject.com/paths/foundations/courses/foundations)
2. Scroll to the lesson on Revisiting Rock Paper Scissors and click it
You should see the above screenshot content on the page (meaning the diagram isn't rendered properly). This only happens when visiting from a clicked link on the site. If you refresh or visit that page directly via its URL, the diagram will render properly. This made me think it was probably introduced alongside recent Turbo changes. Using `git bisect`, I tracked it down to #3845, which introduced Turbo Drive globally.
- Use method for lazier initialization of …
> Fix: Mermaid diagramming with internal navigation links

- spec/models/lesson_spec.rb
The word "candidate" for friendly_id's slug candidates was misspelled in a couple of places in the file
- Fixes spelling of candidate
Closes #XXXXX
-   [x] I have verified all tests and linters …
> Chore: Fix spelling of "candidate" in lesson model spec

- app/components/notification_component.html.erb
- app/javascript/application.js
- package.json
- yarn.lock
Because:
* Rails Ujs has been depreciated in favor of Hotwire.
> Chore: Remove Rails UJS

- app/views/lessons/show.html.erb
The "Improve on Github" link currently has this extra underline prefix. This change applies underline to the span directly so there's no overflow.
Before:
After:
- Fixes the extra underline before "Improve on Github" span
No open issues regarding this
NA
-   [x] The `This PR` …
> Chore: Remove extra underline before the "Improve on Github" link on every page

- app/views/lessons/show.html.erb
Changed ; to = on span class
With reference to #4291. I mistakenly used colon with the class attribute for the span because I got confused with the lines above it. I am sorry for this and have edited it to put the equals (=) sign with the class attribute. The PR was merged and now the underline doesn't show under the link.
Before:
After:
Corrects earlier mistake
- Corrects earlier mistake of using : instead of = 
NA
#4291 
- `Chore` - changes that …
> Chore: Show underline on "Improve on Github" link

- config/locales/team.yml
Because:
* It was accidentally changed in a previous PR
> Fix: Ada's Social Link

- db/fixtures/lessons/javascript_lessons.rb
- db/fixtures/lessons/ruby_lessons.rb
- db/fixtures/paths/full_stack_javascript/courses/javascript.rb
- db/fixtures/paths/full_stack_rails/courses/ruby.rb
Add HashMap lesson related to https://github.com/TheOdinProject/curriculum/pull/26518
@01zulfi I have tested this locally, but only one lesson can be shown at a time, either the lesson or the project in both paths. I suspect this is because of the 'create_uuid' value that I'm using instead of actual ID. I believe more job should be done to copy the first generated ID into the db before creating the newer one, unless I have used the `create_uuid` wrongly, and I should run some function to actually generated the ID before I proceed. 
Let me know if that is the problem and I will work on it.
- Add hashmap lesson and project to javascript db/fixture and db/path
- Add hashmap lesson and project to ruby db/fixture and db/path
-   [x] I have thoroughly read and understand [The Odin Project …
> Add hashmap lesson

- app/components/theme/switcher_component.yml
This pr addressed #4310  . I have updated the relevant code and fixed the text size in hamburger menu for dark/light mode.
> Fix: Correct text size in hamburger menu for dark/light mode

- app/assets/stylesheets/stylesheets/pagy.css
When visiting a full project submissions page the UX of dark mode was worse of light mode potentially due to some rules not applying.
- Gives the active page the lovely Odin gold colour just like light mode does.
- Attempts to harmonize link colour with the `Back to lesson` link at the top of the page.
- Makes disabled `Prev` / `Next` more visually distinct and intuitively disabled depending on the circumstances.
Closes #4307 
This is directly pertaining to the PR, rest is about the process more than anything else:
I duplicated the rules like `text-gold-500` because of specificity, otherwise it wouldn't work. Looks weird, feels weird but works just fine! Not sure if those `&:active` rules are even needed - it is only seen for a split second on slow network after clicking a link, right? …
> feat: improve project submisions dark mode

- db/fixtures/lessons/javascript_lessons.rb
Learners are currently being introduced to JSON via localstorage in the Todo List project. People thought it made sense to have the lesson on JSON occur before this point.
See also: [this PR](https://github.com/TheOdinProject/curriculum/pull/27086) on the curriculum repo.
- Moves the JSON lesson in the lesson fixtures.
- Updates the lesson's path to look in `/javascript/organizing_your_javascript_code/` rather than `/javascript/asynchronous_javascript_and_apis/`
Closes #XXXXX
- `Feature` - adds new or amends …
> Move JSON lesson earlier in JavaScript course

- .github/workflows/heroku-review-app-on-label.yml
Because:
- The manage-heroku-review-app maintainers have graciously made a change that will allow us to deploy pull requests from a forked origin.
- closes https://github.com/TheOdinProject/theodinproject/issues/3193
> Chore: Bump fastruby manage-heroku-review-app action

- app/assets/stylesheets/stylesheets/lesson-content.css
- tailwind.config.js
Certain lessons will embed a small icon image among the lesson text. These images need to be styled inline and not affect the surrounding text content with their margins.
Previously this was accomplished by using raw HTML tags in the curriculum markdown and using the `style` attribute  on the `<img>` tag. This doesn't pass the new Markdown lint rules in the curriculum Markdown files + it's a bit sketchy to do it that way imo.
See also: [this curriculum PR](https://github.com/TheOdinProject/curriculum/pull/27146)
- Adds new `.inline-img` class that can be applied to images that need to be displayed inline
- Adds the new `.inline-img` class to the `safelist` in the Tailwind config
XXXXX
Working example using the lesson preview tool locally:
-   [x] I have thoroughly read and understand [The …
> Chore: Add class for styling images inline

- app/admin/dashboard.rb
- app/controllers/github_webhooks_controller.rb
- config/application.rb
Because:
- The method for triggered them needed replaced with perform_later
- Missing config to use sidekiq as active jobs backend queue
> Fix: GitHub Webhook Lesson Import Job

- app/views/static_pages/about/_overview.html.erb
I was perusing the site and thought this tiny tweak could improve the readability of the user count on the About page.
* Formats the `User.count` value in the Learners card to read `1,231,839` instead of `1231839`
N/a
None …
> Feature: Add delimiter to user count on About page

- app/javascript/controllers/share_preview_controller.js
- app/views/lessons/previews/show.html.erb
Doing a hard refresh every time you make a change to the markdown you're testing is not the best experience and so is manually removing the markdown. Also, buttons in dark mode should be neatly highlighted!
- Adds input clearing functionality
- Fixes lack of hover background colour change in dark mode
nil …
> Feature: Add clear feature to Markdown preview page

- app/controllers/admin_v2/dashboard_controller.rb
- app/views/admin_v2/dashboard/show.html.erb
- config/routes.rb
- config/routes/admin_v2.rb
- spec/system/admin_v2/dashboard_spec.rb
Because:
- We need a separate area and namespace for the new admin so we can work on building it out while keeping the current admin system running in parallel.
This commit:
- Adds a admin_v2 routes file where all new admin routes will be kept - to separate them from the user facing routes.
- Adds an admin v2 dashboard controller and view
- Adds a basic system test to make sure everything is wired up correctly - this will be changed to a more useful admin sign in spec in a follow up PR.
Closes https://github.com/TheOdinProject/theodinproject/issues/4266
-   [x] The title of this PR follows the `keyword: brief description of change` …
> Feature: Separate Area for Admin v2

- app/components/project_submissions/like_component.html.erb
- app/components/project_submissions/like_component.rb
- app/views/project_submissions/likes/create.turbo_stream.erb
- app/views/project_submissions/likes/update.turbo_stream.erb
- spec/components/project_submissions/like_component_spec.rb
Because:
- Previously we were replacing the entire solutions component when liking/unliking. We did that to allow the list to auto sort based on the likes count of each solution. But we have recently replaced auto sorting with a user controlled manual sort. This allows us to be more efficient with likes, and only send the HTML we need over the wire.
This commit:
* Update the likes component instead of the solutions component with Turbo when liking/unliking
* Removes the likes/create.turbo_stream.html view. This must have accidentally got into the codebase at some point, we only use an update action with likes.
* Updates the like icon tool tip to show an appropriate message based on the state - before it was only showing "Like submission"
> Chore: Only Update Likes Component When Using Likes

- app/views/guides/community/show.html.erb
- app/views/guides/installations/index.html.erb
For both the installation guide index and the community guide show page, the full size for the card links isn't clickable. Here's a quick gif of what I mean:
Or, a link to the relevant pages to try for yourself:
- [installations](https://www.theodinproject.com/guides/installations)
- [community guides](https://www.theodinproject.com/guides/community)
- Styles these cards such that their links are clickable along the full height and width of the card.
Another quick gif with my changes:
Closes #XXXXX
- …
> Fix: Community & Installation Guides: Make full cards clickable

- app/controllers/admin_v2/base_controller.rb
- app/controllers/admin_v2/dashboard_controller.rb
- app/controllers/admin_v2/sessions_controller.rb
- app/models/admin_user.rb
- app/views/admin_v2/sessions/new.html.erb
- config/initializers/devise.rb
- config/routes/admin_v2.rb
- db/migrate/20231121083403_create_admin_users.rb
- db/schema.rb
- db/seeds/test_admins.rb
- spec/factories/admin_users.rb
- spec/models/admin_user_spec.rb
- spec/seeds/test_admins_spec.rb
- spec/system/admin_v2/dashboard_spec.rb
- spec/system/admin_v2/sign_in_spec.rb
Because:
- Separating admin users from normal users will make new admin more secure and robust to changes.
- closes: https://github.com/TheOdinProject/theodinproject/issues/4267
This commit:
- Adds admin_users
- Sets up devise for admins users
- Timeout admin users after 30 minutes
- Adds admin v2 sign in page
- Refactors admin v2 test for signing in
- Seeds dummy admin user
> Feature: Admin Users

- app/admin/flags.rb
There is a typo in the submission owner column of an flag: ower instead of owner
Corrects the typo.
> Fix: fix typo in flag column

- app/components/project_submissions/item_component.html.erb
- app/components/project_submissions/item_controller.js
- app/components/project_submissions/like_component.html.erb
- app/javascript/controllers/autosort_controller.js
- app/views/lessons/project_submissions/index.html.erb
Because:
- Previously, we would auto sort the solutions by their likes count when a like value changed.
- We removed it because it was thought to be redundant with manual sorting now available.
- A staff member mentioned missing it, so its back!
This commit:
- Only auto-sort if the current manual sort value is by like count - we don't want this kicking in when users want to see lists ordered by newest or oldest.
- Adds an item controller for solutions which will handle updating the sort code when a like value changes.
- Reinstate the removed auto sort controller which will now observe for any mutations to the sort codes of each item.
> Feature: Re-enable auto-sorting when like value changes.

- .babelrc
- app/assets/stylesheets/stylesheets/prism-theme.css
It can be helpful to copy long and involved bash commands 
- Adds a copy button to all code snippets
- Uses CSS to hide said button for all languages except bash
Closes #4416
Two notes:
- The way the CSS works, its hiding the entire toolbar, not just the copy button. The advantage of this is that we don't end up with a bunch of empty divs where the toolbar should be. The disadvantage is that if we ever add something else to that toolbar that would also get hidden, and it might not be immediately obvious why.
- I'm not entirely convinced by how the button actually works, but I think a possible redesign would be better suited for a follow up PR.
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTR …
> Feature: Add copy button to Bash codesnippets

- spec/support/cuprite.rb
Because:
- We use Cuprite for all our tests and don't need the JavaScript driver to be set separately.
> Chore: Remove Capybara JavaScript driver config

- app/views/layouts/admin_v2/_sidebar_nav.html.erb
- app/views/layouts/admin_v2/base.html.erb
Because:
- This inverts the sidebar and main content area background colors. The side bar is now gray and the main content area is white so it is the focal point
> Feature: Admin V2 layout color tweaks

- db/fixtures/lessons/ruby_on_rails_lessons.rb
- db/fixtures/paths/full_stack_rails/courses/rails.rb
There has been a new lesson added to the Rails course for migrations
See this curriculum PR: https://github.com/TheOdinProject/curriculum/pull/27692
- Adds new migrations lesson
- Runs `db:seed` task
Closes #XXXXX
-   [x] The `This PR` section has a bullet point list describing the …
> Add new lesson for migrations

- app/components/sort_component.html.erb
- app/components/sort_component.rb
- app/views/lessons/project_submissions/index.html.erb
Because:
- We only use the data attributes parameter to pass in the turbo frame the sort should change. But, the sort component is already inside of the turbo frame it changes.
> Chore: Remove data attributes from sort component

- app/controllers/admin_v2/base_controller.rb
- app/controllers/admin_v2/flags_controller.rb
- app/javascript/controllers/option_selector_controller.js
- app/views/admin_v2/flags/_actions.html.erb
- app/views/admin_v2/flags/show.html.erb
- config/locales/flag_actions.yml
- config/routes/admin_v2.rb
Because:
- We are building a new Admin system and need a flag details page where we can handle individual flags
- related to https://github.com/TheOdinProject/top-meta/issues/291
- 
This commit:
- Adds a flag details view
- Flag actions will be chosen from a select instead of displayed as separate buttons
New UI for selecting choosing what action to take:
https://github.com/TheOdinProject/theodinproject/assets/7963776/e32d73d0-c120-4784-bb05-65163de38a61
Overall Page:
> Feature: Admin v2 flag details page

- app/views/lessons/previews/_markdown_preview.html.erb
Because:
- We weren't sanitizing HTML within the outputted preview.
- Thanks to @Asartea for the report
This commit:
- Run the output through Rails's [sanitize](https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize) helper.
Notes
I tried a few different approaches with this:
Scrubbing the output before storing it proved to be very difficult. We're storing the content in markdown which makes it hard to differentiate legitimate script elements that will be displayed within code examples vs top level malicious script elements.
But, scrubbing the output before rendering should be enough to mitigate this issue.
> Fix: Script tags could execute in from previews

- app/assets/stylesheets/stylesheets/lesson-content.css
Applied a zoom-in cursor to all <code>img</code> tags that are direct children of anchor tags within lesson content.
- Adds a new TailWind CSS rule that appears when hovering over images.
Closes [#4474](https://github.com/TheOdinProject/theodinproject/issues/4474#issuecomment-2042571194)
bumps, etc …
> New Feature Add-on: Zoom-in Cursor

- app/components/markdown/preview_component.html.erb
- app/components/markdown/preview_component.rb
- app/views/lessons/previews/create.turbo_stream.erb
- app/views/lessons/previews/show.html.erb
Because:
- We are sanitising the input, but the Rails sanitiser does not include details and summary tags in its default safe list
- Closes: https://github.com/TheOdinProject/theodinproject/issues/4488
This commit:
- Overrides the Rails Sanitiser DEFAULT_ALLOWED_TAGS array to include details and summary tags
- Moves the preview partial into a component to group the allowed tags logic with the preview.
> Fix: Details and summary tags not working on preview tool

- .babelrc
Code examples using `ejs` weren't being given proper syntax highlighting.
- adds `"ejs"` to the `languages` array in the configuration for Prism (the library used to provide syntax highlighting).
Closes #4497 
-   [x] The `This PR` section has a bullet point list describing the …
> Fix: Add `ejs` to Prism language configuration

- app/components/markdown/preview_component.html.erb
- app/components/markdown/preview_component.rb
Because:
- Sections and their ids are being striped out of live previews by Rails sanitiser.
This commit:
- Allow sections and ids within live previews
> Fix: Sections not being inserted into liver preview

- app/javascript/controllers/lesson_toc_controller.js
Currently there's a null error that can happen in the toc stimulus controller if a lesson starts with a comment.
- Removes the possibility for this error by using optional chaining and an early return
Closes #4434 
-   [x] The `This PR` section has a bullet point list describing …
> Fix: Avoid null error in toc controller

- app/assets/stylesheets/stylesheets/typography.css
`.anchor-link`'s flex property was causing rendering issues with `<em>` children as per https://github.com/TheOdinProject/curriculum/issues/27831.
Only just discovered as #4507 let level 4 headings generate `> .anchor-link` and that sole heading was the only occurrence of having a child tag splitting up the text content.
Flex is no longer needed for `.anchor-link` (those headings are the only things that currently use the class).
- Removes flex-related properties from `.anchor-link`
- Positions `.anchor-link:hover::before` due to lack of flexbox
N/A
-   [x] The title of this PR follows the `keyword: brief description of change` …
> Fix: Remove flex from .anchor-link

- app/components/paths/select_button_component.html.erb
- app/components/paths/view_button_component.rb
- app/views/paths/index.html.erb
- spec/components/paths/select_button_component_spec.rb
- spec/system/select_path_spec.rb
A user might get confused about the current behavior of the "Resume" button in [All Paths](https://www.theodinproject.com/paths) (#3230, #4495).
Helps to differentiate a selected path from the rest by:
- Adding a "Selected" badge to the currently selected path.
- Keeping only one "Continue" button instead of "Resume" and "View" buttons to selected path.
**Note:** User needs to be logged in.
Closes #4495
- `Chore` - changes that have no user-facing …
> Feature: Add “Continue” button and badge for selected path

- db/fixtures/lessons/ruby_lessons.rb
- db/fixtures/paths/full_stack_rails/courses/ruby.rb
It'd be cool to have those lessons.
- Adds those lessons so they actually show up in the curriculum!
Related:
- https://github.com/TheOdinProject/curriculum/issues/27026
- https://github.com/TheOdinProject/curriculum/issues/27091
Please merge these first:
- https://github.com/TheOdinProject/curriculum/pull/28040
- https://github.com/TheOdinProject/curriculum/pull/28041
Also, for all the poor WSL2 souls that have failing rspec tests:
Do not follow Cliver error output. It won't be happy with a wslpath'd Chrome on Windows side. At least, it wasn't in my case. Just install Chrome in WSL2 and it'll be happy.
-   [x] The title of this PR …
> Feature: add Ruby Project Management and Linting lessons

- lib/tasks/data_migrations/remove_old_homepage_submissions.rake
Because:
- We previously changed the instructions to clarify the solution learners submit for the Homepage project should not be their personal portfolio. But, many of the older submission are still personal portfolios, and we think they could be causing some confusion with learners submitting new solutions.
This commit
- Adds a data migration to remove any solutions attached to the Homepage project that were submitted more than  3 months ago.
- …
> Chore: Remove old/invalid Homepage projects

- db/seeds.rb
- db/seeds/feature_flags.rb
Because:
- We have to manually add new feature flags through admin in every environment
- We will usually always  want feature flags to be enabled in dev and staging environments
- We have to manually delete old feature flags through the UI
This commit:
Adds a feature_flags seeds file where we can add new feature flags which will then...
- Add any new feature flags from the FEATURE_FLAGS array to Flipper
- Enable feature flags in dev and staging environments by default
- Remove any feature flags from Flipper that are no longer in the FEATURE_FLAGS array.
> Chore: Improve feature flags DX

- config/routes.rb
Because:
- We assign the root url to be the admin v2 dashboard when in the /admin_v2 namespace. This is causing the normal home url to not work as expected.
> Fix: Root url displaying rails welcome page after admin v2 sign in.

- app/components/alerts/flash_component.rb
- spec/components/alerts/flash_component_spec.rb
Because
- This is a bug with devise - https://github.com/heartcombo/devise/issues/1777
- When you are timed out, a flash will appear with "true" as the message
This commit
- Do not render the flash component if the type is "timedout"
> Fix: Phantom timeout flash notice.

- app/helpers/lessons_helper.rb
- app/views/lessons/show.html.erb
- spec/helpers/lessons_helper_spec.rb
It would be good to see when a lesson was last updated and go directly to the lesson's commit history to see the changelog, directly from the lesson page itself. This should help alleviate some confusion when something in the lesson changes when someone is midway through - they'll now be able to see that it was changed and find out what the change was, without having to go to GitHub of their own accord and navigate through the files to find out.
- Adds a github commit url helper method
- Adds a link to the GitHub lesson links at the end of a lesson page, showing the time of last update, and linking to that lesson's commit history.
Closes #XXXXX
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONT …
> Feature: Add link to lesson commit history

- app/controllers/admin_v2/announcements_controller.rb
- app/models/announcement.rb
- app/views/admin_v2/announcements/index.html.erb
- app/views/layouts/admin_v2/_sidebar_nav.html.erb
- config/routes/admin_v2.rb
- spec/models/announcement_spec.rb
Because:
- As an admin, I want to see and manage all announcements
- Relates to: https://github.com/TheOdinProject/top-meta/issues/291
This commit:
- Adds announcements controller and index view to admin v2
- Allows filtering between active and expired announcements
- Renames announcement `unexpired_messages` scope to `active`
> Feature: Admin v2 announcement index screen

- app/assets/images/icons/micro/chevron-left.svg
- app/components/Ui/back_link_component.html.erb
- app/components/Ui/back_link_component.rb
- app/views/admin_v2/flags/show.html.erb
Because:
- When I am on the flag details page, I want an easy way to get back to the flags index page through the UI, so I can navigate through flags quickly
- Relates to: https://github.com/TheOdinProject/top-meta/issues/291
This commit:
- Adds a back link component we can use on admin detail page
> Feature: Admin v2 back to flags link

- app/components/flags/action_button_component.html.erb
- app/models/flag.rb
- app/models/flags/action.rb
- app/views/admin_v2/flags/index.html.erb
- app/views/admin_v2/flags/show.html.erb
- config/locales/flag_actions.yml
- spec/models/flag_spec.rb
- spec/models/flags/action_spec.rb
Because:
- We were relying on primitive hashes for flag actions in multiple places.
> Chore: Refactor flag actions to use value objects

- app/views/users/_skill.html.erb
The purpose of this PR is that it reduces confusion on how much lessons each course have in the dashboard interface by displaying the number of lessons independently from the number of projects, as I already clarified in this issue I opened: #4542
* Courses viewed in the dashboard now follows the syntax of: "(Number of lessons) Lesson(s) / (Number of projects) Project(s)"
Closes #4542
- `Chore` - changes that have no user-facing value, refactors, …
> Feature: courses use the split lesson/project counts

- db/seeds/test_admins.rb
Because:
- The test admin we create in the seeds needed to be set to "active"
> Fix: Admin V2 - Test admin

- app/assets/images/icons/ellipsis-horizontal.svg
- app/assets/images/icons/envelope.svg
- app/components/Ui/dropdown/component.html.erb
- app/controllers/admin_v2/passwords_controller.rb
- app/controllers/admin_v2/team_members/password_resets_controller.rb
- app/views/admin_users/mailer/reset_password_instructions.html.erb
- app/views/admin_v2/passwords/edit.html.erb
- app/views/admin_v2/team/_member.html.erb
- config/locales/en.yml
- config/routes/admin_v2.rb
- spec/requests/admin_v2/passwords_spec.rb
- spec/requests/admin_v2/team_members/password_resets_spec.rb
Because:
- When an Admin team member forgets their password, I want to be able to send them a password reset email, so they can regain access to their account.
- Closes: https://github.com/TheOdinProject/theodinproject/issues/4588
This commit
- Adds a drop down menu to admin team member items
- Adds a reset password option to the menu
- Adds Devise's reset password instructions mailer template and tweaks it for TOP admins
- Blocks access to the new and create devise password actions for all users
> Feature: Admin v2 - reset team member passwords

- app/controllers/admin_v2/profile/password_controller.rb
- app/controllers/admin_v2/profile_controller.rb
- app/models/admin_user.rb
- app/views/admin_v2/profile/edit.html.erb
- app/views/layouts/admin_v2/_nav_bar.html.erb
- app/views/layouts/admin_v2/_sidebar_nav.html.erb
- app/views/layouts/admin_v2/base.html.erb
- config/locales/en.yml
- config/routes/admin_v2.rb
- spec/models/admin_user_spec.rb
- spec/requests/admin_v2/profile/password_spec.rb
- spec/requests/admin_v2/profile_spec.rb
Because:
- When I have an admin account, I want to have the ability to change my password, email address and name, so I can keep my information up to date and secure.
- Closes: https://github.com/TheOdinProject/theodinproject/issues/4591
This commit:
- Adds an edit profile page for the currently signed in admin
- Reuses the styling of the user settings page to save time
- Adds a profile passwords controller because there is no registerable devise controller admin user's can use.
> Feature: Admin V2 - Edit team member

- app/assets/images/icons/user-minus.svg
- app/components/Ui/dropdown/trigger_component.html.erb
- app/controllers/admin_v2/team_controller.rb
- app/controllers/admin_v2/team_members/deactivations_controller.rb
- app/models/admin_user.rb
- app/views/admin_v2/team/_member.html.erb
- app/views/admin_v2/team/show.html.erb
- config/locales/devise.en.yml
- config/routes/admin_v2.rb
- db/migrate/20240704102438_add_deactivated_to_admin_users.rb
- db/schema.rb
- spec/models/admin_user_spec.rb
- spec/system/admin_v2/deactivations_spec.rb
- spec/system/admin_v2/sign_in_and_out_spec.rb
Because:
- When someone leaves the team, we want to be able to deactivate their admin account, so they don't have access when they don't need it anymore.
- Closes: https://github.com/TheOdinProject/theodinproject/issues/4593
This commit:
- Adds a "Deactivate" option to active team member items on the team page
- Moves deactivated users to a "Deactivated team members" section of the team page
- Disallows sign in for deactivated users and displays an alert
> Feature: Admin V2 - Deactivate team members

- app/controllers/admin_v2/sessions_controller.rb
- spec/system/admin_v2/sign_in_and_out_spec.rb
Because:
- It was using the `after_sign_in_path_for` callback in the ApplicationController meant for learners sign in. It  tries to find a stored location and will fallback to the learners dashboard if there is none. Because we're signing in as an admin, it was failing an auth check when redirecting to the learners dashboard and redirecting again to the learner sign in page.
- closes: #4601 
This commit:
- Override the `after_sign_in_path_for` callback with admin specific behaviour when signing in as an admin.
> Fix: Admin v2 - Successful sign in sometimes redirects to learners sign in page

- app/assets/stylesheets/stylesheets/lesson-content.css
- app/assets/stylesheets/stylesheets/typography.css
Currently, all headings' `:hover::before` link icons are absolutely positioned with `left: -1.25rem`. This is completely fine for top-level headings, but for headings in note boxes, ends up looking like the below:
It would be nice for the link icon to be more visible on hover. I had difficulty adjusting positioning so all headings' link icons would render left of the full prose contents. Instead, I opted for making the note box icon invisible on heading hover instead.
- Adds CSS to visually hide note boxes' icons when their headings are hovered over.
N/A
N/A
-   [X] The title of this PR follows the `keyword: brief description of …
> Feature: Increase visibility of link icon when note-box headings hovered over

- app/views/lessons/show.html.erb
After the `xl` breakpoint, the lesson contents div and div housing course/lesson buttons and submissions are both left-aligned but different widths.
No changes needed below the `xl` breakpoint, as the lesson content is centred above the stretched buttons/submissions div.
- Adds `xl:max-w-prose` to the parent `<article>`
N/A
Current:
Unified:
- …
> Feature: Unify width of lesson content with submissions and buttons for wide viewport

- app/assets/images/icons/user-plus.svg
- app/controllers/admin_v2/team_members/reactivation_controller.rb
- app/models/admin_user.rb
- app/views/admin_v2/team/_member.html.erb
- app/views/admin_v2/team/show.html.erb
- config/routes/admin_v2.rb
- db/migrate/20240709052504_add_reactivation_to_admin_user.rb
- db/schema.rb
- spec/models/admin_user_spec.rb
- spec/requests/admin_v2/team_members/reactivation_spec.rb
- spec/system/admin_v2/deactivations_spec.rb
- spec/system/admin_v2/reactivations_spec.rb
Because:
- When an old team member returns to the team, I want to reactivate them as an admin, so they can regain access to the admin area.
- Closes: #4608 
This commit:
- Adds a "Reactivate" action to deactivated admin team members
- Reactivated team members are sent an invite email and can log in again.
> Feature: Admin V2 - Reactivate team members

- app/components/charts/horizontal_bar_chart_component.html.erb
- app/components/charts/horizontal_bar_chart_component.rb
- app/components/charts/line_chart_component.rb
- app/controllers/admin_v2/reports/paths_controller.rb
- app/javascript/controllers/chart_controller.js
- app/jobs/refresh_materialized_views_job.rb
- app/models/concerns/materialized_view.rb
- app/models/path.rb
- app/models/reports/all_lesson_completions_day_stat.rb
- app/models/reports/path_lesson_completions_day_stat.rb
- app/models/user.rb
- app/views/admin_v2/dashboard/show.html.erb
- app/views/admin_v2/reports/paths/show.html.erb
- app/views/layouts/admin_v2/_sidebar_nav.html.erb
- config/routes/admin_v2.rb
- db/migrate/20240712073547_create_path_lesson_completions_day_stats.rb
- db/migrate/20240713134127_add_users_counter_to_paths.rb
- db/schema.rb
- db/views/path_lesson_completions_day_stats_v01.sql
- spec/components/charts/horizontal_bar_chart_component_spec.rb
- spec/jobs/refresh_materialized_views_job_spec.rb
- spec/models/path_spec.rb
- spec/models/reports/all_lesson_completions_day_stat_spec.rb
- spec/models/reports/path_lesson_completions_day_stat_spec.rb
- spec/requests/admin_v2/reports/paths_spec.rb
Because:
- When I need to find something out about a path, I want to go to a path analytics page on admin that can tell me basic stats about the path.
This commit:
- Adds analytics report pages for all paths
- Displays the lesson, courses and enrolments count for the path in cards
- Displays lesson completions for each lesson in the path within a horizontal bar graph
- Allows admins to see path lesson completions in the graph over a period of time
- Allows admins to filter the path lesson completions by course
https://github.com/user-attachments/assets/a66c764f-2efa-4140-8b0c-a5d2b1cf8523
> Feature: Admin V2 - Path Analytics

- app/models/lesson_completion.rb
- app/models/like.rb
- app/models/project_submission.rb
- app/models/user.rb
- app/services/notifications/daily_summary.rb
- spec/models/lesson_completion_spec.rb
- spec/models/like_spec.rb
- spec/models/project_submission_spec.rb
- spec/models/user_spec.rb
- spec/services/notifications/daily_summary_spec.rb
Because:
- Currently, we are running this task at 11:30pm UTC which is not a full and true reflection of that day's stats.
This commit:
- Assumes the daily summary task runs after 12am UTC - the cron job has been changed to 00:30 UTC on Heroku
- Changes the daily summary task to account for users, lesson completions, projects and likes created yesterday
- Gives each model a `x_on` scope to fetch all records created on a given date.
> Feature: Run daily summary after 12am UTC

- app/components/sections/lesson_component.html.erb
- app/models/lesson.rb
- app/views/lessons/_header.html.erb
- spec/models/lesson_spec.rb
testing if adding a lesson chip is viable
adds "new" lesson chip
Closes #XXXXX
-   [ ] If this PR addresses an open …
> feat: new lesson chip

- app/controllers/admin_v2/team_members/deactivation_controller.rb
- app/views/admin_v2/team/_member.html.erb
- config/routes/admin_v2.rb
- spec/system/admin_v2/deactivations_spec.rb
Because:
- It makes more sense for deactivation to be an update action instead of create.
- It can be changed to a singular resource because we can get the team member id through the parent route.
> Chore: Change deactivations controller to singular resource

- app/controllers/admin_v2/team_members/resend_invitation_controller.rb
- app/views/admin_v2/team/_member.html.erb
- config/routes/admin_v2.rb
- spec/requests/admin_v2/team_members/resend_invitation_spec.rb
Because:
- When a pending team member did not receive their invite or cannot accept the initial invite, I want to send it again, so they can join the team.
- Closes: https://github.com/TheOdinProject/theodinproject/issues/4627
This commit:
- Adds a "Resend invite" option to pending team member drop downs.
> Feature: Admin v2 - Resend Invite

- app/components/charts/line_chart_component.html.erb
- app/components/charts/line_chart_component.rb
- app/controllers/admin_v2/reports/users_controller.rb
- app/javascript/controllers/chart_controller.js
- app/javascript/controllers/chart_with_crosshair_controller.js
- app/jobs/refresh_materialized_views_job.rb
- app/models/reports/user_sign_ups_day_stat.rb
- app/models/user.rb
- app/views/admin_v2/dashboard/show.html.erb
- app/views/admin_v2/reports/lesson_completions/show.html.erb
- app/views/admin_v2/reports/paths/show.html.erb
- app/views/admin_v2/reports/users/index.html.erb
- app/views/layouts/admin_v2/_sidebar_nav.html.erb
- config/initializers/date_time_formats.rb
- config/routes/admin_v2.rb
- db/migrate/20240719045454_create_user_sign_ups_day_stats.rb
- db/schema.rb
- db/views/user_sign_ups_day_stats_v01.sql
- package.json
- spec/jobs/refresh_materialized_views_job_spec.rb
- spec/models/reports/user_sign_ups_day_stat_spec.rb
- spec/models/user_spec.rb
- spec/requests/admin_v2/reports/users_spec.rb
- yarn.lock
Because:
- When I want to see how many users have signed up in a given period of time, I want to view that data on a graph, so I can get and read the data easier.
This commit:
- Adds a user analytics page
- Adds a database view to cache the query for sign ups everyday
- Display sign ups in a line graph
- Includes many graph UI improvements
- Adds a year option to line graph filters
- Improved styling with graph colors
- Use cross hairs for the points on line graphs - better UX, allows zooming into segments of the graph
> Feature: Admin v2 - Users analytics

- spec/system/admin_v2/announcements_spec.rb
Because:
- We were getting a warning in the test output about it
> Chore: Wrap delete announcement action within a accept_confirm

- app/components/charts/line_chart_component.rb
Because:
- The y-axis was starting at the datasets smallest value
> Feature: Admin V2 - Begin line graphs at zero

- app/views/admin_v2/team/_member.html.erb
Because:
- When I accidentally click the wrong option, I want to confirm that option was correct, so I don't do something I didn't intend to do.
> Feature: Admin v2 - Add confirms around team member actions

- app/components/project_submissions/item_component.html.erb
- app/components/project_submissions/user_solution_component.html.erb
Because:
- The width and height was removed from the svg files in a previous commit.
This commit:
- Pass width and height classes when rendering the svg inline
> Fix: Invisible vertical ellipsis buttons

- app/controllers/admin_v2/team_members/two_factor_reset_controller.rb
- app/views/public_activity/admin_user/_two_factor_reset.html.erb
Because:
- When I reset someones 2fa, I want an activity to be created, so it is auditable.
- Closes https://github.com/TheOdinProject/theodinproject/issues/4644
> Feature: Admin V2 - Create an activity when 2fa is reset for a team member

- app/models/flags/actions/notify_user.rb
- app/models/notifications/flag_notification.rb
- app/services/admin/flags/notify_user.rb
- spec/models/flags/actions/notify_user_spec.rb
- spec/models/notifications/flag_notification_spec.rb
Because:
- This is better suited as a model rather than a top level concept in the root of the app directory.
> Chore: Move notifications into models directory

- app/controllers/github/webhooks_controller.rb
- app/jobs/lessons/import_all_content_job.rb
- app/models/github/lesson_content_importer.rb
- app/models/github/push_event.rb
- app/models/lesson.rb
- config/routes.rb
- spec/jobs/lessons/import_all_content_job_spec.rb
- spec/models/github/lesson_content_importer_spec.rb
- spec/models/github/push_event_spec.rb
- spec/models/lesson_spec.rb
Because:
- We can put all our GitHub services and models together, making them easier to find.
This commit:
- Move lesson content importer into Github namespace in the models directory
- Move GitHub push event adapter into the Github namespace in the models directory
- Move GitHub webhooks controller into a Github namespace in the controllers directory
> Chore: Add Github namespace

- app/controllers/admin_v2/invitations_controller.rb
- app/controllers/admin_v2/team_members_controller.rb
- app/models/admin_user.rb
- app/views/admin_v2/team/_member.html.erb
- app/views/public_activity/admin_user/_invited.html.erb
- app/views/public_activity/admin_user/_removed.html.erb
- spec/models/admin_user_spec.rb
- spec/requests/admin_v2/team_members_spec.rb
Because:
- When I accidentally add someone to the admin team, I want to be able to remove that team member immediately, so someone doesn't gain access to admin when they shouldn't.
> Feature: Admin V2 - Delete pending team members

- config/initializers/sidekiq.rb
Because:
- We were getting "Sidekiq connecting to Redis" output in the test output
> Chore: Silence Sidekiq logs in test output

- app/views/layouts/admin_v2/_sidebar_nav.html.erb
- config/routes/admin_v2.rb
Because:
- When I want to view Sidekiq or feature flags, I want an easy way to get to them, so I don't need to memorise the URLs.
- Closes: https://github.com/TheOdinProject/theodinproject/issues/4659
> Feature: Admin V2 - Nav links for Sidekiq and feature flags

- spec/system/admin_v2/deactivations_spec.rb
- spec/system/admin_v2/reactivations_spec.rb
Because:
- We need to wrap any links that have a confirm alert in `accept_confirm do ...`
> Chore: handle accept_prompt warnings in specs

- app/builders/tailwind_form_builder.rb
- app/controllers/admin_v2/reports/lesson_completions_controller.rb
- app/controllers/admin_v2/reports/users_controller.rb
- app/models/reports/period.rb
- app/views/admin_v2/reports/_date_filters.html.erb
- app/views/admin_v2/reports/lesson_completions/show.html.erb
- app/views/admin_v2/reports/users/index.html.erb
- config/utility_classes.yml
- spec/builders/__snapshots__/tailwind_form_builder/select.snap
- spec/builders/tailwind_form_builder_spec.rb
- spec/models/reports/period_spec.rb
Because:
- Save space for more filters
This commit:
- Extracts date filters to a partial so they can be used in both lesson completions and user reports
- Adds a period value object to sanitise period input
- Adds select field styling to our tailwind form builder
> Feature: Change period filter buttons to a select field

- Gemfile
- Gemfile.lock
- app/controllers/admin_v2/base_controller.rb
- app/controllers/admin_v2/team_members/deactivation_controller.rb
- app/controllers/admin_v2/team_members/reactivation_controller.rb
- app/controllers/admin_v2/team_members/resend_invitation_controller.rb
- app/controllers/admin_v2/team_members_controller.rb
- app/models/admin_user.rb
- app/models/current.rb
- app/views/admin_v2/team_members/_member.html.erb
- app/views/public_activity/admin_user/_activated.html.erb
- app/views/public_activity/admin_user/_pending_reactivation.html.erb
- db/migrate/20240726181456_add_reactivated_to_admin_user.rb
- db/schema.rb
- db/seeds/test_admins.rb
- spec/factories/admin_users.rb
- spec/models/admin_user_spec.rb
- spec/requests/admin_v2/team_members/deactivation_spec.rb
- spec/requests/admin_v2/team_members/reactivation_spec.rb
- spec/requests/admin_v2/team_members/resend_invitation_spec.rb
- spec/requests/admin_v2/team_members_spec.rb
- spec/requests/admin_v2/two_factor_authentication_spec.rb
- spec/support/aasm.rb
- spec/support/shared_examples/shared_examples_for_authenticatable_with_two_factor.rb
- spec/system/admin_v2/deactivations_spec.rb
- spec/system/admin_v2/invitations_spec.rb
- spec/system/admin_v2/reactivations_spec.rb
- spec/system/admin_v2/sign_in_and_out_spec.rb
Because:
- A state machine will make it easier to reason about state transitions and make sure the state change rules are enforced
- Closes: https://github.com/TheOdinProject/theodinproject/issues/4658
This commit:
- Adds AASM for the state machine DSL
- Renames admin user active status to "activated" to be more uniform with the other statuses
- Adds a new "pending reactivation" status to hold reactivated users until they set new password and 2fa credentials
- Creates activities automatically when an admin user status changes
- Adds status traits to admin user factory
- Adds current attributes to set the admin user so we can use the current admin user when creating an activity from a model.
> Chore: Use state machine with admin user

- app/controllers/admin_v2/team_members/password_resets_controller.rb
- app/views/public_activity/admin_user/_password_reset.html.erb
Because:
- When I reset an admin team members password, I want an activity to be created, so it is auditable.
- Closes: https://github.com/TheOdinProject/theodinproject/issues/4661
> Feature: Admin V2 - Create activity when password reset email is sent

- app/controllers/admin_v2/team_members/two_factor_reset_controller.rb
- app/models/admin_user.rb
- spec/models/admin_user_spec.rb
- spec/requests/admin_v2/team_members/two_factor_reset_spec.rb
Because:
- Previously, the `reset_two_factor` method also set an admin to pending. But that was removed.
This commit:
- Explicitly resets the admin to pending when this controller action is triggered.
- More test coverage around the rest 2fa controller
> Fix: Admin v2 - Resetting 2fa should set admin user to pending

- app/models/admin_user.rb
- app/models/flag.rb
- app/models/null/admin_user.rb
- app/views/admin_v2/flags/index.html.erb
- app/views/admin_v2/flags/show.html.erb
- app/views/admin_v2/invitations/new.html.erb
- db/migrate/20240729171320_add_admin_user_foreign_key_to_flags.rb
- db/schema.rb
- spec/models/admin_user_spec.rb
- spec/models/flag_spec.rb
Because
- We need to know who resolved a flag on Admin v2
This commit:
- Adds an admin_user foreign key to flags
- Adds a null admin user object to populate the name of flags handled by admins who have been deleted
- Adds resolved by column to the flags index table
- Adds a resolved by detail to the flag show page
> Chore: Add Admin User Foreign Key to Flags

- app/models/admin_user.rb
- db/migrate/20240730082143_remove_reactivated_by_from_admin_user.rb
- db/schema.rb
Because:
- We have activities to track who reactivated a team member instead.
> Chore: Remove reactivated_by from admin users

- app/controllers/admin_v2/announcements_controller.rb
- app/models/announcement.rb
- app/views/admin_v2/announcements/index.html.erb
- app/views/admin_v2/announcements/show.html.erb
- db/migrate/20240730080010_add_admin_user_to_announcement.rb
- db/schema.rb
- spec/models/announcement_spec.rb
Because:
- We need to know who created announcements
This commit:
- Adds a admin_user foreign key to announcements
- Returns a null admin user for older announcements created by admins that have since been deleted
- Displays the admin who created the announcement on the announcement index and show pages.
> Chore: Add admin user foreign key to announcements

- config/environments/test.rb
- this is causing tests to fail (see e.g. https://github.com/TheOdinProject/theodinproject/pull/4677), including on a no op
- Copies the active record keys from `development.rb` to `test.rb`
- …
> Fix: Add Active Record Encryption keys to test enviroment

- app/controllers/admin_v2/announcements_controller.rb
- app/models/announcement.rb
Because:
- Announcements are seen by everyone and need to be auditable
This commit:
- Creates activities when an announcement is created and updated.
- We aren't exposing these activities in the UI yet, but may do in the future.
> Chore: Add created and updated activities on announcements

- app/controllers/admin_v2/invitations_controller.rb
- app/controllers/admin_v2/team_members/role_controller.rb
- app/models/admin_user.rb
- app/views/admin_v2/invitations/new.html.erb
- app/views/admin_v2/team_members/_member.html.erb
- app/views/admin_v2/team_members/role/edit.html.erb
- app/views/admin_v2/team_members/role/update.turbo_stream.erb
- config/routes/admin_v2.rb
- db/migrate/20240801070241_add_roles_to_admin_users.rb
- db/schema.rb
- db/seeds/test_admins.rb
- spec/factories/admin_users.rb
- spec/models/admin_user_spec.rb
- spec/requests/admin_v2/invitations_spec.rb
- spec/requests/admin_v2/team_members/role_spec.rb
- spec/system/admin_v2/invitations_spec.rb
Because:
- We will use roles for permissions
This commit:
- Adds role enum to admin user with  moderator, maintainer and core as the possible values
- Allows role to be selected when inviting a new team member
- Adds a new team member option for changing a role.
- Display the team member role and email address on their team member item so an inviter can come back later and check they entered the correct information
> Feature: Admin v2 - Team member roles

- db/migrate/20240802085933_add_null_constraint_to_admin_user_role.rb
- db/schema.rb
- spec/requests/admin_v2/invitations_spec.rb
Because:
- Now that we have roles populated for existing admins, we can make sure this attribute is never null for future admins.
> Chore: Add null constraint to admin user role

- app/components/Ui/dropdown/component.rb
- app/controllers/admin_v2/invitations_controller.rb
- app/controllers/admin_v2/team_members/deactivation_controller.rb
- app/controllers/admin_v2/team_members/reactivation_controller.rb
- app/controllers/admin_v2/team_members/role_controller.rb
- app/controllers/admin_v2/team_members/two_factor_reset_controller.rb
- app/policies/admin_user_policy.rb
- app/views/admin_v2/passwords/edit.html.erb
- app/views/admin_v2/team_members/_member.html.erb
- app/views/admin_v2/team_members/index.html.erb
- spec/policies/admin_user_policy_spec.rb
- spec/requests/admin_v2/invitations_spec.rb
- spec/requests/admin_v2/team_members/deactivation_spec.rb
- spec/requests/admin_v2/team_members/reactivation_spec.rb
- spec/requests/admin_v2/team_members/resend_invitation_spec.rb
- spec/requests/admin_v2/team_members/role_spec.rb
- spec/requests/admin_v2/team_members/two_factor_reset_spec.rb
Because:
- We'll be following principle of least privilege for security - users should only be able to perform actions they need to.
This commit:
- Adds a admin user policy to encapsulate admin user permissions.
- Wraps actions in the team page with conditionals to enable and disable sensitive actions
- Adds before actions to applicable controllers to check if admins are authorised to perform that action
> Feature: Admin V2 - role permissions

- app/components/charts/line_chart_component.rb
- app/views/admin_v2/dashboard/show.html.erb
- app/views/admin_v2/reports/lesson_completions/show.html.erb
- app/views/admin_v2/reports/paths/show.html.erb
- app/views/admin_v2/reports/users/index.html.erb
- config/initializers/date_time_formats.rb
- Puts graphs within a border so they will be aligned with date navigation buttons
- Include totals within the graphs, so you can get an overview of the total for that period.
- Adds loading spinners as the default state of the graphs lazily loaded on the dashboard
> Feature: Admin V2 - Graph styling tweaks

- app/javascript/controllers/modal_controller.js
Because:
- There is a very slight layout shift when opening/closing modals.
> Fix: Modal layout shift

- db/seeds.rb
- db/seeds/test_users_and_admins.rb
- spec/seeds/test_users_and_admins_spec.rb
Because:
- Admins are separate from users.
This commit:
- Rename the file to communicate it create test users and admins instead of just admins.
> Chore: Remove admin attribute from test users

- app/assets/stylesheets/application.tailwind.css
- package.json
- postcss.config.js
- yarn.lock
Because:
Previously we had to run two css build scripts:
- One for our tailwind styles
- One for active admin
This required us to add packages like css-nano to handle the two builds. But now that Active Admin is gone, we can simplify this to one build.
This commit:
- Remove css-nano
- Rename the application stylesheet bundler to tailwind and pass postcss as a modifier in the script
> Chore: Simplify how our CSS is being loaded

- app/views/lessons/_header.html.erb
The h1 heading in the Intermediate CSS Concepts section's Custom Properties lesson was not centered correctly.
- updates the class of the h1 container from `sm:flex-row` to `xl:flex-row`.
Closes #4654
This issue was discussed in the [Odin Project Discord server](https://discord.com/channels/505093832157691914/700355756188368926) in the #contribution-opportunies channel.
- `Chore` - changes that have no user-facing value, refactors, dependency …
> fix: center h1 title on large screen(#4654)

- lib/tasks/data_migrations/populate_flag_resolvers.rake
- lib/tasks/data_migrations/update_legacy_flag_reasons.rake
Because:
- We want to keep an accurate record of who resolved flags
This commit:
- Adds a data migration to set legacy flags with a reason "4" to "40". These flags fail validation and can't be updated without this.
- Adds a data migration mapping old user resolvers to admin users and sets the admin user foreign key for the appropriate flags
> Chore: Migrate old flag resolvers to admin users

- app/models/admin_user.rb
- app/models/flag.rb
- app/views/admin/flags/index.html.erb
- app/views/admin/flags/show.html.erb
- db/migrate/20240805080849_rename_flag_admin_user_to_resolved_by.rb
- db/schema.rb
- spec/factories/flags.rb
- spec/models/admin_user_spec.rb
- spec/models/flag_spec.rb
Because:
- This is the domain name we used for this association before and it communicates the admin users relationship to the flag better.
This commit:
- Removes legacy resolved_by_id column from flags
- Renames admin user column on flags to resolved_by_id
- Validates that resolved flags should always have a resolved_by set
> Chore: Rename flag admin user association to resolved by

- app/controllers/admin/announcements_controller.rb
- app/models/admin_user.rb
- app/models/announcement.rb
- app/models/null/admin_user.rb
- db/migrate/20240806054115_rename_announcement_admin_user.rb
- db/schema.rb
- spec/factories/announcements.rb
- spec/models/admin_user_spec.rb
- spec/models/announcement_spec.rb
Because:
- Created by better represents the admins relationship with the announcement.
This commit:
- Removes announcement user_id column
- Adds a null constraint to the created by foreign key
- Removes null admin user - we don't need it anymore.
> Feature: Rename announcement admin user association to created_by

- app/models/flag.rb
- app/models/user.rb
- app/views/admin/flags/index.html.erb
- app/views/admin/flags/show.html.erb
- db/migrate/20240806061546_rename_flag_taken_action_to_action_taken.rb
- db/schema.rb
- spec/models/flag_spec.rb
- spec/models/flags/actions/ban_spec.rb
- spec/models/flags/actions/dismiss_spec.rb
- spec/models/flags/actions/notify_user_spec.rb
- spec/models/flags/actions/remove_project_submission_spec.rb
- spec/models/user_spec.rb
Because:
- We are using action_taken in the UI. Using the same name makes it easier and safer to pass actions through the stack.
> Chore: Rename flag taken_action column to action_taken

- app/models/admin_user.rb
- spec/models/admin_user_spec.rb
Because:
- Instead of deleting, We want to always deactivate admins that have handled flags or created announcements.
This commit:
- Changes admin user flag and announcements associations to use restrict_with_exception as their dependent option
- This will raise an `ActiveRecord::DeleteRestrictionError` exception if we try to delete a user that has any  records associated with them
> Feature: Admin users with associations should never be deleted

- app/controllers/concerns/current_theme.rb
Because:
- We're seeing quite a few error reports in Sentry about the theme name being nil for mac users.
This commit:
- Returns the light theme as the default if the theme cannot be found from the users theme cookie.
> Fix: Current theme not set for some users

- package.json
Because:
- We're not using it directly anywhere
> Chore: Remove lodash

- yarn.lock
Because:
- It was removed from package.json but still in the yarn.lock file
> Chore: Remove Hint.css

- package.json
- yarn.lock
Because:
- We once used this for hashing lesson preview content and appending that to the url. But that was limited and we started saving previews and assigning them uuids instead. This package no longer needed.
> Chore: Remove js-base64 package

- db/fixtures/lessons/javascript_lessons.rb
- db/fixtures/paths/full_stack_javascript/courses/javascript.rb
- db/fixtures/paths/full_stack_rails/courses/javascript.rb
In [curriculum #27953](https://github.com/TheOdinProject/curriculum/pull/27953) and [curriculum #27962](https://github.com/TheOdinProject/curriculum/pull/27962), two new lessons are being added as part of a larger ESM/Webpack rewrite + split.
- Adds the new Revisiting Webpack lesson details
- Adds the new npm lesson details
- Adds these new lesson to both pathways' lesson lists
N/A
This will be something to only be merged after the following 3 PRs have been merged:
- (https://github.com/TheOdinProject/curriculum/pull/27953)
- (https://github.com/TheOdinProject/curriculum/pull/27961)
- (https://github.com/TheOdinProject/curriculum/pull/27962)
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIB …
> Feature: Add new lessons from ESM/Webpack restructure to both pathways

- .buildcache
- .github/workflows/ci.yml
- .slugcleanup
- .slugignore
- lib/tasks/heroku.rake
Because:
- We used caching buildpacks to cache assets and dependencies to speed up deployments. But they don't make a difference anymore. The Node and Heroku buildpacks already do a good enough job at caching.
- Yarn install runs twice because we are using both the Node and Ruby buildpacks - adding a few seconds onto our time to deploy
- We use a slug clean up buildpack to make sure our slug size on heroku does not grow beyond the 300mb soft limit. With our switch to Js-bundling for assets, we needed to change the javascript directory that will be cleaned up.
This commit:
- Remove the .buildcache file as we aren't using the caching buildpacks its used with anymore.
- Adds `SKIP_YARN_INSTALL` env var to CI, review apps, and the production environment. This will skip the yarn install task …
> Chore: Optimise Heroku deploy

- package.json
- yarn.lock
Because:
- We were a few patch versions behind
> Chore: Bump Sortablejs

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- bin/ci_spec
- config/database.yml
- config/environments/test.rb
- db/schema.rb
- spec/services/notifications/flag_submission_spec.rb
- spec/support/capybara.rb
Because:
- It shaves a minute off our CI completion time 🚤 
This commit:
- Adds parallel tests gem
- Split tests in groups on Github actions using their matrix feature
- Change test setup to allow for dynamic ports based on the parallel test number thats is being used
> Chore: Run tests in parallel on CI

- spec/requests/paths_spec.rb
Because:
- It was 'Static pages' but should be 'Paths'
> Fix: Paths request spec describe title

- app/models/github/lesson_content_importer.rb
- spec/models/github/lesson_content_importer_spec.rb
Because:
- If your GitHub Api token is incorrect, the lesson import task will silently fail. It will run through every lesson, incrementing the progress bar, and look as if it has succeeded. Resulting in a lot of confusion when you go to a lesson page and the content is blank.
This commit:
- Abort the lesson import task if an incorrect GitHub API token is provided and print out a message about what might have gone wrong.
> Chore: Abort lesson import when bad credentials are provided

- spec/support/cuprite.rb
Because:
- We are seeing intermittent failures with `Ferrum::NoSuchTargetError` being raised.
This commit:
- It appears to be an issue with the latest version of Ferrum, configuring it with `flatten: false` is reported to fix it.
> Fix: Flaky CI test runs

- app/components/Ui/badge_component.rb
Because:
- Badges didn't look very good on dark mode, they were too bright 🔆
> Feature: Optimise dark mode styling for badges

- spec/requests/admin/team_members/password_resets_spec.rb
- spec/requests/admin/team_members/reactivation_spec.rb
- spec/requests/admin/team_members/resend_invitation_spec.rb
- spec/requests/users/registrations_spec.rb
- spec/support/mail.rb
- spec/support/retry.rb
Because:
- Emails appear to be leaking between parallel tests
This commit:
- Use matchers included with the Mail gem as they are meant to be more reliable
- The mail matchers expect to be run against the subject in request specs, I've opted to disable the named subject cop to instead of moving the requests into subjects to keep all set up within tests and keep them as readable as possible.
> Fix: Flaky tests that use ActionMailer

- app/assets/images/icons/bars-3.svg
- app/assets/images/icons/ham-burger.svg
- app/assets/images/icons/x.svg
- app/components/announcement_component.html.erb
- app/components/modal_component.html.erb
- app/views/layouts/admin/_nav_bar.html.erb
- app/views/layouts/admin/_sidebar_nav.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_off_canvas_menu.html.erb
Because:
- We had a few icons that were using plain SVG syntax in the views.
This commit:
- Renames ham-burger.svg to bars-3.svg to bring it inline with Heroicons naming
- Removes the x.svg icon - its the exact same as the x-mark.svg icon
- Replace open menu button SVGs with the inline_svg helper
- Replace closer and dismiss button SVGs with the inline_svg helper
> Chore: Use inline-svg helper with all applicable SVGs

- package.json
- yarn.lock
Because:
- It fixes a JS error with older iOS versions.
> Chore: Bump chartjs-plugin-tailwindcss-colors

- bin/test
Some people (*coughcough*) somehow had persistent issues with running rspec globally or via `bundle exec rspec`. We have a dedicated `bin/rspec` which does work for everyone so far so that ought to be used in `bin/test`.
- Fixes typo in yarn lint command
- Replaced rspec command with rspec binstub
Closes #XXXXX …
> Chore: Use binstubs in bin/test

- app/components/content_container_component.html.erb
- app/javascript/controllers/diagramming_controller.js
- app/views/lessons/previews/show.html.erb
- app/views/lessons/show.html.erb
- bin/test
We initialise and run mermaid as soon as mermaid diagrams enter the DOM. If they have `display: none`, which they start off with as a child of a hidden parent element in the markdown preview page, they'll be rendered with incorrect SVG values - unable to rerender later as the mermaid text will have already been replaced.
- Runs `diagramming#connect` when switching to rendered preview tab in the markdown preview tool
- If in markdown preview page, only runs mermaid rendering on non-hidden diagrams
- Replaces deprecated `mermaid.init` method with recommended new `run` method as per documentation for v10+
Closes #4783
-   [x] The …
> Fix: Correctly render mermaid diagrams in markdown preview tool

- app/controllers/admin/dashboard_controller.rb
- app/views/admin/dashboard/show.html.erb
This change adds a tile indicating active announcement count on the admin dashboard. This will allow admins to briefly see if there have been new announcements. Clicking on the tile will navigate the admin to the announcements page.
- Adds a `.active_count` scope on `announcement.rb`. It builds off of the existing `.active` scope.
- The new scope is used in the admin/dashboardcontroller to populate `active_announcements_count`.
- `active_announcements_count` is presented in the view as another tile similar to the unresolved flags tile.
- The `announcement` model spec is updated to test for this new scope.
Closes #4619
-   [x] The …
> Feature: Adds active announcements tile to v2 admin dashboard.

- app/components/markdown/preview_component.rb
Some of our lessons have markdown tables but the necessary table tags (table/thead/tbody/tr/th/td) are not included in [rails-html-sanitizer's default allowed tags](https://github.com/rails/rails-html-sanitizer/blob/5104ca94644d0eb495ef0dced17f62c3e68df8c0/lib/rails/html/sanitizer.rb#L79), meaning our markdown preview tool won't render tables.
- Adds table/thead/tboyd/tr/th/td tags to `Markdown::PreviewComponent#allowed_tags`.
N/A
Go to the [markdown preview tool](https://www.theodinproject.com/lessons/preview) and enter
```md
| Verb   | Action | Example                                       |
| ------ | ------ | --------------------------------------------- |
| POST   | Create | `POST /posts` Creates a new blog post         |
| GET    | Read   | `GET /posts/:postid` Fetches a single post …
```
> Fix: Allow table rendering in markdown preview tool

- config/puma.rb
Because:
- Barnes doesn't need to be started in the puma config file.
> Chore: Puma config tweaks

- config/initializers/rack_attack.rb
Because:
- Investigating in NewRelic, Rack attack is adding significant time to requests.
This commit:
- Disables throttling with RackAttack, we have this covered with Cloudflare
> Fix: Slow response times

- config/routes.rb
This PR refactors the routing configuration for static pages in routes.rb by consolidating individual get routes into a single scope declaration for the static_pages controller. This change streamlines the routing, improves readability, and makes future management of static pages more efficient.
- Replaced individual get routes for static pages (home, about, faq, team, contributing, support_us, terms_of_use, privacy-policy, success_stories) with a scope declaration for the static_pages controller in routes.rb.
Closes #4855 
NA
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the …
> Chore: Consolidate static page routes using a scope declaration

- db/fixtures/paths/foundations/seed.rb
we are replacing Replit exercises with ones from `javascript-exercises`, so we need to do set up for Node.js earlier in the JavaScripts Basics course.
* Moves the Installing Node.js lesson so it is right before the Data Types and Conditionals lesson
- The Data Types and Conditionals lesson is where we will have new material from `javascript-exercises`
Related to https://github.com/TheOdinProject/curriculum/issues/29054
Since multiple repos are affected simultaneously, it may be ideal to merge all 3 PRs at once:
**Blockers:**
* Need to add the four new exercises to the `javascript-exercises` repo - https://github.com/TheOdinProject/javascript-exercises/pull/509
* Need to update the appropriate lessons within our `curriculum` repo to replace the Replit lessons currently there - …
> Feature: Relocate Node.js installation lesson

- app/controllers/application_controller.rb
Because:
- By default it already enabled and included in `ActionController::Base`. Our declaration in `ApplicationController` is unnecessary.
> Chore: Remove explicit protect from forgery callback

- app/views/guides/community/how_to_ask.html.erb
The channel names in the ["How to ask technical questions" page](https://www.theodinproject.com/guides/community/how_to_ask) were outdated.
- Updates names of mentioned channels.
- Use `<b>` tags for better "keyword" visibility for channel names.
- Adds missing period.
N/A
-   [x] …
> Chore: Update Discord channel names in "How to ask technical questions" page

- app/views/guides/community/rules.html.erb
Capitalize Googled to recognize Google as a trademarked term.
- "Asking questions that can be easily googled" -> "Asking questions that can be easily Googled"
Closes https://github.com/TheOdinProject/curriculum/issues/29308 …
> Fix: Capitalize "googled" -> "Googled"

- app/models/user.rb
- app/views/admin/learners/index.html.erb
- db/migrate/20250212143446_add_search_ts_vector_column_to_users.rb
- db/schema.rb
Because:
- The default configuration is not fast enough for the amount of data we have in production.
This commit:
- Adds a ts_vector column to the users table which we can search against - this is recommended in the [pg_search docs](https://github.com/Casecommons/pg_search?tab=readme-ov-file#using-tsvector-columns)
- Sneaks in a data-turbo-action="advance" attribute to the learner search results turbo frame so we can share search result pages with admins if we need to.
> Chore: Speed up admin learner search

- app/models/github/lesson_content_importer.rb
- app/models/omniauth_providers/builder.rb
Because:
- We moved away from this style a while ago and it being flagged in a pending Rubocop bump
> Chore: Remove Inline Private Attr Readers

- app/javascript/controllers/chart_controller.js
- app/views/admin/reports/lesson_completions/show.html.erb
- app/views/admin/reports/paths/show.html.erb
- app/views/admin/reports/users/index.html.erb
- package.json
- yarn.lock
Because:
- We're not using enough of it's features to justify the extra dependencies.
- It's preventing us from upgrading to Tailwind 4
> Chore: Remove Chart JS TW Colors Plugin

- app/components/progress_circle/component.html.erb
- app/components/progress_circle/component.rb
- app/javascript/controllers/progress_controller.js
Because:
- We can use the pathLength attribute to simplify our progress circle implementation and avoid needing to calculate and pass around the circumference of the circle when updating the percentage.
> Chore: Simplify progress circle implementation.

- Gemfile.lock
- app/components/complete/button_component.html.erb
- app/components/complete/icon_component.html.erb
- app/views/lessons/completions/create.turbo_stream.erb
Because:
- The complete button will appear to "hang" on slower connections.
This commit:
- Adds loading spinners to the complete button on lesson and course pages, that will only appear when toggling complete and the connection is slow.
- Bumps turbo-rails to latest patch version so we can use the :morph option when replacing content with turbo streams and avoid hover flashes on buttons as the content is replaced.
- Switch the complete button on course pages from links to buttons as they are not making GET requests.
- Removes some old Stimulus JS hooks for a complete controller that has been removed long ago.
Lesson page loading spinner:
https://github.com/user-attachments/assets/73ece768-9f82-4003-9bd9-5ed1260a5f7c
Course page loading spinner: …
> Feature: Provide loading feedback when completing a lesson on a slow connection

- app/components/flags/action_button_component.html.erb
Because:
- The latest version of Tailwind changes how the space utility works
> Fix: flag actions dropdown spacing

- app/assets/stylesheets/custom_styles/prism-theme.css
At small font sizes, the design of the comma in 'Andale Mono' closely resembles a period. This can cause confusion, particularly for new learners trying to distinguish between , and . in code examples. Given The Odin Project’s educational focus, clarity and readability of code snippets are essential.
- Removed `'Andale Mono'` from the font stack used for `<code>` and `<pre>` elements.
N/A
This change was made after noticing readability issues when viewing code blocks with small font sizes, where commas appeared nearly identical to periods when rendered in 'Andale Mono'. 
A related [issue](https://github.com/readthedocs/sphinx_rtd_theme/issues/524) is discussed on another project.
-   [x] I have thoroughly read and understand [The Odin Project Contributing …
> Feature: Remove 'Andale Mono' from code font stack for better readability

- app/components/sort_component.html.erb
Because:
- When I sort by newest or most liked, I want to be brought back to the first page and the top of the list, so I can actually see the most liked and newest submissions first.
- Closes https://github.com/TheOdinProject/theodinproject/issues/4347
This commit:
- Stops sending the current page param with the sort request.
> Feature: Return to first page when sorting

- app/views/lessons/project_submissions/index.html.erb
We have a great note about expectations from community solutions and advanced/out-of-scope features in the Recipes project. The community solutions component would benefit from a reminder about this and link to that Recipes project note. https://github.com/TheOdinProject/theodinproject/discussions/5037#discussioncomment-13757690
- Adds reminder about project expectations to community solutions component
N/A
- `Chore` - changes that have no …
> Feature: Add reminder and link about expectations to community solutions page

- config/environments/development.rb
- config/environments/test.rb
- config/initializers/new_framework_defaults_7_1.rb
Because:
* Part of the Rails 7.1 upgrade process
* Resolves #5048
> Chore: Update Active Record encryption configuration

- config/application.rb
Because: There was a backwards compatibility issue with the new defaults in 7.1
> Chore: Update encryption settings for ActiveRecord
